### PR TITLE
Allowing pod spec labels to start with numbers in addition to alphas.

### PR DESCRIPTION
**Pull request by mes5k**
This PR fixes [this issue](https://github.com/nextflow-io/nextflow/issues/1905).  One of the regexes used to sanitize the labels just omitted numbers.  Per [the spec](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set) (and manually created examples), labels should be allowed to start with numbers.

### CODE REVIEW

**Review by pditommaso — COMMENTED** [review]
Nice. Thanks for summiting this. Could you please sign-off the DC to make the bot happy? https://github.com/nextflow-io/nextflow/blob/master/CONTRIBUTING.md#contributing-code-changes

**Comment by pditommaso** [comment]
Nevermind! You did already, thanks Mike!

**Comment by mes5k** [comment]
Happy to help!

**Comment by pditommaso** [comment]
Merged manually 👍

**Pull request closed without merging**
