### PR TITLE
Add support for SGI MPT

### PR DESCRIPTION
**Pull request by robsyme**
The SLURM schedules running the SGI Message Passing Toolkit (MPT) instead of OpenMPI do not set the OMPI_COMM_WORLD_RANK environment variable. Fortunately, they do set SLURM_PROCID in the same way. This commit adds a test for this variable. If OMPI_COMM_WORLD_RANK is set, the SLURM_PROCID test is never run.

### CODE REVIEW

**Comment by pditommaso** [comment]
Interesting. How does it looks like your launcher script ?

**Comment by robsyme** [comment]
Hmm... This actually might be the wrong approach. I'm debugging on the cluster now. I think I just used the wrong submission script (should use srun on SLURM).

**Comment by pditommaso** [comment]
Let's try to recap. When using MPI the launcher script is executed with sbatch/qsub/etc. Then in the launcher script we use `mpirun` to launch NF, eg: 

```
mpirun --pernode nextflow run <your-project-name> -with-mpi [pipeline parameters]
```

What is supposed to be the equivalent for SGI (if any)?

**Comment by robsyme** [comment]
I think that the equivalent should be:

`srun nextflow run <your-project-name> -with-mpi [pipeline parameters]`

**Comment by pditommaso** [comment]
I would suggest to execute a dummy script instead of NF that just dumps the current environment for each task.

**Comment by robsyme** [comment]
It is possible with slurm to launch nextflow many times on a single node. For example, lets say we have a cluster composed of nodes with 16 cpus. If I have the following script `run.sh`:

```
#!/bin/bash --login
#SBATCH --job-name=nf-chickpea
#SBATCH --ntasks=32

srun nextflow run -with-mpi .
```

When I run `sbatch run.sh`, nextflow will be launched 32 times (16 on each node). For the 32 instances of nextflow, the env will include

- `SLURM_NODEID=0;SLURM_PROCID=0`
- `SLURM_NODEID=0;SLURM_PROCID=1`
- `SLURM_NODEID=0;SLURM_PROCID=2`
- `SLURM_NODEID=0;SLURM_PROCID=3`
- `SLURM_NODEID=0;SLURM_PROCID=4`
- ...
- `SLURM_NODEID=1;SLURM_PROCID=0`
- `SLURM_NODEID=1;SLURM_PROCID=2`
- `SLURM_NODEID=1;SLURM_PROCID=3`
- `SLURM_NODEID=1;SLURM_PROCID=4`
- ...
- `SLURM_NODEID=1;SLURM_PROCID=15`

We really only need to launch nextflow master when `$SLURM_NODEID == 0 && $SLURM_PROCID == 0` and then a daemon when `$SLURM_NODEID != 0 && $SLURM_PROCID == 0`.

Does this sound sensible to you?

**Comment by robsyme** [comment]
I guess that the 'correct' way to launch nextflow on SLURM would be a submission script that explicitly only launches nextflow once per node. Something like `better.sh`:

```
#!/bin/bash --login
#SBATCH --job-name=nf-chickpea
#SBATCH --ntasks=2
#SBATCH --ntasks-per-node=1

srun nextflow run -with-mpi .
```

**Comment by pditommaso** [comment]
> I guess that the 'correct' way to launch nextflow on SLURM would be a submission script that explicitly only launches nextflow once per node. 

Yes, also because by default NF allocates all available CPUs for the executed task. 

However the ability to run more than a NF instance for instance would be desirable, but it would be necessary to know how many CPUs per task are available. Is there a SLURM variable with such info ?

**Comment by robsyme** [comment]
Yes, there is: `$SLURM_CPUS_ON_NODE`. 

If I launch nextflow once for each core, things seems to go just fine. Even though each nextflow daemon will be reporting "I found 16 cpus", Nextflow is clever enough to work out which ones are duplicates. Launching like this (run nextflow 32 times):

```sh
#!/bin/bash --login
#SBATCH --ntasks=32
srun nextflow run -with-mpi  .
```

Gives topology like this:

`Topology snapshot [ver=31, servers=31, clients=0, CPUs=32, heap=830.0GB]`

Whereas a launch script like this:

```sh
#!/bin/bash --login
#SBATCH --ntasks=2
#SBATCH ntasks-per-node=1
srun nextflow run -with-mpi  .
```

Gives cluster topology:

`Topology snapshot [ver=2, servers=2, clients=0, CPUs=32, heap=53.0GB]`

**Comment by pditommaso** [comment]
Hi Rob, sorry for the late reply. Since this uses a different set of variables and command line, I think it would be better to introduce a specific option to handle SGI execution eg. `-with-sgi`. 

Between the other things I was looking for some documentation about SGI MPT interface but I was unable to find it. Do you have any link to a documentation page?

**Comment by robsyme** [comment]
No worries at all - my workaround is totally fine at the moment. I'll get some more details from our HPC admins (@Pawseyops). Will be on leave next week with intermittent net access (I'll be in Spain for a bit!), but will pick this up when I get back if not beforehand.

**Comment by robsyme** [comment]
I've also just discovered that on a different cluster (Crays), the relevant environment variable is `$ALPS_APP_PE`. There must be a more universal way to do this. I will check and report back.

**Comment by pditommaso** [comment]
Hi Rob, I'm reading only now that your come to Spain. I hope that you won't come to Barcelona without letting me know that!

About this issue, how you any idea if SGI is a SLURM specific technology (I guess no)? Can it coexist with OpenMP?

**Comment by pditommaso** [comment]
@robsyme I've merged manually this PR. See https://github.com/nextflow-io/nextflow/commit/13f3a091d7dc24c5712216c34b58d7ce8a947d0a 

Thanks a lot

**Pull request closed without merging**
