### PR TITLE
Improve secrets rendering

### PR DESCRIPTION
**Pull request by pditommaso**
This PR simplifies the rendering of secrets in the the `nextflow config` using a AST transformation instead of using the `SecretContext` class.

See also https://github.com/nextflow-io/nextflow/pull/4177

### CODE REVIEW

**Comment by pditommaso** [comment]
Should be OK, now.

**Comment by bentsherman** [comment]
Code looks good. Did you do a manual end-to-end test?

**Review by bentsherman — APPROVED** [review]
Manual test passed 👍

**Comment by pditommaso** [comment]
Thanks Ben

**Pull request merged**
