### PR TITLE
recognises more UGE states. Closes nextflow-io/nextflow#1461

### PR DESCRIPTION
**Pull request by DaGaMs**
Signed-off-by: Benjamin Schuster-Böckler <ben.sb@methodicate.com>

### CODE REVIEW

**Comment by DaGaMs** [comment]
Oops, seems some tests are failing. I'll try to figure out how to run them locally 🙈

**Comment by DaGaMs** [comment]
I fixed the test failures - not sure why the build scripts don't kick in?

**Comment by pditommaso** [comment]
There was a glitch on GH configuration. Now it's green. The PR is good but the test looks incomplete, please add a line like 

```
 1267 0.17254 run_mappin epalumbo     h     08/29/2014 11:28:11 short@node-ib0208bi.linux.crg. 
``` 

For each of the new state introduced. It's very important to keep stable over time. Thanks!

**Comment by pditommaso** [comment]
I've managed to restart travis, but it looks failing. Do the tests run locally?

**Comment by pditommaso** [comment]
Thanks a lot for this contribution.

**Pull request merged**
