### PR TITLE
Implement SIF ORAS protocol to HTTP

### PR DESCRIPTION
**Pull request by pditommaso**
This PR draft the mapping of ORAS images names to HTTP ones.

### CODE REVIEW

**Comment by marcodelapierre** [comment]
( a lot of extra commits due to fixing commit sign-offs - sorry! )

**Comment by marcodelapierre** [comment]
@pditommaso  ready for review

**Comment by marcodelapierre** [comment]
Still one failing unit test on CI `should resolve docker container with wave container` in `WaveContainerResolverTest`, call to `resolveImage` at line 53.   

The responsible bit of code is in [`WaveContainerResolver`](https://github.com/nextflow-io/nextflow/pull/5000/files#diff-4a58d66fa4d344ac7eaccca1fb2e8ae63930541b356d989a25abaa98b4c0ca00), new lines 98-108. 

Looking into it.

**Comment by marcodelapierre** [comment]
@pditommaso  @ewels  following the meeting today, I have implemented the workaround for the URI in the case of Seqera Containers: https://github.com/nextflow-io/nextflow/blob/wave-sif-http/plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveClient.groovy#L392-L400

Ready for review   (with one last unit test to fix)

**Comment by marcodelapierre** [comment]
OK, last outstanding unit test fixed:
* local tests OK
* github CI running now.

**Comment by marcodelapierre** [comment]
@pditommaso  ready for review

**Comment by marcodelapierre** [comment]
Do we need an integration test for running with Wave plugin and using Http over Oras?

**Comment by pditommaso** [comment]
It may be useful. Some wave tests are [here](https://github.com/nextflow-io/nextflow/blob/241a31ac5ebb6227a30779af3b731260ca2326c2/validation/wave.sh#L1-L1)

**Comment by pditommaso** [comment]
Let's put in hold, not sure anymore it makes sense to implement this

**Comment by pditommaso** [comment]
Closing this. If needed we may we a different approach because http requests needs to be authenticated

**Pull request closed without merging**
