### PR TITLE
Add developer docs

### PR DESCRIPTION
**Pull request by bentsherman**
- Add the developer docs I wrote with class diagrams
- Add section headers to the docs navbar
- Add the Nextflow green to navbar

TODO:
- [x] Add pages for remaining class diagrams

### CODE REVIEW

**Comment by bentsherman** [comment]
Look at that beautiful preview! 😄

**Comment by bentsherman** [comment]
@pditommaso can we merge this one

**Comment by marcodelapierre** [comment]
I am keen to provide an external review on the dev docs, will be on it next Monday.

**Comment by marcodelapierre** [comment]
Hi @bentsherman @pditommaso  , here some comments/suggestions, from a contents perspective:

Navigation bar
- I *LOVE* the classification of the sections!
- I suggest moving "Plugins" from "Execution" to "Additional software"

Section Contributing -> Overview
- All links tested OK
- Class Diagrams: I suggest adding a link to the Packages section
- Building and Testing: isn't Gradle also a requirement for building?

Section Contributing -> Packages
- I haven't read everything, mostly flied over the introductory statement and the diagram
- nextflow: Nextflow and Channel still work in progress? any minimal info that can be inserted?
- nextflow.ast: please define/explain concisely "AST"
- nextflow.cache: could these (and any other type of) arrows be introduced in the main Packages page?

Hope this helps to get closer to merge ;)

**Comment by bentsherman** [comment]
Thanks for the feedback Marco. I will push a few changes later.

I would rather keep the Plugins page where it is, because it is a core part of the runtime. The core plugins aren't additional software after all.

The Gradle CLI is usually only used to bootstrap a project, at which which a launcher script called `gradlew` is created and used thereafter to run Gradle tasks, including installing the Gradle runtime. Java is really all you need!

I don't say much about the Nextflow and Channel classes because they are already covered in the user docs, namely the "Scripts" and "Channels" pages.

Regarding the `nextflow.cache` page, I'm not sure what you mean? I explain the three types of arrows under "Class Diagrams"

**Comment by ewels** [comment]
I think mermaid diagrams [should work](https://stackoverflow.com/a/67380521/713980)?

> `mermaid` is perfectly integrated to MyST-parser.
>
> You only need to call it like that with `{mermaid}`:
>
> ````markdown
> ```{mermaid}
> graph LR
>   a --> b
> ```
> ````
>
> No need to define in `conf.py` a `def setup(app):` only:
>
> ```python
> extensions = ['myst_parser', 'sphinxcontrib.mermaid']
> ```

**Comment by bentsherman** [comment]
That's weird, I just opened the cache page in the deploy preview and the diagram works 🤷‍♂️

**Comment by ewels** [comment]
Are we talking about this? In which case yeah, works fine for me too..

CleanShot 2023-08-29 at 15 45 16@2x

**Comment by marcodelapierre** [comment]
I can see that one fine, too, I mean the *Class Diagram* section (not page, sorry) inside the Overview page, `docs/_build/html/developer/index.html` in the built docs.

See screenshot below:


Screenshot 2023-08-30 at 10 03 08 am

**Comment by ewels** [comment]
Nice, preview here: https://deploy-preview-4065--nextflow-docs-staging.netlify.app/developer/index.html#class-diagrams

> [!NOTE]
> @marcodelapierre note that the deployment preview [mentioned in a comment](https://github.com/nextflow-io/nextflow/pull/4065#issuecomment-1614954441) further up continuously updates whenever a new commit is pushed, so you can just look at that rather than needing to build locally...

**Comment by marcodelapierre** [comment]
> I see, well, I don't want to put a whole mermaid diagram there just to show the arrows, but I can put the equivalent code which should give some hint. They are basically the conventions used by Mermaid diagrams: https://mermaid.js.org/syntax/classDiagram.html#defining-relationship

Completely agree, a legend would do in my opinion

**Comment by marcodelapierre** [comment]
ah damn! Sorry @bentsherman , my finger slipped on the

**Comment by marcodelapierre** [comment]
> Nice, preview here: https://deploy-preview-4065--nextflow-docs-staging.netlify.app/developer/index.html#class-diagrams
> 
> Note @marcodelapierre note that the deployment preview [mentioned in a comment](https://github.com/nextflow-io/nextflow/pull/4065#issuecomment-1614954441) further up continuously updates whenever a new commit is pushed, so you can just look at that rather than needing to build locally...

thanks Phil, hadn't notices the preview feature! -- rather than rebuilding myself, I think I would rather lazily asked Ben for a snapshot 🤣

**Comment by ewels** [comment]
@marcodelapierre - I discovered website deployment previews on PRs rather recently, and now I can't live without them; adding them to every repository I can 😆

**Comment by marcodelapierre** [comment]
I tooootally understand, from now on I won't live without them neither!!

**Comment by ewels** [comment]
@pditommaso don't make me 😢 Surely this is negated by me [stripping out unnecessary CI checks](https://github.com/nextflow-io/nextflow/pull/4250)? 😉 



(I was about to argue that I would spend the CPU cycles building locally anyway, but I guess you're right that the web server is running constantly for us to have them).

**Comment by marcodelapierre** [comment]
ah, good point Paolo!

**Comment by pditommaso** [comment]
Ok, nice. I made a few changes in the TOC. Nice job!

**Comment by mribeirodantas** [comment]
🤩 So happy that this PR has been merged! Way to go, guys!

**Comment by marcodelapierre** [comment]
Love this, love the refreshed docs look! Great initiative @bentsherman! 🤩

**Pull request merged**
