### PR TITLE
[WIP] Use the Sphinx press theme 

### PR DESCRIPTION
**Pull request by abhi18av**
Creating a placeholder PR for the `press` Sphinx theme.

Here are some points to consider 

#### General look and feel 🤩 

Screenshot 2022-04-14 at 11 12 41 AM

Screenshot 2022-04-14 at 11 12 21 AM

-------

#### The image sizes needs to be tweaked (especially in `Tracing and visualization` section) 🚧  📸 

image

-------

#### A list of warnings for completeness (similar to the previous theme) 🗒️ 

```
(sphinx-env) Abhinavs-MacBook-Pro:docs eklavya$ make clean html

rm -rf _build/*
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v4.5.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 29 source files that are out of date
updating environment: [new config] 29 added, 0 changed, 0 removed
reading sources... [100%] tracing
/code/nextflow/docs/azure.rst:5: WARNING: Duplicate explicit target name: "azure batch".
/code/nextflow/docs/container.rst:5: WARNING: Duplicate explicit target name: "official documentation".
/code/nextflow/docs/dsl2.rst:496: WARNING: Literal block expected; none found.
/code/nextflow/docs/process.rst:5: WARNING: Duplicate explicit target name: "kubernetes".
/code/nextflow/docs/script.rst:5: WARNING: Duplicate explicit target name: "read more".
/code/nextflow/docs/script.rst:5: WARNING: Duplicate explicit target name: "read more".
/code/nextflow/docs/script.rst:5: WARNING: Duplicate explicit target name: "read more".
/code/nextflow/docs/script.rst:5: WARNING: Duplicate explicit target name: "read more".
/code/nextflow/docs/script.rst:5: WARNING: Duplicate explicit target name: "read more".
/code/nextflow/docs/sharing.rst:5: WARNING: Duplicate explicit target name: "bitbucket".
/code/nextflow/docs/sharing.rst:5: WARNING: Duplicate explicit target name: "this link".
looking for now-outdated files... none found
pickling environment... done
checking consistency... /code/nextflow/docs/dnanexus.rst: WARNING: document isn't included in any toctree
/code/nextflow/docs/example.rst: WARNING: document isn't included in any toctree
/code/nextflow/docs/faq.rst: WARNING: document isn't included in any toctree
/code/nextflow/docs/metrics.rst: WARNING: document isn't included in any toctree
done
preparing documents... WARNING: unsupported theme option 'display_version' given
done
writing output... [100%] tracing
generating indices... genindex done
writing additional pages... search done
copying images... [100%] images/dag-mermaid.png
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 16 warnings.

The HTML pages are in _build/html.

Build finished. The HTML pages are in _build/html.

```

-------

#### Maintenance 

The original author is looking for others to take over the project ⚠️ 

https://github.com/schettino72/sphinx_press_theme#looking-for-project-maintainers

### CODE REVIEW

**Comment by bentsherman** [comment]
Is the theme independent from the markup language, such that we can still use it if we switch to markdown? Also, weren't we considering switching to mkdocs-material ?

**Comment by pditommaso** [comment]
I'm very pragmatic on this. I think it would be enough just to have a prettier html/css template. 

> Is the theme independent from the markup language

Yes, but those themes are for Sphynx

**Comment by bentsherman** [comment]
> I think it would be enough just to have a prettier html/css template.

Do you mean keeping the RTD theme and making some improvements? Just from reading the Snakemake docs (which also uses RTD) it looks like we could improve some things. I would support that.

**Comment by pditommaso** [comment]
I mean keep the rst docs and create a brand new theme

**Comment by abhi18av** [comment]
Closing this in favor of https://github.com/nextflow-io/nextflow/pull/2835

**Pull request closed without merging**
