### PR TITLE
Add checks to dynamic trace logs

### PR DESCRIPTION
**Pull request by bentsherman**
Add `log.isTraceEnabled()` check to certain log messages with dynamic strings, so that the strings aren't evaluated when trace logging is disabled. Mainly for trace logs that occur often or print large data structures.

### CODE REVIEW

**Comment by pditommaso** [comment]
Good intent but it's not needed! The @Slf4j does that for you, adding an `if` guard to each log statement 

https://www.infoworld.com/article/2074117/easy-groovy-logger-injection-and-log-guarding.html

**Comment by bentsherman** [comment]
Don't think so. There is a [customer ticket](https://support.seqera.io/a/tickets/3741) where an error was reported by [this line](https://github.com/nextflow-io/nextflow/blob/5b5b579d603475d786d6ffed8ae63f9b7191560b/modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy#L2379), a trace message even though trace logging was disabled. The error came from printing a list object to the log message, which means the GString was still being evaluated.

The logging library may be adding those guards, but apparently it does not prevent the log message from being evaluated.

**Comment by pditommaso** [comment]
That's sounds very strange. Worth to open a bug with the corresponding error trace. Could not find it.

**Comment by bentsherman** [comment]
Here is the [log](https://seqera.attachments8.freshdesk.com/data/helpdesk/attachments/production/73067322271/original/nextflow.log.txt?response-content-type=text%2Fplain&Expires=1692019889&Signature=Mm3wd95IMMdjUJnkonyQqbiLXK95pmGOLmSZw725wZvF18fb8yFB2kuRYwL9b0s8bGdYHFvdvLwcqGUbWdZ7qPK~zIzYlivCOy2VBPMTD2FYotwFnJ8GwcVg~wcymACmHaOh~MfNO0Z4r3oL-PcChU4-zk5zZw3dSMBJ~8va~D280Olln-SGGD7uS2e4ZmA-0o-2R5Z7QlliDtZihUjqPhZTO8yH2e71WMyzIeeC0pwv94FrpLFJYgs0jTiFhuvS0KpsimcCk0pNhqO35EmGP21Ma2VBsLCbqkFpp98F0nqVhNPh22Ij9Sm-HmYRgwejEjU~a-w~NKzspp3oOoZ1FA__&Key-Pair-Id=APKAJ7JARUX3F6RQIXLA) from that ticket, though not sure if the link works for you. It's the last public note from Anthony.

Here is the error trace:
```
Aug-11 09:42:17.357 [Actor Thread 8] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=PRE_PROCESSING:FASTQC; work-dir=null
  error [java.util.ConcurrentModificationException]: java.util.ConcurrentModificationException
Aug-11 09:42:17.368 [Actor Thread 8] ERROR nextflow.processor.TaskProcessor - Error executing process > 'PRE_PROCESSING:FASTQC'

Caused by:
  java.util.ConcurrentModificationException

java.util.ConcurrentModificationException: null
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:751)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:749)
	at org.codehaus.groovy.runtime.InvokerHelper.formatMap(InvokerHelper.java:722)
	at org.codehaus.groovy.runtime.InvokerHelper.format(InvokerHelper.java:662)
	at org.codehaus.groovy.runtime.InvokerHelper.formatCollection(InvokerHelper.java:770)
	at org.codehaus.groovy.runtime.InvokerHelper.format(InvokerHelper.java:659)
	at org.codehaus.groovy.runtime.InvokerHelper.formatCollection(InvokerHelper.java:770)
	at org.codehaus.groovy.runtime.InvokerHelper.toListString(InvokerHelper.java:886)
	at org.codehaus.groovy.runtime.InvokerHelper.toListString(InvokerHelper.java:874)
	at org.codehaus.groovy.runtime.InvokerHelper.toListString(InvokerHelper.java:863)
	at org.codehaus.groovy.runtime.InvokerHelper.write(InvokerHelper.java:555)
	at groovy.lang.GString.writeTo(GString.java:200)
	at groovy.lang.GString.toString(GString.java:157)
	at org.codehaus.groovy.reflection.stdclasses.StringCachedClass.coerceArgument(StringCachedClass.java:45)
	at org.codehaus.groovy.reflection.ParameterTypes.coerceArgumentsToClasses(ParameterTypes.java:152)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap.invoke(PojoMetaMethodSite.java:197)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.processor.TaskProcessor$TaskProcessorInterceptor.beforeRun(TaskProcessor.groovy:2379)
	at groovyx.gpars.dataflow.operator.DataflowProcessor.fireBeforeRun(DataflowProcessor.java:371)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.onMessage(DataflowOperatorActor.java:106)
	at groovyx.gpars.actor.impl.SDAClosure$1.call(SDAClosure.java:43)
	at groovyx.gpars.actor.AbstractLoopingActor.runEnhancedWithoutRepliesOnMessages(AbstractLoopingActor.java:293)
	at groovyx.gpars.actor.AbstractLoopingActor.access$400(AbstractLoopingActor.java:30)
	at groovyx.gpars.actor.AbstractLoopingActor$1.handleMessage(AbstractLoopingActor.java:93)
	at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by pditommaso** [comment]
Fascinating. I do not fully understand why it's evaluated. However, the root problem is that the message (aka the process inputs hold a map object that's modified somewhere else in the pipeline code. 

Therefore, bypassing *this* error will just make it happen somewhere else. It's a pipeline code fault

**Comment by bentsherman** [comment]
I know, but the particular error is beside the point. The point here is that the dynamic strings are always evaluated, which creates a lot of useless computation when trace logging is disabled. The `log.isTraceEnabled()` is already used throughout the code, I assume for this purpose.

**Comment by pditommaso** [comment]
Umm. it may be something related with @Slfj annotation and nested classes. I've made this test 👉 ac5d866f and that's what I'm getting 

```
Before run 1
Before run 2
Before run 3
Before run 4
Checking cache [0]
Checking cache [0]
Checking cache [0]
Checking cache [0]
```

**Comment by pditommaso** [comment]
Fixed via 50f6f6d59

**Comment by bentsherman** [comment]
Thanks, then the changes to NextflowDSLImpl should also be added because they are in an inner class. Also those trace logs are the most hefty.

**Comment by pditommaso** [comment]
It's not a problem considering they are only invoked once during the script interpretation.

**Comment by bentsherman** [comment]
Yes, but for things like the preview commands or a Nextflow language server (which would use this code), the parsing should be as fast as possible.

**Comment by pditommaso** [comment]
We are to write this before having a lang server :D

**Pull request closed without merging**
