### PR TITLE
Add engineOptions setting to Docker configuration.

### PR DESCRIPTION
**Pull request by manuelesimi**
Sample usage:
```
docker {
    enabled = true
    engineOptions = "--tlsverify --tlscacert=\"/Users/mas2182/.docker/machine/machines/dev/ca.pem\" --tlscert=\"/Users/mas2182/.docker/machine/machines/dev/cert.pem\" --tlskey=\"/Users/mas2182/.docker/machine/machines/dev/key.pem\" -H=tcp://192.168.99.100:2376"   
    runOptions = " -v /Users/mas2182/temp/ARTIFACT_REPOSITORY:/scratchLocal/gobyweb/ARTIFACT_REPOSITORY"       
}
```

### CODE REVIEW

**Comment by pditommaso** [comment]
Manuele, thanks a lot for this contribution. Could you please add a test for this feature in the `DockerBuilderTest` class?

**Comment by manuelesimi** [comment]
Paolo,

I added and pushed a test case. The only problem is that when I try to run the tests, the execution got stuck with:

> Building 98% > :nxf-gridgain:test > 4 tests completed

You may want to run the tests in your environment before pulling the change.

**Comment by pditommaso** [comment]
Thanks a lot for that. No problem for the tests, as you can see we have a couple of CI services checking that.  

BTW do you need urgently a new release? (I'm out of office and I have a very bad connection that does allow me to upload it).

**Comment by manuelesimi** [comment]
We are not in a super-urgent need right now. The next NextFlow workbench release will not include our abstraction over the docker integration, so for the moment we can use our modified version internally.

Thanks!

**Comment by pditommaso** [comment]
I've just released version `0.15.3` that includes this pull request.

**Comment by manuelesimi** [comment]
Thanks for letting me know.
I just tested the new version and it works well. You may want to update 1) the doc page at http://www.nextflow.io/docs/latest/config.html#config-docker describing the new runEngine setting and 2) make an announcement on the forum (I missed for instance 0.15.2 for a while because it was not announced and it greatly fixes some issues we experienced here).
Super-thanks!

**Comment by pditommaso** [comment]
Thanks for remind me that. I was forgetting to upload the docs.

**Pull request merged**
