### PR TITLE
add new names and adjectives.

### PR DESCRIPTION
**Pull request by MaxUlysse**
- sorted adjectives
- new adjectives: `astonishing`, `deadly`, `fabulous`, `friendly`, `marvelous`, `mighty`, `nice`
- new names: `ampere`, `becquerel`, `bernard`, `coulomb`, `cuvier`, `dalembert`, `descartes`, `fourrier`, `gutenberg`, `laplace`, `lavoisier`, `legentil`, `mandelbrot`, `pesquet`, `poisson`

### CODE REVIEW

**Comment by ewels** [comment]
🇫🇷   🎉

**Comment by pditommaso** [comment]
I've noticed a kind of french proud! I need to compensate with some Italian scientists ! LOL 

Thanks guys!

**Comment by MaxUlysse** [comment]
It was easy, you have lists of everything on wikipedia ;-)

https://en.wikipedia.org/wiki/Category:Lists_of_scientists_by_nationality

**Comment by pditommaso** [comment]
Added mines 😂 

https://github.com/nextflow-io/nextflow/commit/2a2fe47ddde61efa2a4f7c17bf62982b21190c64

**Pull request merged**
