### PR TITLE
Add support for FUSION_AWS_REGION 

### PR DESCRIPTION
**Pull request by pditommaso**
This PR adds support for passing the AWS region to Fusion when using a custom endpoint.

### CODE REVIEW

**Review by jordeu — APPROVED** [review]

**Comment by abhi18av** [comment]
Oh, this is a welcome addition - would be great to have this in the stable release series 🤩

**Comment by jordeu** [comment]
We have only seen this to be a problem when using OVH S3 service, most of the other S3 services there is no need to set the region when using a fixed endpoint. Just for curiosity @abhi18av, have you seen same problem with a different S3 service?

**Comment by abhi18av** [comment]
_To some extent_, yes I have seen similar problems with Oracle Cloud Infrastructure (OCI) Object Storage S3 API  


(🗒️  _Personal note_: Didn't report this earlier since I wasn't sure to what extent other s3 API providers would be supported and I didn't want to add on to your workloads. Though if there's interest in addressing this - I'd be happy to connect during the week and setup the creds for your exploration 😊  ) 


**References**: 
- https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm
- https://docs.oracle.com/en-us/iaas/Content/Object/Concepts/dedicatedendpoints.htm 


# Error observed with non-home region


**NOTE**: The home region is NOT `af-johannesburg-1`, which I've used in the `nextflow.config` so that makes for a good test.

However, worth noting that even with the home region (`eu-frankfurt-1` in my case) the AWS sdk client complains about 

```
N E X T F L O W  ~  version 23.10.0
Launching `https://github.com/nextflow-io/hello` [stoic_pike] DSL2 - revision: 1d71f857bb [master]
ERROR ~ The secret key required to complete authentication could not be found. The region must be specified if this is not the home region for the tenancy. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: null; S3 Extended Request ID: null; Proxy: null)

```

### Stacktrace from `.nextflow.log` file 

```
com.amazonaws.services.s3.model.AmazonS3Exception: The secret key required to complete authentication could not be found. The region must be specified if this is not the home region for the tenancy. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: null; S3 Extended Request ID: null; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403)
	at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:421)
	at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6532)
	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1861)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1821)
	at nextflow.cloud.aws.nio.S3Client.putObject(S3Client.java:210)
	at nextflow.cloud.aws.nio.S3FileSystemProvider.createDirectory(S3FileSystemProvider.java:488)
	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
	at java.base/java.nio.file.Files.createDirectories(Files.java:743)
	at java_nio_file_Files$createDirectories.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at nextflow.extension.FilesEx.mkdirs(FilesEx.groovy:493)
	at nextflow.Session.init(Session.groovy:393)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:128)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:372)
	at nextflow.cli.Launcher.run(Launcher.groovy:499)
	at nextflow.cli.Launcher.main(Launcher.groovy:670)
```


### Relevant `nextflow.config` file

```nextflow
docker {
    enabled = true
}

fusion {
    enabled = true
    privileged = true
    exportStorageCredentials = true
    logLevel = "debug"
    logOutput = "stdout"
}

wave {
    enabled = true
}


process {
    container = "quay.io/nextflow/rnaseq-nf:v1.2"
    memory = "2048.MB"
    cpus = 2
    time = "1h"
}


profiles {
    ocis3_af {

        workDir = "s3://temp/work"

        aws {
          region = "af-johannesburg-1"

          accessKey= "REDACTED"
          secretKey= "REDACTED"

          client {
             endpoint = "https://REDACTED.compat.objectstorage.af-johannesburg-1.oci.customer-oci.com"
             s3PathStyleAccess = true
          }
        }
    }


}

```

# Error observed with home region

### Stacktrace 

This seems to point to hostname resolution issues 

```
Caused by: java.net.UnknownHostException: s3.eu-frankfurt-1.amazonaws.com
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1519)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1378)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27)
	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy27.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	... 28 common frames omitted
```

**Comment by jordeu** [comment]
It might be the same problem. I ping you when the new release is out at the end of this week.

**Pull request merged**
