### PR TITLE
Remove 'defaults' conda channel from docs.

### LINKED ISSUE #5601: Remove Conda defaults channel from documentation or put disclaimer
Hi!

Thanks for developing Nextflow and the complete universe of useful tools around it!

Recently, we got aware that Anaconda Inc. changed its Terms and Conditions for the usage of their "defaults" channel. Institutions larger than 200 employees may get charged quite considerable sums. 
The documentation in https://github.com/nextflow-io/nextflow/blob/master/docs/conda.md lists "defaults" channel. 

Could it be useful to highlight the potential issues in a disclaimer there, make the use of the "defaults" channel optional or remove the "defaults" channel from the examples?

cheers

### PR DESCRIPTION
**Pull request by ewels**
Fixes #5601

### CODE REVIEW

**Comment by christopher-hakkaart** [comment]
Looks good to me.

**Comment by pditommaso** [comment]
Failing tests 😢

**Comment by bentsherman** [comment]
@ewels you need to either revert the changes to CondaCacheTest or update the expected conda hashes in those tests. Your choice 😅

**Comment by ewels** [comment]
I was hoping that the CI would print out the new hash in the log when it failed, so that I could just copy it in without running anything locally. However no such luck by the look of it 😢

**Comment by bentsherman** [comment]
You have to download the test report given under "Publish tests report" to see that. Or run the test locally, it gives you the same report

**Comment by ewels** [comment]
@bentsherman thank you! I'd forgotten that this existed. Would be fun to set up a GitHub action to post a link to these assets as a comment on the PR if the tests fail!

**Pull request merged**
