### PR TITLE
Lsf never rerunnable

### PR DESCRIPTION
**Pull request by timini**
This MR is to add an "non rerunnable" option for LSF 

https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=options-rn

### CODE REVIEW

**Comment by pontus** [comment]
While I don't have any objections to the code, I miss a link to an issue or other discussion about the use case for this and why it's important enough that it can't be managed through `clusterOptions`.

**Comment by pditommaso** [comment]
Same here

**Comment by timini** [comment]
it is a workaround for this issue 

https://github.com/nextflow-io/nextflow/issues/4935

**Comment by pditommaso** [comment]
It would be better to solve https://github.com/nextflow-io/nextflow/issues/4935 as it provides a more general solution

**Comment by pditommaso** [comment]
Closing in favor of the solution described [here](https://github.com/nextflow-io/nextflow/issues/4935#issuecomment-2066786351)

**Pull request closed without merging**
