### PR TITLE
Adds readOnly flag to k8s volume mounts

### PR DESCRIPTION
**Pull request by mes5k**
Signed-off-by: Mike Smoot <msmoot@illumina.com>

For https://github.com/nextflow-io/nextflow/issues/2012

### CODE REVIEW

**Review by pditommaso — CHANGES_REQUESTED** [review]
I think it's fine. Please an entry in the corresponding docs 

https://github.com/nextflow-io/nextflow/blob/51c87bb5cf7b9cd2296d93b77887d1d14939dc8e/docs/process.rst#L1966-L1979

**Comment by mes5k** [comment]
Great, updated the docs!

**Review by pditommaso — APPROVED** [review]
Awesome. Thanks a lot Mike

**Comment by mes5k** [comment]
My pleasure!

**Pull request merged**
