### PR TITLE
Implement the scoringFunction-v1.0 for parameter optimization

### PR DESCRIPTION
**Pull request by abhi18av**
This PR is an attempt to address the ideas discussed in https://github.com/nextflow-io/nextflow/issues/168

Here's the overall roadmap, for `scoringFunction v1.0`that  I have in mind.

- [ ] At parsing level, implement a task directive `scoringFunction`, similar to `afterScript`
```
 scoringFunction  'SOME_BASH_COMMAND_OR_SCRIPT', optimization: 'max', strategy: 'brute_force'
```
- [ ] Indicate which variables need to be used to construct the `search-space`

Please feel free to review and suggest changes.

### CODE REVIEW

**Comment by pditommaso** [comment]
We are very far from 1.0 :). Yes, let's prototype just having just `scoreFunction` as a plain string that's executed after the command and before `afterScript` (outside the container, I expect the score function to have its own container)

**Comment by abhi18av** [comment]
@pditommaso , for a start I've modelled the `scoringFunction` directive similar to `afterScript` and added the tests and all tests are passing. However, for some reason, the locally built `nextflow` binary does not recognize the `scoringFunction` directive.


image


Here are the contents of 

- `scratch.nf`

```nextflow
process TASK {
echo true
afterScript "bash $launchDir/afterScript.sh"
scoringFunction "bash $launchDir/scoringFunction.sh"

script: 
"""
echo "Hello, world!"
"""

}

```

- `afterScript.sh`

```
echo "AFTERSCRIPT"

```

- `scoringFunction.sh`

```
echo "SCORING_FUNCTION"

```

I've attached the `.nextflow.log` file as well.

[nextflow.log](https://github.com/nextflow-io/nextflow/files/5770213/nextflow.log)

**Comment by pditommaso** [comment]
It has to be added to this list 
https://github.com/nextflow-io/nextflow/blob/3de45c2287d78a70ac477d705aa9b8a4c019e629/modules/nextflow/src/main/groovy/nextflow/script/ProcessConfig.groovy#L48-L89

also, let's call it `score` instead of `scoringFunction`

**Comment by abhi18av** [comment]
Nope, no dice 🎲 🤔 

image

**Comment by pditommaso** [comment]
The error stack trace in the .nextflow.log file is your friend :)

**Comment by pditommaso** [comment]
We lost momentum with this. We may re-open this at some point where there's a more concrete request for this feature

**Pull request closed without merging**
