### PR TITLE
Add support for Azure low-priority VMs

### PR DESCRIPTION
**Pull request by pditommaso**
This PR adds initial support for Azure Low-priority VMs by adding a new `lowPriority` boolean option to the azure pool settings

### CODE REVIEW

**Comment by pditommaso** [comment]
@adamrtalbot should be ok now

**Comment by pditommaso** [comment]
Nice, let's merge

**Comment by abhi18av** [comment]
Great work guys - I believe this one is definitely worth having in the LTS version!

We can make use of the Low priority VMs as part of Azure megatests on the nf-core side.

**Comment by pditommaso** [comment]
We can give it a try

**Pull request merged**
