### PR TITLE
Rename pod directive to podOptions

### PR DESCRIPTION
**Pull request by bentsherman**
This PR renames the `pod` directive to `podOptions`, for consistency with `clusterOptions`, `containerOptions`, etc. Nextflow will still accept `pod` but will print a deprecation warning.

### CODE REVIEW

**Comment by pditommaso** [comment]
I will the idea, I'd resist making this change only for naming uniformity. I guess there's a lot of config out there that would be impacted and can be annoying to update them. 

I would keep this possibility if at some point there's need to change the pod configuration structure or keep in sync with the config re-engineering #2723

**Comment by bentsherman** [comment]
To be clear, this PR only deprecates the `pod` option, so `pod` is still accepted but users get a deprecation warning. Anyway, this PR is here if you want to merge it. Although I left it as a draft because I wanted to make sure I did the deprecation correctly. Still need to test locally.

**Comment by pditommaso** [comment]
Understand that, but still think we can keep this for when it may be needed to re-organise the K8s config. Also considering the discussion to use jobs instead of pods #2751, does still make sense to use `podOptions`? maybe it may be better turn into `k8sOptions`. 

Closing this for now.

**Comment by bentsherman** [comment]
I think `podOptions` still makes sense because it refers to the pod-specific options, whether the pod is standalone or part of a job. `k8sOptions` would be confusing with the `k8s` config options, we would want to rethink how the k8s options are organized overall.

**Pull request closed without merging**
