### PR TITLE
Charliecloud support v3

### PR DESCRIPTION
**Pull request by phue**
As of Charliecloud `v0.28`, support in Nextflow stopped working because the expected CLI arguments for the pull command changed in that release. dd69f62c648cf1126225bbdf7e2e08004e8f4f94 addresses that, raising the required Charliecloud version to >=0.28.

Bonus:
Charliecloud has recently gained some nice additions and default settings. This allows for substantial cleanup of the code that
builds the bash wrapper, making some of my earlier workarounds obsolete. See 799e9c33235a1df8cae83fe769dc79b56cac890b for details.

### CODE REVIEW

**Comment by pditommaso** [comment]
This is nice, but what about potential users that may be using old versions?

**Comment by phue** [comment]
In my opinion, users should be encouraged to upgrade, Charliecloud itself has stabilised quite a bit over the last couple of releases.
It's also straightforward to update/install, doesn't require admin privileges whatsoever.

I think keeping legacy support would create unwarranted overhead, the new implementation is much cleaner and more future proof.

**Comment by pditommaso** [comment]
I tend to agree, but it's always bad to break changes. Though looking at the code, the only way to keep the compatibility with the old version would be have a new class implementing the support for 0.28 and use it as the default implementation. Not sure it's worth it.

**Comment by phue** [comment]
Atleast the documentation states that Charliecloud support is experimental, so that can serve as an excuse for a breaking change :sweat_smile:

**Comment by phue** [comment]
I have added the information about Charliecloud version requirements for different Nextflow releases :+1:

**Review by pditommaso — APPROVED** [review]
Nice

**Pull request merged**
