### PR TITLE
Change access rights of submitRateLimit

### PR DESCRIPTION
**Pull request by Lehmann-Fabian**
In my CWS plugin, I overwrite the `submitPendingTasks` method. However, the submitRateLimit is not accessible. Please merge this to give me access.

### CODE REVIEW

**Comment by pditommaso** [comment]
Instead of submitting individual PR, would not it be better to create a dedicated PR for there where collecting all required changes?

**Comment by pditommaso** [comment]
In general, I agree, however, considering this effort can take a while several iterations, maybe it's better you prototype into a separate Nextflow branch, so you can prototype it faster and we can discuss how improve it

**Comment by Lehmann-Fabian** [comment]
So, for now, should I join all 4 PRs in a single one, or do we continue as it is?

**Comment by pditommaso** [comment]
Let's move to a uber PR related to CWS effort

**Pull request closed without merging**
