### PR TITLE
Headless release (onescript)

### PR DESCRIPTION
**Pull request by tom-seqera**
An alternative approach to a headless release process (https://github.com/nextflow-io/nextflow/pull/5554) which puts all the whole process into a single script, run from within the `build.yml` Github Action

### CODE REVIEW

**Comment by bentsherman** [comment]
This one was the least preferred in our weekly meeting

**Comment by pditommaso** [comment]
Agree

**Comment by bentsherman** [comment]
I said this one was the *least* preferred 😅

**Comment by pditommaso** [comment]
LOL, i've skipped "least". My rationale is that's it's better decoupled from GH.

**Comment by bentsherman** [comment]
well, as long as you are happy with the changes, doesn't matter to me which one we use

**Comment by tom-seqera** [comment]
The main weakness of this approach is that it's entirely embedded in the `build.yml` Github workflow. 

This is fine for the moment. In the future though - as we work to automate more of the remaining manual steps - we'll likely want to pull it out into its own Github workflow.

**Pull request merged**
