### PR TITLE
Support container directive for condor executor

### PR DESCRIPTION
**Pull request by bentsherman**
Part of #3705 

cc @JosephLalli @Thom38 for testing

```bash
# build
git clone -b 3705-condor-docker-support git@github.com:nextflow-io/nextflow.git
cd nextflow
make compile

# test
../launch.sh run main.nf ...
```

### CODE REVIEW

**Comment by JosephLalli** [comment]
Hi there,
Just wanted to say that I'm very excited about this work, and when I have time to test it I will. I'm still very interested in using nextflow on HTCondor platforms!

-Joe

**Comment by JosephLalli** [comment]
Hi @bentsherman, quick update. I had some free time open up and began testing this update. I've been having trouble getting Nextflow to submit jobs into the docker universe. 

What are the conditions that trigger the "isContainerEnabled" attribute of a task? 

Right now I have docker.enabled = True and a container specified in the process main.nf file, but that is not causing Nextflow to produce a condor configuration file with a "universe = docker" line.

**Comment by bentsherman** [comment]
That's strange, because setting `docker.enabled = true` and `process.container = '...'` should be enough to add the container settings to the job script. Can you share your exact config and the process under test?

**Comment by JosephLalli** [comment]
Well, I'm running the nextflow test pipeline hello, edited to ensure there's a container.

Config file:
```
process {
    executor = 'condor'
    memory = '2 GB'
    cpus = 1
}

docker.enable=true
```

Workflow file:
```
#!/usr/bin/env nextflow
nextflow.enable.dsl=2


process sayHello {
  input:
    val x
  output:
    stdout
  script:
    """
    echo '$x world!'
    """
}

workflow {
  Channel.of('Bonjour', 'Ciao', 'Hello', 'Hola') | sayHello | view
}
```

Hello's nextflow.config:
```
process.container = 'quay.io/nextflow/bash'
```

Command used to run pipeline:
```
nextflow run hello -config test.config
```

condor submit file generated:
```
universe = vanilla
executable = .command.run
log = .command.log
getenv = true
request_memory = 2 GB
queue
```

Finally, I am running nextflow inside a docker container running on an HTCondor submit server. Most of the container deals with neatly configuring HTCondor to allow for the container user to query the HTCondor scheduler and submit jobs to the queue. Once HTCondor installation and configuration is done, the portion of the Dockerfile used to install Nextflow (which was mostly copied from Nextflow's docker container):

```
#####################################################################
# Install nextflow
ARG TARGETPLATFORM=linux/amd64

# copy docker client
COPY dist/${TARGETPLATFORM}/docker /usr/local/bin/docker

# download nextflow
WORKDIR /usr/local
RUN git clone -b 3705-condor-docker-support https://github.com/nextflow-io/nextflow

RUN cd nextflow && make compile

# download runtime
RUN nextflow/nextflow info

COPY entry.sh /usr/local/bin/entry.sh
RUN cp nextflow/nextflow /usr/local/bin/nextflow

RUN chmod 755 /usr/local/bin/nextflow 
RUN chmod 755 /usr/local/bin/entry.sh 
ENV NXF_OPTS="-Xms500M -Xmx2G" 


ENTRYPOINT ["/usr/local/bin/entry.sh"]
```

And the entry bash script, which obtains the HTCondor token used to submit jobs (again, adapted from the dockerized nextflow entry script):
```
# enable debugging
[[ "$NXF_DEBUG_ENTRY" ]] && set -x

# wrap cli args with single quote to avoid wildcard expansion
cli=''; for x in "$@"; do cli+="'$x' "; done


if [[ ! "$CONDOR_TOKEN" ]]; then
    if [[ -s "secrets.token" ]]; then
        CONDOR_TOKEN=secrets.token
    else
        echo "WARNING: HTCondor authentication token not detecting in present working directory. HTCondor execution will not function appropriately."
    fi
fi

mkdir -p $HOME/.condor/tokens.d
if [[ -s "$CONDOR_TOKEN" ]]; then
    cp $CONDOR_TOKEN /etc/condor/tokens.d/secrets.token
fi
if [[ -d /local_config ]]; then
    cp -af /local_config/. /etc/condor/ 2> /dev/null
fi

echo 'SEC_TOKEN_DIRECTORY = /etc/condor/tokens.d/' >> /etc/condor/condor_config

exec bash -c "$cli"
```

I'm sorry there's so much here! I know that's hardly a minimal bug report case, but I've been given instructions to only run Nextflow on a docker container on a submit server.

The container itself can be pulled from jlalli/nextflow-condor:0.2 , but without a working test server it will be difficult to do much with the container.

Finally, if you want to email me, I might be able to arrange a meeting with a member of the Condor team to discuss getting a test environment set up for you. While I'm not authorized to provide anything other that my time and (limited) knowledge, I know that there is a push to get better Nextflow support on HTCondor systems. Assistance with setting up a test environment for your team seems like a reasonable way to achieve that goal. My email is lalli at wisc.edu.

**Comment by JosephLalli** [comment]
Unrelated to the docker universe issue, my testing has uncovered a problem with how Nextflow queries the queue to monitor job progress. Parsing "condor_q" output every five seconds is an unreliable method of monitoring job progress, as completed jobs often fall out of the queue and no longer appear in condor_q's output.

Brian Bockelman, a Condor developer at the Morgridge Institute for Research at UW, suggested condor_history would be a better choice to monitor job progress. Additionally, there are [python bindings](https://htcondor.readthedocs.io/en/latest/apis/python-bindings/tutorials/Scalable-Job-Tracking.html) to allow for job tracking via event-based job logs, which are (per Brian) more scalable and created for tools such as Nextflow to monitor job progress. However, I don't know if a python API is of much use for Nextflow.

**Comment by bentsherman** [comment]
I think your Nextflow docker image is not using the custom Nextflow build. You run `make compile`, but in that case you must use `launch.sh` to run Nextflow, it doesn't install Nextflow to your system. To use the `nextflow` command, you would have to run `make install`.

To verify, run `nextflow info` and check the build number. It should match `APP_BUILDNUM` in `Const.groovy` in your local clone.

As for the status polling, if you can figure out a better command to fetch the queue status, you should be able to update `queueStatusCommand()` and `parseQueueStatus()` accordingly.

**Comment by JosephLalli** [comment]
Hi @bentsherman,

That was my first thought as well, but the build number reported matches the build number of what I am cloning from github (5864).

```
[root@6786d7a91d89 nextflow]# ./nextflow info
  Version: 23.06.0-edge build 5864
  Created: 14-06-2023 21:02 UTC
  System: Linux 3.10.0-1160.62.1.el7.x86_64
  Runtime: Groovy 3.0.17 on OpenJDK 64-Bit Server VM 17.0.8+7-LTS
  Encoding: UTF-8 (UTF-8)
```

Just in case, I changed make compile to make install in the docker file, and changed the run command to directly point to the location of the cloned nextflow file:

```
/usr/local/nextflow/nextflow run hello -config test.config
```

I see the same issue, and the same build number.

**Comment by bentsherman** [comment]
It should actually be one more than the build number from github, because the build process increments this number in your local repo. So if github says 5864 then your build should be 5865.

**Comment by JosephLalli** [comment]
OK, it turns out that following the 'install from source' instructions on the README page is helpful if you're trying to install from source.

The correct commands are make compile, _**make pack**_, make install. Running these three commands has ticked the build count to 5865, and the "created" date is finally today's date.

I'll test the build tomorrow. Thanks for your patience/help.

**Comment by pditommaso** [comment]
the suggested wortflow is `make compile` and then `./launch.sh` in place of the usual `nextflow` command

**Comment by JosephLalli** [comment]
@bentsherman Update - I am now running the correct Nextflow instance. Jobs are successfully submitted to Nextflow. However, nextflow does not detect when jobs are completed. The hello pipeline still runs hours after the job has successfully returned "hello". I suspect this is because completed jobs fall out of the queue and are no longer present in the output of "condor_q". Condor_history is a command that will return the status of all jobs submitted to the scheduler, but that is an overwhelming amount to parse

Condor recommends users track job status by polling individual job logs. ```condor_history --userlog $workdir/.command.log``` quickly parses the logfile and returns job progress in a format similar to condor_q. As an added benefit, condor_history --userlog does not interact with the scheduler, which is often run on the slowest machine in a cluster. However, I don't see an example of Nextflow monitoring job progress by polling individual jobs.

condor_history $user would return all jobs submitted by the user, but that would be across pipeline runs. I don't know if/how  Nextflow handles parsing that.

I am working with the Condor team to see if it is possible to have a job write to two log files - one for the job, and one for the run. condor_history --userlog is capable of parsing multiple jobs writing to the same log file. In the meantime, you all have more experience than I do with the best way to handle this sort of thing. What solutions do you recommend looking into?

**Comment by pditommaso** [comment]
> condor_history $user would return all jobs submitted by the user

Since when? is it possible to specify a time range?

**Comment by JosephLalli** [comment]
Yes, via the '''-since''' option.

**Comment by Thom38** [comment]
Hi,
Thank you for your support.
I was off it's why I was long to answer.
On my side this look like to be working fine, the .command.condor generated file is :
universe = docker
docker_image = myrepo/mydockerimage:latest
executable = .command.run
log = .command.log
getenv = true
request_cpus = 4
machine_count = 1
request_memory = 20 GB
queue

I have the good universe, the node is starting the job with the good docker image.
Just I think some issue with some path and file location to resolve but so far it looks good.
Thank you !

**Comment by JosephLalli** [comment]
> Hi, Thank you for your support. I was off it's why I was long to answer. On my side this look like to be working fine, the .command.condor generated file is : universe = docker docker_image = myrepo/mydockerimage:latest executable = .command.run log = .command.log getenv = true request_cpus = 4 machine_count = 1 request_memory = 20 GB queue
> 
> I have the good universe, the node is starting the job with the good docker image. Just I think some issue with some path and file location to resolve but so far it looks good. Thank you !

@Thom38, have you encountered the issue I saw regarding nextflow not detecting when jobs complete? If not, then maybe I've made a mountain out of my own piles of errors!

**Comment by Thom38** [comment]
> > Hi, Thank you for your support. I was off it's why I was long to answer. On my side this look like to be working fine, the .command.condor generated file is : universe = docker docker_image = myrepo/mydockerimage:latest executable = .command.run log = .command.log getenv = true request_cpus = 4 machine_count = 1 request_memory = 20 GB queue
> > I have the good universe, the node is starting the job with the good docker image. Just I think some issue with some path and file location to resolve but so far it looks good. Thank you !
> 
> @Thom38, have you encountered the issue I saw regarding nextflow not detecting when jobs complete? If not, then maybe I've made a mountain out of my own piles of errors!

Yes you're right, nextflow is not detecting the end of the job.

**Comment by Thom38** [comment]
The condor submission look good but job stuck with an error, and I can't see the error.
This is what I have in my Nextflow logs : 
```

Aug-09 14:42:57.195 [main] DEBUG nextflow.Session - Session await
Aug-09 14:42:57.414 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [CONDOR] submitted process sayHello (1) > jobId: 8828.0; workDir: /home/thom38/nextflow/work/fa/3b00df47e5bc0b8d43a2d8f6b2b726
Aug-09 14:42:57.415 [Task submitter] INFO  nextflow.Session - [fa/3b00df] Submitted process > sayHello (1)
Aug-09 14:42:57.465 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [CONDOR] submitted process sayHello (4) > jobId: 8829.0; workDir: /home/thom38/nextflow/work/5a/afa6724f53a1f302832a8e261dd023
Aug-09 14:42:57.466 [Task submitter] INFO  nextflow.Session - [5a/afa672] Submitted process > sayHello (4)
Aug-09 14:42:57.504 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [CONDOR] submitted process sayHello (2) > jobId: 8830.0; workDir: /home/thom38/nextflow/work/63/50e271f53a70b8a1bd81a46f2cc100
Aug-09 14:42:57.504 [Task submitter] INFO  nextflow.Session - [63/50e271] Submitted process > sayHello (2)
Aug-09 14:42:57.554 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [CONDOR] submitted process sayHello (3) > jobId: 8831.0; workDir: /home/thom38/nextflow/work/b4/5fb2a829220ed95b282bd2f5a6d840
Aug-09 14:42:57.554 [Task submitter] INFO  nextflow.Session - [b4/5fb2a8] Submitted process > sayHello (3)
Aug-09 14:48:02.147 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor condor > tasks to be completed: 4 -- submitted tasks are shown below
~> TaskHandler[jobId: 8828.0; id: 1; name: sayHello (1); status: SUBMITTED; exit: -; error: -; workDir: /home/thom38/nextflow/work/fa/3b00df47e5bc0b8d43a2d8f6b2b726 started: -; exited: -;
 ]
~> TaskHandler[jobId: 8829.0; id: 4; name: sayHello (4); status: SUBMITTED; exit: -; error: -; workDir: /home/thom38/nextflow/work/5a/afa6724f53a1f302832a8e261dd023 started: -; exited: -;
 ]
~> TaskHandler[jobId: 8830.0; id: 2; name: sayHello (2); status: SUBMITTED; exit: -; error: -; workDir: /home/thom38/nextflow/work/63/50e271f53a70b8a1bd81a46f2cc100 started: -; exited: -;
 ]
~> TaskHandler[jobId: 8831.0; id: 3; name: sayHello (3); status: SUBMITTED; exit: -; error: -; workDir: /home/thom38/nextflow/work/b4/5fb2a829220ed95b282bd2f5a6d840 started: -; exited: -;
```

And the nextflow job stuck in this state : 

```
N E X T F L O W  ~  version 23.06.0-edge
Launching `main.nf` [goofy_pasteur] DSL2 - revision: bfc4b06e27
executor >  condor (4)
[4f/574324] process > sayHello (3) [  0%] 0 of 4
```

**Comment by bentsherman** [comment]
Can you try updating the `queueStatusCommand()` method in `CondorExecutor` with a different status command like `condor_history`? We have made a few suggestions here.

Still, I'm wondering if `condor_q` has an option to show/hide completed jobs. It has a "Completed" status, so it should be able to show them right?

**Comment by Thom38** [comment]
We can use condor_history to show the ExitStatus but I don't know how to use that with Nextflow.

> condor_history USERNAME -af clusterId ExitStatus
500886 0
500886 0
500886 0
500886 0
500886 0
500886 0
500886 0
500886 0
500886 0
500886 0

**Comment by bentsherman** [comment]
Okay I incorporated your example command into the condor executor. It will fetch the username from `$USER` environment variable. I use JobStatus as defined here: https://htcondor.readthedocs.io/en/latest/classad-attributes/job-classad-attributes.html#JobStatus

Is that the correct attribute to use?

**Comment by pditommaso** [comment]
This PR has stalled. I'm closing it, feel free to re-open if there's any interest moving this feature forward

**Pull request closed without merging**
