### PR TITLE
[Bugfix] problem with names containing spaces

### PR DESCRIPTION
**Pull request by Lehmann-Fabian**
Signed-off-by: Lehmann-Fabian <fabian.lehmann@informatik.hu-berlin.de>

### CODE REVIEW

**Comment by bentsherman** [comment]
Can you provide a test case that fails before your changes and succeeds after your changes? Some of these bash variables don't need to be quoted because they are escaped by Nextflow before populating the bash template.

**Comment by pditommaso** [comment]
I'm unable to replicate this problem. I'm using this test script 

```
workflow {
  foo | view{ it.text }
}

process foo {
    scratch true
    debug true
    output:
    path "*/*.txt"
    """
    mkdir "a b"
    echo "Hello world" > "a b/hello.txt"
    """
}
```

It looks OK. This is how it gets executed: 

```
++ eval 'ls -1d */*.txt'
+++ ls -1d 'a b/hello.txt'
++ sort
++ uniq
+ for name in '$(eval "ls -1d */*.txt" | sort | uniq)'
+ nxf_fs_copy 'a b/hello.txt' /Users/pditommaso/Projects/nextflow/work/a0/5f78e8d35d2c165fc275ff9178991a
+ local 'source=a b/hello.txt'
+ local target=/Users/pditommaso/Projects/nextflow/work/a0/5f78e8d35d2c165fc275ff9178991a
++ dirname 'a b/hello.txt'
+ local 'basedir=a b'
+ mkdir -p '/Users/pditommaso/Projects/nextflow/work/a0/5f78e8d35d2c165fc275ff9178991a/a b'
+ cp -fRL 'a b/hello.txt' '/Users/pditommaso/Projects/nextflow/work/a0/5f78e8d35d2c165fc275ff9178991a/a b'
+ unset IFS
+ on_exit
+ exit_status=0
+ printf 0
```

**Comment by Lehmann-Fabian** [comment]
It looks like you tried `copy` as stage mode. Copy works, but `move` does not: `-process.stageOutMode move
`

**Comment by pditommaso** [comment]
I've tried both 

```
++ eval 'ls -1d */*.txt'
++ sort
+++ ls -1d 'a b/hello.txt'
++ uniq
+ for name in '$(eval "ls -1d */*.txt" | sort | uniq)'
+ nxf_fs_move 'a b/hello.txt' /Users/pditommaso/Projects/nextflow/work/f3/75d58c66ce83d1686a443ef174ef90
+ local 'source=a b/hello.txt'
+ local target=/Users/pditommaso/Projects/nextflow/work/f3/75d58c66ce83d1686a443ef174ef90
++ dirname 'a b/hello.txt'
+ local 'basedir=a b'
+ mkdir -p '/Users/pditommaso/Projects/nextflow/work/f3/75d58c66ce83d1686a443ef174ef90/a b'
+ mv -f 'a b/hello.txt' '/Users/pditommaso/Projects/nextflow/work/f3/75d58c66ce83d1686a443ef174ef90/a b'
+ unset IFS
+ on_exit
+ exit_status=0
+
```

**Comment by pditommaso** [comment]
Closing this. Feel free to re-open if you find more evidence

**Comment by Lehmann-Fabian** [comment]
I tested it again with your script and the latest Nextflow Version:
`nextflow run test.nf -with-docker nfcore/chipseq:1.2.2  -process.stageOutMode move`
And got:
```
N E X T F L O W  ~  version 22.10.3
Launching `test2.nf` [focused_mahavira] DSL2 - revision: 149f37bde9
executor >  local (1)
[68/21a26b] process > foo [100%] 1 of 1, failed: 1 ✘
Error executing process > 'foo'

Caused by:
  Missing output file(s) `*/*.txt` expected by process `foo`

Command executed:

  mkdir "a b"
  echo "Hello world" > "a b/hello.txt"

Command exit status:
  0

Command output:
  (empty)

Work dir:
  /tmp/work/68/21a26bb92879b6f293bb52165fc978

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

Did you test it with the `nfcore/chipseq:1.2.2` container?

**Comment by pditommaso** [comment]
No didn't, but the problem should be irrespective of the container usage

**Comment by Lehmann-Fabian** [comment]
I can only reproduce this error with some containers, e.g., the `nfcore/chipseq:1.2.2` one.
So it has something to do with the installed bash/GNU core utils.
Adding the quotes, however, makes it also work with this container.

**Pull request closed without merging**
