### PR TITLE
add retries to container env vars on batch

### PR DESCRIPTION
**Pull request by jchorl**
So the first command that a batch container exec's is of the shape:
`aws --region <region> s3 cp --only-show-errors`

By this point, no bash scripts have executed. So the exported aws retry env vars haven't hit yet. When running a bunch of batch jobs through a single instance, it's possible to overwhelm the metadata endpoint or s3 rate limits. This makes achieving throughput difficult.

This PR adds explicit env vars to the container to achieve retries even on the initial s3 pull.

I wrote a test, but `gradle test` wasn't passing for me locally (408 failed - something must be wrong). If you point me in the right direction, I can run only the single test I modified to see if its passing. Or, feel free to check out locally and fix it up.

Thanks!

### CODE REVIEW

**Review by pditommaso — CHANGES_REQUESTED** [review]
This is a great catch! well done. I've attached a patch that should fix the problem with the the failing test (ignore the changes in the `Consts.groovy` file please) 

[patch.txt](https://github.com/nextflow-io/nextflow/files/7523500/patch.txt)

**Comment by jchorl** [comment]
Good catches/suggestions, and thanks for the help with the test. Updated

**Comment by pditommaso** [comment]
Thanks, however there are still a few tests to fix 

```

AwsBatchTaskHandlerTest > should set accelerator FAILED
    org.spockframework.mock.TooManyInvocationsError at AwsBatchTaskHandlerTest.groovy:133

AwsBatchTaskHandlerTest > should create an aws submit request with a timeout FAILED
    org.spockframework.mock.TooManyInvocationsError at AwsBatchTaskHandlerTest.groovy:155

AwsBatchTaskHandlerTest > should create an aws submit request with retry FAILED
    org.spockframework.mock.TooManyInvocationsError at AwsBatchTaskHandlerTest.groovy:218
```

**Comment by pditommaso** [comment]
Ok, I went ahead and merged this manually, see 57e6cf1f2. Thanks a lot for spotting this problem and submitting this PR!

**Comment by jchorl** [comment]
@pditommaso thank you so much for driving this across the finish line. Much appreciated! :heart_eyes:

**Comment by pditommaso** [comment]
You are welcome 👍

**Pull request closed without merging**
