### PR TITLE
Adjusted Syntax for newer versions of PBS Pro Scheduler

### PR DESCRIPTION
**Pull request by lorenzgerber**
The current implementation of PBS Pro / Torque does not work on newer [PBS Pro](https://github.com/PBSPro/pbspro) installations  (tested with 14.2.4 on [NSCC](https://www.nscc.sg/) and a recent build 19.0.0 ) Two issues needed to be addressed:

- the resource request syntax has changed
- the `-1` flag for `qstat -f` does not exist anymore 

Here, `PbsExecutor` was subclassed with `PbsProExecutor` to amend the above mentioned issues. The new executor also had to be registered in `ProcessFactory`.

### CODE REVIEW

**Comment by lorenzgerber** [comment]
@pditommaso added license info and unit tests

**Comment by masonlr** [comment]
Thanks @lorenzgerber for the contribution. I just built and tested on PBS Pro 18.2.2.

**Comment by pditommaso** [comment]
I'm wondering if when no cpus are specified the following syntax is correct 

```
#PBS -l select=mem=1mb
```

**Comment by pditommaso** [comment]
@masonlr could you also copy & paste a sample output of the command `qstat -f | egrep '(Job Id:|job_state =)'` here?

**Comment by masonlr** [comment]
```
$ qstat -f | egrep '(Job Id:|job_state =)'
Job Id: 2100713.cx1
    job_state = R
```

**Comment by pditommaso** [comment]
Thanks. It looks identical to the non-pro version. What about the `-1` flag ?

**Comment by masonlr** [comment]
```
$ qstat -f -1
qstat: conflicting options.
usage:
qstat [-f] [-J] [-p] [-t] [-x] [-E] [-F format] [-D delim] [ job_identifier... | destination... ]
qstat [-a|-i|-r|-H|-T] [-J] [-t] [-u user] [-n] [-s] [-G|-M] [-1] [-w]
	[ job_identifier... | destination... ]
qstat -Q [-f] [-F format] [-D delim] [ destination... ]
qstat -q [-G|-M] [ destination... ]
qstat -B [-f] [-F format] [-D delim] [ server_name... ]
qstat --version
```


From the `qstat` man page:

```
    -1        Reformats  qstat output to a single line.  Can be used only in conjunction
                 with the -n and/or -s options.
```

**Comment by pditommaso** [comment]
I see. It seems it has changed. Thanks for the prompt reply.

**Comment by masonlr** [comment]
Just mentioning that I'm seeing this warning with e53beb3:

```
WARN: [PBSPRO] failed to retrieve queue status -- See the log file for details
```

**Comment by pditommaso** [comment]
Can you check in the log fail? there should be a more detailed message and report here?

**Comment by lorenzgerber** [comment]
@pditommaso @masonlr I'm pretty sure this happens because `egrep` returns with exit status 1 when there is no more job in the queue (and hence no match). I'm looking into it. I think this even happens with the pbs executor.

**Comment by pditommaso** [comment]
Makes sense! I'm patching with a `qstat | egrep '(Job Id:|job_state =)' || true`. Does it sound good to you ?

**Comment by lorenzgerber** [comment]
@pditommaso According to [PBSRefGuide 18.2. ](https://www.pbsworks.com/pdfs/PBSRefGuide18.2.pdf) the state for completed jobs changed to `F` (in PBS Executor it's `C`). See table below.
screenshot from 2018-10-24 16-28-57

Could you include the following in the 'PBS pro Executor':
```
    static protected Map DECODE_STATUS = [
            'F': QueueStatus.DONE,
            'R': QueueStatus.RUNNING,
            'Q': QueueStatus.PENDING,
            'H': QueueStatus.HOLD,
            'S': QueueStatus.HOLD
    ]
```

**Comment by pditommaso** [comment]
See #908.

**Pull request merged**
