### PR TITLE
bugfix: Prevent double trigger CI build

### LINKED ISSUE #2650: Prevent double trigger CI build
The event of creating a pull-request from this same project (i.e. not a forked repository) results into triggering two separate GitHub Action builds, one for the branch push and the other for the PR, which is a bit annoying. 

I think this is caused by this configuration 

https://github.com/nextflow-io/nextflow/blob/master/.github/workflows/build.yml#L5-L12

Removing one of the two would result disable the CI build either for any PR or for any push to a branch. 

The ideal solution would be to trigger a build for PR submitted from external forks *AND* when pushing to a branch.

### PR DESCRIPTION
**Pull request by jorgeaguileraseqera**
resolve #2650

Signed-off-by: Jorge Aguilera <jorge.aguilera@seqera.io>

### CODE REVIEW

**Comment by pditommaso** [comment]
Is this still draft or it could be merged?

**Comment by jorgeaguileraseqera** [comment]
I think is completed
The main "problem" to fully validate is that we need some PR so maybe we can merge and check how it works with new PRs

**Comment by pditommaso** [comment]
This does not seem to solve. Still double triggering the CI build

**Comment by pditommaso** [comment]
This seems better [ec97af1](https://github.com/nextflow-io/nextflow/pull/2743/commits/ec97af1b304e7d8f3d2b0b5357b942877c34545c)

**Pull request merged**
