### PR TITLE
Avoid to read an included config file more than once

### PR DESCRIPTION
**Pull request by jordeu**
## Description

When using Tower (or trace enabled) Nextflow is reading the `includeConfig` file twice. 

First time, it is read as expected when building the config map here:
https://github.com/nextflow-io/nextflow/blob/787a1fd84aead0f285ab94ab8a328093cbe0ec84/modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy#L287

and the second time is read when building the resolved config string here:
https://github.com/nextflow-io/nextflow/blob/787a1fd84aead0f285ab94ab8a328093cbe0ec84/modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy#L306-L307

It is not possible to reuse the same config object when building the resolve configuration due to the use of the method `setShowClosures` on the second builder.
https://github.com/nextflow-io/nextflow/blob/21792bf727f668c50a6155153b208a0faae88d6c/modules/nextflow/src/main/groovy/nextflow/config/ConfigBuilder.groovy#L830-L835

This is a proposal to memoize the content of the included config file to avoid multiple reads.

### CODE REVIEW

**Comment by pditommaso** [comment]
Can I move this to "Ready for review" ?

**Comment by jordeu** [comment]
Ready @pditommaso

**Comment by pditommaso** [comment]
I cannot think any negative side effects, but I'm not understanding for what reason is invoked twice without the memorisation

**Comment by pditommaso** [comment]
Umm, but then the memoised should work within the config object instance, in the example you are reporting the should different instances. How could it work?

**Comment by pditommaso** [comment]
Got it 👍

**Review by pditommaso — APPROVED** [review]

**Pull request merged**
