### PR TITLE
Include manifest data in workflow metadata object

### PR DESCRIPTION
**Pull request by sven1103**
Addresses #840

### CODE REVIEW

**Comment by pditommaso** [comment]
The manifest object is modelled by [this](https://github.com/nextflow-io/nextflow/blob/7e1ace22f1092b446479d5b188f548cb95325386/src/main/groovy/nextflow/config/Manifest.groovy#L34) class.

**Comment by pditommaso** [comment]
Green! Please add come tests and the relative docs. Thanks!

**Comment by sven1103** [comment]
Sure, always!

**Comment by ewels** [comment]
Hi @pditommaso,

Did this make it into the 0.32.0 release? @crickbabs is still getting this error after upgrading to 0.32.0:

```
ERROR ~ No such variable: manifest
```

Phil

**Comment by pditommaso** [comment]
Yes, it's supposed to be `workflow.manifest` not just `manifest`

**Comment by ewels** [comment]
Thanks! 🎉

**Comment by ewels** [comment]
Ok, we got to the root of the problem. This PR makes `workflow.manifest` available in the scripts as advertised. However, I had wrongly assumed that `manifest` was an open scope like `params` where we could add any variables that we like (see `name`, `pipelineVersion`, `author` etc in https://github.com/nextflow-io/nextflow/issues/840#issue-351183181).

So we can now access `workflow.manifest.version` in scripts which is great, but we can't access `workflow.manifest.name` (or `workflow.manifest.pipelineVersion`).

My thoughts are that we should either make this flexible so that it can hold any variable names, or we should keep it locked down (preferably with the additional variables requested in the above issue) and throw an error if anything else is found. Currently you can define whatever you like there but not ever use it, which leads to confusing bugs: `ERROR ~ No such variable: pipelineVersion`

Any thoughts on this design decision @pditommaso?

Phil

**Comment by ewels** [comment]
https://github.com/nextflow-io/nextflow/issues/871

**Pull request merged**
