### PR TITLE
add codespell: config, workflow and have typos fixed

### PR DESCRIPTION
**Pull request by yarikoptic**
workflow would only detect when a new typo is introduced, it will not automagically inject its fix somehow.

more info on codespell: https://github.com/codespell-project/codespell

### CODE REVIEW

**Comment by yarikoptic** [comment]
I've fixed up for
```
/home/runner/work/nextflow/nextflow/modules/nextflow/src/test/groovy/nextflow/cli/CmdSecretTest.groovy: 63: Unexpected input: 't' @ line 63, column 41.
> Task :nextflow:compileTestGroovy FAILED
   hould validate #COMMAND doesn't accept #
                                 ^

1 error
```

**Comment by yarikoptic** [comment]
It is all green and ready for review!

**Comment by yarikoptic** [comment]
The goal is to fix and prevent common typos anywhere in the codebase.  `codespell` catches common typos and has proposed ways to fix them -- that is what I have done here. Added workflow would run `codespell` for any new PR, and error out if PR introduces a new typo, thus alerting author to fix it.

**Review by pditommaso — APPROVED** [review]
Ok, thanks a lot

**Pull request merged**
