### PR TITLE
bugfix: include revision in the Azure Repos provider if specified

### PR DESCRIPTION
**Pull request by jorgeaguileraseqera**
closes #2861 

Signed-off-by: Jorge Aguilera <jorge.aguilera@seqera.io>

### CODE REVIEW

**Comment by pditommaso** [comment]
it was fast! think we need to add an integration test to verify it works as expected

**Comment by jorgeaguileraseqera** [comment]
> it was fast! think we need to add an integration test to verify it works as expected

ah, ok. I see this test uses a NXF_AZURE_REPOS_TOKEN but not sure if it's injected in the github action

```
   @IgnoreIf({System.getenv('NXF_SMOKE')})
    @Requires({System.getenv('NXF_AZURE_REPOS_TOKEN')})
    def 'should fetch repo tags'() {
```

**Comment by pditommaso** [comment]
Yes, it is

**Comment by jorgeaguileraseqera** [comment]
Added 2 test to verify against a real Azure repo (one to test fake branch and another to check a file is retrieved)

**Comment by pditommaso** [comment]
Released along with version `22.05.0-edge`

**Pull request merged**
