### PR TITLE
Undeprecate countBy operator

### PR DESCRIPTION
**Pull request by bentsherman**
The countBy operator is deprecated for some reason, but I think it adds enough value that it's worth keeping.

With `reduce`:
```groovy
channel.of( 'x', 'y', 'x', 'x', 'z', 'y' )
    | reduce([:]) { counts, v ->
      counts[v] = (counts[v] ?: 0) + 1
      counts
    }
```

With `countBy`:
```groovy
channel.of( 'x', 'y', 'x', 'x', 'z', 'y' )
    | countBy
```

### CODE REVIEW

**Comment by bentsherman** [comment]
Also the docs for reduce were incorrect about the argument order of the reduce closure, so I fixed that.

**Comment by mribeirodantas** [comment]
👀

**Comment by pditommaso** [comment]
I don't there's a great use for `groupBy`. Above all, [this never worked in dsl2](https://github.com/nextflow-io/nextflow/blob/759d7b94addc2f4ff1154685eafe21d374def782/modules/nextflow/src/main/groovy/nextflow/extension/OpCall.groovy#L325-L328). Deprecated and undeprecation, can create even more confusion. 

I think it's better to keep in the current form. I've merged manually the docs change 👉 759d7b94.

**Comment by bentsherman** [comment]
> I don't there's a great use for `groupBy`.

Paolo, this PR is about `countBy`

**Pull request closed without merging**
