### PR TITLE
Document cleanup configuration variable

### PR DESCRIPTION
**Pull request by jfy133**
This documents the currently undocumented `cleanup` option that is avaliable in configuration files.

Based on the discussion on the nf-core slack originally [here](https://nfcore.slack.com/archives/CE56GDKN0/p1583244613045500) and more recently [here](https://nfcore.slack.com/archives/CE6P95170/p1622115069029300)

Note this is a draft as we are unsure if this still an incubating feature and also it is not a traditional 'scope'. However we were unsure where this would fit in the documentation - therefore feel free to move/update as necessary.

It would also potentially close [#452](https://github.com/nextflow-io/nextflow/issues/452)

### CODE REVIEW

**Comment by maxulysse** [comment]
You say `There are additional variables`, but you only list one.

**Comment by jfy133** [comment]
That is future proofing in case there are other mysterious things we don't know about yet :grimacing:

**Comment by mmatthews06** [comment]
@pditommaso , is still an officially supported feature, or experimental? And if the latter, is there any plan to make it fully supported?

Obvously #452 would be nice, too.

**Comment by pditommaso** [comment]
Apology to be silent on this. This was never documented because makes the pipeline not resumable. Could not be self-defeating?

**Comment by drpatelh** [comment]
I still think it would be useful. From what I gather the advantage of this option compared to `nextflow clean` is that it will be run automatically at the end of the pipeline without having to execute a separate command. As long as we are explicit in the documentation as to it's limitations it would be a nice, "official" addition. We have quite a few configs using it on [nf-core/configs](https://github.com/nf-core/configs/search?q=cleanup) now too :)

**Comment by jfy133** [comment]
Agreed, as long as it's explicit it's fine.

I can update the documentation accordingly if you wish

Certainly for use at my institute, once a pipeline is complete people rarely use the run again.

**Comment by pditommaso** [comment]
Ok, let's highlight better then. What about the following? 

```
================== ================
Name                Description
================== ================
cleanup             If ``true``, on a successful completion of a run all files in *work* directory are automatically deleted.
================== ================

.. warning:: 
    The use of the above ``cleanup`` option will prevent the use of the *resume* feature on subsequent executions of that pipeline run. 
    Also, be aware that deleting all scratch files can take a lot of time especially when using shared file system or remote cloud storage.

``` 


can you incorporate the change if it's fine?

**Comment by jfy133** [comment]
Fine with me! Updated!

**Review by pditommaso — APPROVED** [review]

**Pull request merged**
