### PR TITLE
Support pipe for `dump` operator

### PR DESCRIPTION
**Pull request by bentsherman**
Makes the `dump` operator behave like an actual operator (i.e. chainable) by moving it to `OperatorImpl`.

### CODE REVIEW

**Review by pditommaso — CHANGES_REQUESTED** [review]
Worth adding some unit tests

**Comment by bentsherman** [comment]
I added a unit test. Strangely, the unit test fails but it works when I run it as a script:
```console
$ cat dump.nf
Channel.of(1, 2, 3) | dump

$ ../launch.sh run dump.nf -dump-channels 
N E X T F L O W  ~  version 23.08.0-edge
Launching `dump.nf` [condescending_torricelli] DSL2 - revision: eac5d3d36c
[DUMP] 1
[DUMP] 2
[DUMP] 3
```

**Comment by pditommaso** [comment]
It's already possible to do 

```
channel.of(1,2,3)
  .dump()
  .map(it -> it*2)
  .view()
```

What you are tying to fix here?

**Comment by bentsherman** [comment]
To make the pipe syntax work:

```groovy
channel.of(1,2,3)
  | dump
  | map(it -> it*2)
  | view
```

**Comment by pditommaso** [comment]
Moving to draft since tests fails

**Comment by bentsherman** [comment]
Closing in favor of v2 operator library

**Pull request closed without merging**
