### PR TITLE
Stash support

### PR DESCRIPTION
**Pull request by biologghe**
Hi,
This is all brand new to me (even this very first pull request ;-)
Found this private scm support a really cool feature. But in house, we use stash, so that's the reason I gave it a try to add support for stash. I omitted the StashRepositoryProviderTest from the github repo because the server is not public and would always fail otherwise.
Cheers,
Marc

PS Since BOSC2004 Glasgow I have been using Chirs Mungall's skam (skolem assisted makefile) to build pipelines. Got intrigued by NextFlow at the BOSC2015 and finally got the time to play with it 2 weeks ago. NextFlow rocks :-)

### CODE REVIEW

**Comment by pditommaso** [comment]
Cool! But Stash at the end is a private Bitbucket installation, isn't it? I'm wondering it should be merged with `BitbucketRepositoryProvider`. What do you think ?

**Comment by biologghe** [comment]
I'll have a more carefull look. I remember that I tried by setting the platform to bitbucket but that did not work. Think the REST API is slightly different.
I also finally found out how to run tests with Gradle... I only did 'testClasses', should have been 'test'. I'll fix the failing code first. Ambarrassing to find out that this pull request would trigger the build servers. And miserably fail. Of course. Expected only message to you. Like I said: this is all brand new to me ;-)
Cheers

**Comment by pditommaso** [comment]
The CI is meant for that!

You are welcome.

Cheers, p

**Comment by pditommaso** [comment]
Hi, if you could add a test for the changes you have done to `GitUrl` and include a section in the doc for `Stash` at [this page](https://github.com/nextflow-io/nextflow/blob/master/docs/sharing.rst#gitlab-credentials) I would be happy to merge your pull request. 

Also you may take in consideration to include also `StashRepositoryProviderTest` script using a `@Requires` annotation in order to disable tests as [shown here](https://github.com/nextflow-io/nextflow/blob/0e68e2a4c81fa7a7d2a6398f2a5386b1501895a1/src/test/groovy/nextflow/scm/BitBucketRepositoryProviderTest.groovy#L31-L31).

**Comment by biologghe** [comment]
Hi Paolo, I'll close this pull request for now. As soon as I find the time to write the tests and so I'll perform a new one.
Thanks for your patience.
Cheers,
Marc

**Pull request closed without merging**
