### PR TITLE
Implementation AWS CodeCommit provider

### PR DESCRIPTION
**Pull request by pditommaso**
This tentative implementation for support for Git providers via Nextflow plugins system, plus the addition of a new provider for [AWS CodeCommit service](https://aws.amazon.com/codecommit/). 

The main change is the introduction of a new [RepositoryFactory](https://github.com/nextflow-io/nextflow/blob/a0d374624c099b1c08b57a54928773b357949c0b/modules/nextflow/src/main/groovy/nextflow/scm/RepositoryFactory.groovy#L41-L86) that creates [RepositoryProvider](https://github.com/nextflow-io/nextflow/blob/a0d374624c099b1c08b57a54928773b357949c0b/modules/nextflow/src/main/groovy/nextflow/scm/RepositoryProvider.groovy#L38-L38)s instances via the plugin system 

The support CodeCommit is implemented by [AwsCodeCommitRepositoryProvider](https://github.com/nextflow-io/nextflow/blob/a0d374624c099b1c08b57a54928773b357949c0b/plugins/nf-amazon/src/main/nextflow/cloud/aws/codecommit/AwsCodeCommitRepositoryProvider.groovy#L41-L41)

What's remaining to do, is to delegate to the plugin system the provider configuration that was hardcoded in the `ProviderConfig` class [here](https://github.com/nextflow-io/nextflow/blob/a0d374624c099b1c08b57a54928773b357949c0b/modules/nextflow/src/main/groovy/nextflow/scm/ProviderConfig.groovy#L56-L109) and [here](https://github.com/nextflow-io/nextflow/blob/a0d374624c099b1c08b57a54928773b357949c0b/modules/nextflow/src/main/groovy/nextflow/scm/ProviderConfig.groovy#L307-L323)

### CODE REVIEW

**Comment by jorgeaguileraseqera** [comment]
I've moved the Codecommit specific configuration to the plugin repo and now is loaded when the nf-amazon is loaded, plus a little refactor to facilitate if we can move other providers to specific plugins

**Comment by jorgeaguileraseqera** [comment]
I've needed to refactor some parts but now I'm able to run a project in codecommit from scratch 

```
nextflow run https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/nf-test -plugins nf-amazon@1.7.1 -r main
N E X T F L O W  ~  version 22.03.1-edge
Pulling repos/nf-test ...
WARN: Cannot read project manifest -- Cause: Could not find path nextflow.config (Service: AWSCodeCommit; Status Code: 400; Error Code: FileDoesNotExistException; Request ID: f0e18def-9632-43e7-9268-bf4d6245268b; Proxy: null)
 downloaded from https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/nf-test
Launching `https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/nf-test` [magical_mestorf] DSL1 - revision: aed0bc0bf8 [main]
WARN: The use of `echo` method has been deprecated
executor >  local (4)
[1b/6115b6] process > sayHello (4) [100%] 4 of 4 ✔
Bojour mundo!!

Hello mundo!!

Ciao mundo!!

Hola mundo!!
```

Also I've updated the nf-amazon plugin to 1.7.1 (patch) as it includes now some new artifacts, I'm not sure if it's better a patch or a revision

**Comment by jorgeaguileraseqera** [comment]
I've removed the need to specify the plugin via cli and now we detect which plugin is required for specific repos

In this way all these commands work out of the box:

`nextflow run https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/nf-test `

`nextflow pull https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/nf-test `

`nextflow clone https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/nf-test `

**Comment by jorgeaguileraseqera** [comment]
it seems we have some commit without a valid signature

**Comment by jorgeaguileraseqera** [comment]
just rebased this branch due to conflicts with master

**Comment by pditommaso** [comment]
I made some mess about this feature. I didn't realised my branch was not updated and I've implemented some other stuff diverging from this branch. I've pushed to [this branch ](https://github.com/nextflow-io/nextflow/commit/3b1569eb4dae672ceada4a7f3c2966d8142fd5aa)

**Comment by jorgeaguileraseqera** [comment]
so do I need to compare against this new branch and incorporate changes from it into this branch?

**Comment by pditommaso** [comment]
I've made the mess, I'll try to reconcile it, no worry

**Comment by pditommaso** [comment]
I've took some ideas from this PR but also tried to not change too much the core implementation. The new branch diverged too much, therefore just closing this in favour of #2930

**Pull request closed without merging**
