### PR TITLE
Kubernetes limits pod option

### PR DESCRIPTION
**Pull request by KevinSayers**
First shot at #997, I am guessing this is too simplistic though and would be better to make a class for `limits`?

### CODE REVIEW

**Comment by pditommaso** [comment]
Hi Kevin, thanks for this but I think it would be better to have a generic `gpus` directive ultimately working for all executor not just for K8s. 

Then, the limits is a bit more tricky. Also this ideally should be a general solution taking in consideration #773. Frankly I still have no idea for an optimal solution about the latter.

**Comment by KevinSayers** [comment]
I agree that a `gpus` directive would be the ultimate goal, but I still think `limits` could be useful as there are other `extended resources` too. For example Intel FPGA, NVIDIA/AMD/Intel GPU, HPC networking, and Google TPUs all could be specified with the proposed changes. It would also address the issue in #773 of partial CPU specifications as the CPU value is just a string.

**Comment by pditommaso** [comment]
Yes, but I would prefer a more general solution for res allocation and limits, not just fixing K8s. let me think a bit about that.

**Comment by bentsherman** [comment]
@KevinSayers @pditommaso is this PR ready enough for me to test it on my workflows? I agree with you that ultimately we want to have a nice `gpus` directive but right now I have no workaround for doing this on k8s. On my HPC cluster and my local machine I can get by. But it looks like this PR would give me just enough functionality to test GPU workflows on k8s.

**Comment by pditommaso** [comment]
Fair enough. I'm going to merge this manually for now as an experimental feature.

**Comment by pditommaso** [comment]
I've realised that this would conflict with the current [limits](https://github.com/nextflow-io/nextflow/blob/594da5e8cd2995a793ff8b59809b3bee8176c4b6/modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy#L309-L312) specification. 

I think I prefer to close this and work instead of the `gpu` directive #997. I'll try to implement something in a couple of days.

**Pull request closed without merging**
