### PR TITLE
First shot at Cytoscape.js DAG rendering

### PR DESCRIPTION
**Pull request by mes5k**
This change adds the ability to export a DAG as an html file where the DAG is rendered using Cytoscape.js and Dagre.  It uses a template html file and simply substitutes in the network data formatted as json that Cytoscape.js will understand.  

The only notable change is that the rendering of Dot and Cytoscape.js are separated into individual classes that are separate from the definition of the DAG, edges, and vertices.  I'd probably argue that the GraphRender class should probably move execution of the dot command to the DotRenderer class to tidy things up, but I haven't made that change.

### CODE REVIEW

**Comment by pditommaso** [comment]
Thats a great start. Thank you! 

I would suggest the following changes: 

1) Instead of using a static methods for the renderers they could be implemented by using a [strategy pattern](https://en.wikipedia.org/wiki/Strategy_pattern). In practice the renders should implement a common interface, then a render instance is provided to the `DAG` via the constructor. Eventually you can take in consideration to use [Groovy Traits](http://groovy-lang.org/objectorientation.html#_traits) instead an interface + concreate classes. 

2) When the user specifies `-with-dag <file>.json` it should produce only the JSON.

3) Some unit tests

**Comment by mes5k** [comment]
Thanks Paolo, I've pushed new changes that should address each of your points.  I'm not sure if the approach I've used for the strategy pattern will be to your liking, but it's simple and will be easy to add new file formats. The tests I've added are just for GraphRender, but in the process check the output of some of the text based outputs.

**Comment by mes5k** [comment]
Ok, added a Dagre/D3 option.  Instead of replacing Cytoscape, I gave D3 the ".htm" suffix instead of ".html".  Cytoscape is still available with .html.  Dumb, but it works.  There is no json option for Dagre as the graph is created directly with javascript.  It would be trivial to create a function that consumes the JSON output for Cytoscape and loads it into Dagre, but I'm going to leave that for someone else.  Likewise the styling, which is non-existent.  More D3 trickery will be needed to make the graph interactive.

**Comment by pditommaso** [comment]
Thanks for your PR.

**Pull request merged**
