### PR TITLE
Add docs for process.cleanup

### PR DESCRIPTION
**Pull request by abhi18av**
Following up from the discussion earlier today.

### CODE REVIEW

**Review by bentsherman — APPROVED** [review]

**Comment by abhi18av** [comment]
@pditommaso perhaps we can merge this in the docs?

**Comment by bentsherman** [comment]
@abhi18av Can you put this `cleanup` directive in alphabetical order of the directives list so that it is easier for people to find?

**Comment by abhi18av** [comment]
Good point @bentsherman, I've now fixed the ordering of `c*` directives.

**Comment by abhi18av** [comment]
@bentsherman , mind if I point this PR to your https://github.com/nextflow-io/nextflow/pull/2698 ?

**Comment by bentsherman** [comment]
I was just gonna wait for this PR to be merged first 😄

**Comment by abhi18av** [comment]
Aah, okay 😅 

Well, I don't have merge rights so pinging @pditommaso to do the honors.

**Comment by pditommaso** [comment]
Never wanted to document this, because the logic is a bit convoluted and it can create false expectations. Also, note it's enabled by default 

https://github.com/nextflow-io/nextflow/blob/6930408ba1dba6e70ddcf76fa713d2533a007af5/modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy#L445-L448

**Comment by abhi18av** [comment]
> Never wanted to document this, because the logic is a bit convoluted and it can create false expectations.

I kind of agree on this, the name `cleanup` is now at top level config as well as in the `process` config so it might be misleading.

In any case, if there's still interest in this PR then I'll test some assumptions to improve the docs on the SLURM cluster once we have it up and running internally.

Otherwise, please feel free to close this PR 👍

**Comment by pditommaso** [comment]
This feature never has never been considered satisfactory. Think it's better to keep undocumented.

**Pull request closed without merging**
