### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by bentsherman**
Another round of docs improvements:
- [x] Split executor docs into subpages
- [x] Combine additional cloud / k8s docs with executor docs
- [x] Review code blocks for consistency
- [x] Review tips, notes, warnings for consistency
- [x] Remove notes about version requirements for 0.x versions

### CODE REVIEW

**Comment by bentsherman** [comment]
As before, this PR contains lots of general language and formatting improvements, and I tested my changes locally as I went, to make sure I didn't break anything.

**Comment by abhi18av** [comment]
@bentsherman , heads up for the merge-conflict.

**Comment by abhi18av** [comment]
Note for deployment: This PR moved some files within a new scope called `executor` (inside a folder of the same name) - would this cause breakage of current bookmarks or would the folder change not affect the URLs?

**Comment by bentsherman** [comment]
Yes. Here is a list of the url changes:
- `/docs/latest/executor.html` -> `/docs/latest/executor/index.html`
- `/docs/latest/awscloud.html` -> `/executor/aws.html`
- `/docs/latest/azurecloud.html` -> `/executor/azure.html`
- `/docs/latest/google.html` -> `/executor/google.html`
- `/docs/latest/ignite.html` -> `/executor/ignite.html`
- `/docs/latest/kubernetes.html` -> `/executor/kubernetes.html`

**Comment by pditommaso** [comment]
Thanks Ben. One thing, don't think makes much sense to move cloud pages under executors. Most of the times there are more info/setting other than executors. Second breaks exiting links which is a bit annoying

**Comment by bentsherman** [comment]
Good points, I realized them as well only as I was working on it. I have some ideas though, I will describe them in the new PR.

**Comment by bentsherman** [comment]
Separate PRs have been created, closing this one.

**Pull request closed without merging**
