### PR TITLE
Use Google Tag Manager.

### PR DESCRIPTION
**Pull request by ewels**
Documentation: Load Google Analytics via GTM instead of gtag.js

### CODE REVIEW

**Review by pditommaso — APPROVED** [review]

**Comment by ewels** [comment]
Ah, slight problem with https://github.com/nextflow-io/nextflow/pull/3840 - these two CI jobs are _required_ in the repo settings and now they don't run for PRs purely on docs. That means that GitHub just sits and waits for them forever, and merging is blocked:

image

**Comment by ewels** [comment]
I think that there are two ways around this:

* Remove the required status of these tests in the branch protection
* Rework the actions workflow so that it always runs, but that the `job` / `steps` are skipped if it's only the docs that were edited
    * GitHub treats skipped tests as passes for required CI jobs
    * A fair bit more code needed in the workflow YAML, not as clean

**Comment by pditommaso** [comment]
But still I can bypass the checks 😄

**Comment by pditommaso** [comment]
I've seen this also in other PRs e.g. [this](https://github.com/nextflow-io/nextflow/pull/3681), never fully understood why

**Comment by ewels** [comment]
Yeah, you can always admin-force merge.. But it's a bit messy 😉 

I foun another way to do it in these [GitHub docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks) - create a second workflow with the same name, that runs in the opposite scenario. Feels a bit hacky but might be the nicest solution. I'll create a PR..

**Comment by pditommaso** [comment]
you are right!

**Comment by ewels** [comment]
> I've seen this also in other PRs e.g. [this](https://github.com/nextflow-io/nextflow/pull/3681), never fully understood why

This one is something different I think. It looks like the CI build is triggering, but being skipped due to this config in the workflow:

```yaml
if: "github.event == 'push' || github.repository != github.event.pull_request.head.repo.full_name"
```

That's saying that pull-request CI builds should only run if the PR comes from a fork, not from the same repo. The PR you linked to came from a branch on the main repo, hence it was skipped.

Any idea why the workflow is configured this way?

**Comment by ewels** [comment]
> Any idea why the workflow is configured this way?

Ah maybe it's because the CI jobs are running on the `push` already, and so it's assumed that the same CI on the pull-request event is redundant? But the same could be said for forks 🤔 

If that's the motivation, I think it probably makes more sense to only run CI tests for `push` on the `master` branch. Then have `pull_request` CI jobs always run.

**Comment by ewels** [comment]
> Yes, to prevent double triggering the CI for internal PRs

But we're double triggering the CI for external PRs, I don't really see how the two are different..

Also, the two sets of CI tests are slightly different. The `pull_request` one runs the CI on the merged code, `push` only on the base code. So if the PR is coming from a fork that's a long way behind it is more representative of what will happen post-merge.

**Comment by ewels** [comment]
I made https://github.com/nextflow-io/nextflow/pull/3842 to explain what I mean..

**Pull request merged**
