### PR TITLE
Html trace

### PR DESCRIPTION
**Pull request by ewels**
* New plot for % of allocated time used, styled like the other plots
* Reordered table columns so that they're easier to read and compare
* More styling and tidying (eg. prettier navbar)

Ok, I think I'm happy with this now if you are @pditommaso!

### CODE REVIEW

**Comment by ewels** [comment]
[test_report.html.zip](https://github.com/nextflow-io/nextflow/files/1401656/test_report.html.zip)

**Comment by pditommaso** [comment]
Gorgeous!

**Comment by pditommaso** [comment]
Hi Phil, thanks again for your contribution. It's merged in the master branch. I've added also some documentation about the html report. 
https://github.com/nextflow-io/nextflow/commit/dc8bacf96a85c647c0117d3c8093b436bf4508de

You may want to contribute with some details/notes about the resource charts or whatever you may think it could be useful. Thanks a lot!

**Comment by ewels** [comment]
Great stuff, thanks @pditommaso ! Can't wait to add this as a default for all of our pipelines 🎉

**Comment by pditommaso** [comment]
Same here!

**Pull request merged**
