### PR TITLE
Accomodate the updated URL for ena API

### PR DESCRIPTION
**Pull request by abhi18av**
This PR addresses https://github.com/nextflow-io/nextflow/issues/2237 and implements the fix as per the PR on the `nf-core/fetchngs` workflow https://github.com/nf-core/fetchngs/pull/26/files

### CODE REVIEW

**Comment by pditommaso** [comment]
Was this tested with the reported example?

**Comment by drpatelh** [comment]
Yep. The minimal pipeline tests were failing with the old URL and are fixed now

Before:
https://github.com/nf-core/fetchngs/runs/3132001955

After:
https://github.com/nf-core/fetchngs/runs/3136148113

**Comment by abhi18av** [comment]
I've tested locally as well,

```
(base) Abhinavs-MacBook-Pro:_scratch eklavya$ ../launch.sh main.nf
N E X T F L O W  ~  version 21.06.0-edge
Launching `main.nf` [admiring_lovelace] - revision: 8892acb165
[ERR908507, [/vol1/fastq/ERR908/ERR908507/ERR908507_1.fastq.gz, /vol1/fastq/ERR908/ERR908507/ERR908507_2.fastq.gz]]
[ERR908506, [/vol1/fastq/ERR908/ERR908506/ERR908506_1.fastq.gz, /vol1/fastq/ERR908/ERR908506/ERR908506_2.fastq.gz]]
[ERR908505, [/vol1/fastq/ERR908/ERR908505/ERR908505_1.fastq.gz, /vol1/fastq/ERR908/ERR908505/ERR908505_2.fastq.gz]]

```

**Comment by pditommaso** [comment]
Still unable to test this since the associated endpoint is not reachable. I'm not even able to open thehttps://www.ncbi.nlm.nih.gov/sra web site. It's just my problem?

**Comment by abhi18av** [comment]
This is strange 🤔 

Anyways, I have checked just now the website, seems to be working 

image

**Comment by pditommaso** [comment]
Screenshot 2021-07-26 at 10 22 52

wow, then they banned me! 😆

**Comment by pditommaso** [comment]
Does this work for you? 

```
Channel
    .fromSRA('SRP043510')
    .view()
```

**Comment by abhi18av** [comment]
Yes, I tested that code and here's the response 


```
(base) Abhinavs-MacBook-Pro:nextflow eklavya$ ./launch.sh run _resources/test.nf
N E X T F L O W  ~  version 21.06.0-edge
Launching `_resources/test.nf` [voluminous_shaw] - revision: b5dcc52a61
[SRR1448795, /vol1/fastq/SRR144/005/SRR1448795/SRR1448795.fastq.gz]
[SRR1448794, /vol1/fastq/SRR144/004/SRR1448794/SRR1448794.fastq.gz]
[SRR1448793, /vol1/fastq/SRR144/003/SRR1448793/SRR1448793.fastq.gz]
[SRR1448792, /vol1/fastq/SRR144/002/SRR1448792/SRR1448792.fastq.gz]
[SRR1910483, /vol1/fastq/SRR191/003/SRR1910483/SRR1910483.fastq.gz]
[SRR1910482, /vol1/fastq/SRR191/002/SRR1910482/SRR1910482.fastq.gz]
[SRR1448791, [/vol1/fastq/SRR144/001/SRR1448791/SRR1448791_1.fastq.gz, /vol1/fastq/SRR144/001/SRR1448791/SRR1448791_2.fastq.gz]]
[SRR1448790, [/vol1/fastq/SRR144/000/SRR1448790/SRR1448790_1.fastq.gz, /vol1/fastq/SRR144/000/SRR1448790/SRR1448790_2.fastq.gz]]
[SRR1448789, /vol1/fastq/SRR144/009/SRR1448789/SRR1448789.fastq.gz]
[SRR1448788, /vol1/fastq/SRR144/008/SRR1448788/SRR1448788.fastq.gz]
[SRR1448787, /vol1/fastq/SRR144/007/SRR1448787/SRR1448787.fastq.gz]
[SRR1448786, /vol1/fastq/SRR144/006/SRR1448786/SRR1448786.fastq.gz]
[SRR1448785, /vol1/fastq/SRR144/005/SRR1448785/SRR1448785.fastq.gz]
[SRR1448784, /vol1/fastq/SRR144/004/SRR1448784/SRR1448784.fastq.gz]
[SRR1448783, /vol1/fastq/SRR144/003/SRR1448783/SRR1448783.fastq.gz]
[SRR1448782, /vol1/fastq/SRR144/002/SRR1448782/SRR1448782.fastq.gz]
[SRR1448781, /vol1/fastq/SRR144/001/SRR1448781/SRR1448781.fastq.gz]
[SRR1448780, /vol1/fastq/SRR144/000/SRR1448780/SRR1448780.fastq.gz]
[SRR1448779, /vol1/fastq/SRR144/009/SRR1448779/SRR1448779.fastq.gz]
[SRR1448778, /vol1/fastq/SRR144/008/SRR1448778/SRR1448778.fastq.gz]
[SRR1448777, /vol1/fastq/SRR144/007/SRR1448777/SRR1448777.fastq.gz]
[SRR1448776, /vol1/fastq/SRR144/006/SRR1448776/SRR1448776.fastq.gz]
[SRR1448775, /vol1/fastq/SRR144/005/SRR1448775/SRR1448775.fastq.gz]
[SRR1448774, /vol1/fastq/SRR144/004/SRR1448774/SRR1448774.fastq.gz]

```

**Comment by pditommaso** [comment]
crazy! I get `Host not found: eutils.ncbi.nlm.nih.gov` !

**Pull request merged**
