### PR TITLE
Add XPath default serializer

### PR DESCRIPTION
**Pull request by jorgee**
Add XPath default serializer

### CODE REVIEW

**Comment by pditommaso** [comment]
Any test unit tests that can replicate the issue and validate the patch?

**Comment by jorgee** [comment]
> Any test unit tests that can replicate the issue and validate the patch?

I have tried to reproduce the error. In fact, there is a unit test checking the XPath serialized and deserialized from a byte array that is the one used in the error in SortFileCollector.saveFile function. This test is not failing even without the no-arg constructor. 
I think, the issue is more related to how a particular XPath instance has been serialized that forces Kyro to use the no-args constructor when deserializing in this particular case and not in the others. Finding the particular case could take some time, and I think just adding the default constructor should solve the issue. I can continuing looking for this particular case, but I don't know if it is good to invest more time on it.

**Comment by pditommaso** [comment]
Curious to see the error trace. Is there a link to the issue?

**Comment by jorgee** [comment]
> Curious to see the error trace. Is there a link to the issue?

https://github.com/nextflow-io/nextflow/issues/5208

**Review by pditommaso — APPROVED** [review]

**Pull request merged**
