### PR TITLE
WIP: add charliecloud support

### LINKED ISSUE #1707: Using Charliecloud containers
Is it possible to use Charliecloud containers and if so is there any documentation on how to use it?

### PR DESCRIPTION
**Pull request by tbugfinder**
fixes #1707 
I'm opening this PR so that community is aware of WIP of Charliecloud
.

### CODE REVIEW

**Review by pditommaso — CHANGES_REQUESTED** [review]
Thanks a lot for this initiative. Please sign the commit to make the DCO bot happy. https://github.com/nextflow-io/nextflow/blob/master/CONTRIBUTING.md#contributing-code-changes

**Comment by phue** [comment]
Hi @tbugfinder,
I just came across this PR and I would also be very interested in charliecloud support in nextflow. Therefore I would be willing to help with this.

Can you elaborate on what is needed in this PR ?
I noticed that newer versions of charliecloud  also support pulling images from docker registries without root.
I understand that it would require methods for pulling (`ch-grow pull`) and running (`ch-run`) charliecloud containers.
What seems difficult, is that charliecloud does not seem to honor `ENV` layers in docker containers, but only inherits the hosts environment. This might be tricky if a container contains software in locations that are not set in the `$PATH`.

Thanks!

**Comment by pditommaso** [comment]
It should be implemented a *driver* for charliecloud similar to the ones for [Docker](https://github.com/nextflow-io/nextflow/blob/d0cc38de04f9f541e7d5aac12b7294cd62f1616d/modules/nextflow/src/main/groovy/nextflow/container/DockerBuilder.groovy#L26-L212) or [Singularity](https://github.com/nextflow-io/nextflow/blob/d0cc38de04f9f541e7d5aac12b7294cd62f1616d/modules/nextflow/src/main/groovy/nextflow/container/SingularityBuilder.groovy#L30-L160).

**Comment by tbugfinder** [comment]
I have to admit that I got distracted from spending more time on that and I also want to wait for a few changes in charliecloud. Thank you @phue for contributing to it.

**Comment by phue** [comment]
I think I made some progress, feel free to apply the commits listed above to this PR.
Alternatively, I can open a PR against https://github.com/tbugfinder/nextflow/tree/feature/charliecloud

**Comment by phue** [comment]
There is one issue though. Charliecloud does not set Environment variables (see [docs](https://hpc.github.io/charliecloud/command-usage.html#environment-variables)) that are defined in a Docker ENV layer.

My workaround in commits https://github.com/phue/nextflow/commit/9c640a1934c520ef1c16364f3299721559dbf1ee and https://github.com/phue/nextflow/commit/b316d09394363d90f3eba0db6e9c7f5ada5578ee assumes that the container has a key=value file at `/etc/environment` that contains these variables.
However this does not seem to be the case for all base docker images.

So I guess this could be solved by adding missing environment variables in either the `env` scope or via `charliecloud.envWhitelist` and pass them to the container upon execution.
This is not optimal though as it requires additional configuration.

Any other ideas how to handle this? @tbugfinder @pditommaso

**Comment by pditommaso** [comment]
My understanding is that chanrliecloud has a `--set-env` cli option. that should be enough to pass the env variables listed in the `envWhitelist`

**Comment by phue** [comment]
> My understanding is that charliecloud has a `--set-env` cli option. that should be enough to pass the env variables listed in the `envWhitelist`

Absolutely, that works. But it needs to be explicitly passed and won't work out-of-the-box.

Let's take nf-core containers for example. They usually have the dependencies in a conda environment at
`/opt/conda/envs/nf-core-{name}-{version}/bin` which is added as a Docker [ENV layer](https://github.com/nf-core/tools/blob/b67fd2a734a9e2bcf46b37f0f94b5545f7387298/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/Dockerfile#L10)
However Charliecloud ignores such ENV layers, so we would need to manually pass `envWhitelist="PATH=/opt/conda/envs/nf-core-{name}-{version}/bin:$PATH"`

I would like to do this automatically somehow, but I can't find a way to read this environment from of a Docker image.

**Comment by pditommaso** [comment]
Don't think it's correct because the `envWhitelist` is needed to propagate a host variable in the container. For what you are mentioning it should be enough to add the in the nextflow config  `PATH=/opt/conda/envs/nf-core-{name}-{version}/bin:$PATH` (having `{}` resolved ..).

**Comment by tbugfinder** [comment]
Thanks @phue for doing the hard work within #1809.
I'm closing this PR.

**Comment by phue** [comment]
> Thanks @phue for doing the hard work within #1809.
> I'm closing this PR.

Thank you for the initiative!

**Pull request closed without merging**
