### PR TITLE
Add mermaid DAG renderer

### LINKED ISSUE #2684: Output pipeline dag as a mermaid diagram
[Mermaid](https://github.com/mermaid-js/mermaid) is a Javascript library that creates diagrams from a markdown-like syntax. Github recently [add support](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/) for Mermaid rendering in markdown files, like this:

```mermaid
  graph TD;
      A-->B;
      A-->C;
      B-->D;
      C-->D;
```

I think Nextflow's dag renderer would benefit greatly from supporting the Mermaid format. Nextflow just needs to generate the mermaid description, and then either return that as a text file or call the [Mermaid CLI](https://github.com/mermaid-js/mermaid-cli) if it is available. Even with the text description, the user could just paste that into a markdown file in their github repo and it will work out of the box.

I will probably take a crack at this when I have some time. Only thing I'm wondering is whether it should be part of the main codebase or a plugin.

### PR DESCRIPTION
**Pull request by bentsherman**
Resolves #2684 

Here is the style convention so far:
- processes are rectangles
- channels are rectangles on the edges
- operators are rounded rectangles
- sources are circles

Probably should do something different for sources since the circle is pretty big. Also I think we can change the style, color, etc, however we want. The Mermaid docs are [here](https://mermaid-js.github.io/mermaid/#/flowchart).

Here is the cbcrg/shootstrap example from the docs:
```mermaid
flowchart TD
    p0((Channel.fromPath))
    p1([ifEmpty])
    p2[get_shuffle_replicates]
    p3[get_msa_replicates]
    p4[get_msa_trees]
    p5([collectFile])
    p6([first])
    p7[get_stable_msa_trees]
    p8(( ))
    p9[get_seqboot_replicates]
    p10[get_replicate_trees]
    p11([collectFile])
    p12([max])
    p13[get_shootstrap_tree]
    p14(( ))
    p0 --> p1
    p1 -->|file_names| p2
    p2 -->|shuffle_replicates| p3
    p3 -->|msa_replicates| p4
    p3 -->|msa_replicates2| p9
    p4 -->|msa_trees| p7
    p4 -->|msa_trees2| p5
    p5 --> p6
    p6 --> p7
    p7 -->|stable_trees| p8
    p7 -->|most_stable_tree| p12
    p9 -->|replicates| p10
    p10 -->|trees| p11
    p11 --> p13
    p12 --> p13
    p13 -->|shootstrap_tree| p14
```

### CODE REVIEW

**Comment by pditommaso** [comment]
This is nice, think we should add a mention in the docs and merge it!

**Review by pditommaso — APPROVED** [review]

**Comment by bentsherman** [comment]
Done.

I decided the giant circle is fine for now. I also decided it's better to not be opinionated about the style, so Nextflow just outputs the basic structure and users can style it however they want.

I just learned you can add hyperlinks to the DAG elements. So here's a crazy nf-core idea for @ewels and @drpatelh: generate a Mermaid diagram for each nf-core pipeline, where each operator / process links to the corresponding definition in Nextflow / nf-core docs 😄

**Comment by ewels** [comment]
Ooh nice! Is there an easy way to test this out? I'd love to see the resulting diagram for a big pipeline like nf-core/rnaseq or nf-core/sarek 😎

Love the idea of rendering these with links! Could we even do this within Nextflow if it's a GitHub repo? Link to a permalink highlighting the lines for that process / process etc?

**Comment by pditommaso** [comment]
> Ooh nice! Is there an easy way to test this out?

Sure, clone the repo, run `make compile` and run it using `./launch.sh` instead of `nextflow`

**Comment by bentsherman** [comment]
@ewels Adding the links is easy enough, the challenge is determining which link to use. For operators we could have a pre-baked mapping of links to Nextflow docs. For processes, we could try to find a matching nf-core module. I'm sure you could find the exact code block where a process is defined, it just sounds complicated at an initial glance.

Anyway, just an idea I wanted to throw out there. For now the basic mermaid rendering is done and can be merged.

**Comment by pditommaso** [comment]
Finally tests passed

**Pull request merged**
