### PR TITLE
Sanitize Grid Engine job name

### PR DESCRIPTION
**Pull request by amereddius**
This commit sanitizes custom job names and replaces any invalid characters so the jobs are not rejected by Grid Engine.

### CODE REVIEW

**Comment by bentsherman** [comment]
Looks good to me, only thing is you need to revert your changes to `Const.groovy`. The file is changed whenever you build Nextflow but it is only actually updated for new releases.

**Comment by amereddius** [comment]
@bentsherman please review as I updated this PR's scope to sanitize custom job names only for SGE executor. Thanks in advance!

**Review by bentsherman — APPROVED** [review]

**Comment by bentsherman** [comment]
Approved pending successful CI tests

**Review by pditommaso — COMMENTED** [review]
Hi, Is it not clear what this change does? It would be nice to add more extensive tests covering what this change address, using the following snippet as a template 

https://github.com/nextflow-io/nextflow/blob/6f087fecade0293978af096c465dce9ea1e75f84/modules/nextflow/src/test/groovy/nextflow/executor/AbstractGridExecutorTest.groovy#L29-L38

**Comment by pditommaso** [comment]
Closing for lack of response

**Pull request closed without merging**
