### PR TITLE
Kms support

### PR DESCRIPTION
**Pull request by mageshwarm**

### CODE REVIEW

**Review by pditommaso — CHANGES_REQUESTED** [review]
Thanks for this contribution. A few comments: 
1. Could you please provide some guidance for testing this feature?  
2. the sources were indented using tabs, this PR uses spaces adding a lot of noise. Any chance to use tabs instead of spaces 
3. To being able to merge it, the DCO bot must be green. This requires signing the commit as described at this link https://github.com/nextflow-io/nextflow/blob/master/CONTRIBUTING.md#contributing-code-changes

**Comment by mageshwarm** [comment]
@pditommaso . Please find my comments,

1. Could you please provide some guidance for testing this feature? 
`Please  add below in nextflow.config. Also if **storageEncryption** to "null or AES256", code will ignore **storageEncryptionKey** value, 
aws {
	region = 'eu-west-1'
	client { 
		storageEncryption = 'aws:kms'
		storageEncryptionKey = 'alias/dev-omics-s3-data-hosting-solution-kms-key'
	}
}`
2. the sources were indented using tabs, this PR uses spaces adding a lot of noise. Any chance to use tabs instead of spaces
`We tried it, if we change indent to tab, it creates lot of noises. In document also it mention to use space indent https://github.com/nextflow-io/nextflow/blob/master/CONTRIBUTING.md#ide-settings`

3. To being able to merge it, the DCO bot must be green **(DONE)**

**Comment by abhi18av** [comment]
Related https://github.com/nextflow-io/nextflow-s3fs/pull/26

**Comment by pditommaso** [comment]
Looking into this PR, I've realised that NF is yet fully compatible with S3 having KMS server encryption enabled. I made the following test: 

I did the following: 

1. create a KMS symmetric key with id: e97ecf28-951e-4700-bf22-1bd416ec519f

2. creating a bucket and configuring the defult encryption with the above key 

        » aws s3api get-bucket-encryption --bucket nf-kms-xyz
        {
            "ServerSideEncryptionConfiguration": {
                "Rules": [
                    {
                        "ApplyServerSideEncryptionByDefault": {
                            "SSEAlgorithm": "aws:kms",
                            "KMSMasterKeyID": "arn:aws:kms:eu-west-1:195996028523:key/e97ecf28-951e-4700-bf22-1bd416ec519f"
                        },
                        "BucketKeyEnabled": true
                    }
                ]
            }
        }

3. create a user and assign to it the following policy 


        {
            "Version": "2012-10-17",
            "Statement": {
                "Effect": "Allow",
                "Action": [
                    "kms:Decrypt",
                    "kms:GenerateDatakey"
                ],
                "Resource": [
                    "arn:aws:kms:eu-west-1:195996028523:key/e97ecf28-951e-4700-bf22-1bd416ec519f"
                ]
            }
        }
        
4. upload a file with the following snippet (with the user above) 


        process foo {
          publishDir "s3://nf-kms-xyz"
          output: 
            path 'bar.txt'
          """
          echo ciao > bar.txt
          """
        }
    
    
5. the file was created and it has used the correct KMS key 

        » aws s3api head-object --bucket nf-kms-xyz --key bar.txt

        {
            "AcceptRanges": "bytes",
            "LastModified": "2021-10-11T08:34:40+00:00",
            "ContentLength": 5,
            "ETag": "\"d4855ed687ac99f5507c81997e411d1a\"",
            "ContentType": "application/octet-stream",
            "ServerSideEncryption": "aws:kms",
            "Metadata": {},
            "SSEKMSKeyId": "arn:aws:kms:eu-west-1:195996028523:key/e97ecf28-951e-4700-bf22-1bd416ec519f",
            "BucketKeyEnabled": true
        }
        

Therefore I'm not sure what this PR is trying to achieve?

**Comment by pditommaso** [comment]
This has been merged manually c1e45aa9. Thanks for the contribution.

**Pull request closed without merging**
