### PR TITLE
Use rclone for azure blob I/O

### PR DESCRIPTION
**Pull request by abhi18av**
This PR implements the lessons from https://github.com/seqeralabs/azure-sandbox/blob/35fc3309249aef4f659b8e114be10a0e70ee4486/src/test/groovy/io/seqera/services/TaskServiceImplTest.groovy#L302

### CODE REVIEW

**Comment by abhi18av** [comment]
I've initiated work for adding tests for the `AzFileCopyStrategyTest` - any pointers would be helpful :)

**Comment by pditommaso** [comment]
Does this run?

**Comment by abhi18av** [comment]
Paolo, I'm not sure how to test the plugin beyond the unit tests like `AzFileCopyStrategyTest`.

- Do we just build a nextflow binary and run it with Azure credentials in the config?
- Do I need to select a special Gradle build for building with the plugins?
-

**Comment by pditommaso** [comment]
Running NF using the azure executor using the config I've shared on slack

**Comment by abhi18av** [comment]
Closing this PR as this has become obselete due to the design changes.

**Pull request closed without merging**
