### PR TITLE
Fix a few issues in BatchLogging.groovy

### PR DESCRIPTION
**Pull request by aaronegolden**
1. Adds the projectId to BatchLogging's LoggingOptions so the logs will be fetched from the correct project. Previously I got a lot of "that resource might not exist" responses from the log read requests. I'm not sure if there's something special about my environment that causes me to need the projectId in the options, but I think it couldn't hurt to have the projectId in general.

2. Removes the old paseOutput function, which relied on the STDERR and STDOUT prefixes in the payload of the log entries. Batch no longer adds those prefixes so that parsing doesn't work. Now we can distinguish stderr from stdout by looking at the logEntry's severity.

3. Catches any exception thrown by the log reading code. It could be a permissions issuee like I was seeing, or a thread pool issuee as in https://github.com/nextflow-io/nextflow/issues/3166. Either way, something going wrong while trying to read task logs should probably not stop the whole workflow.

With these changes, the nf-core/methylseq workflow can be run with the google-batch executor.

### CODE REVIEW

**Comment by pditommaso** [comment]
Thanks a lot for this, however, there are a couple of failing tests: 

[This one](https://github.com/nextflow-io/nextflow/blob/main/plugins/nf-google/src/test/nextflow/cloud/google/batch/logging/BatchLoggingTest.groovy#L97-L97) is reporting the following message 

```
Condition not satisfied:

stderr.contains('Oops something went wrong')
|      |
""     false

	at nextflow.cloud.google.batch.logging.BatchLoggingTest.should fetch logs(BatchLoggingTest.groovy:152)

```

[and this other](https://github.com/nextflow-io/nextflow/blob/main/plugins/nf-google/src/test/nextflow/cloud/google/batch/logging/BatchLoggingTest.groovy#L44-L44) fails with  

```
groovy.lang.MissingMethodException: No signature of method: nextflow.cloud.google.batch.logging.BatchLogging.parseOutput() is applicable for argument types: (String, StringBuilder, StringBuilder) values: [  Task action/STARTUP/0/0/group0/0, STDOUT:  No user sessions are running outdated binaries.
, ...]
	at nextflow.cloud.google.batch.logging.BatchLoggingTest.should parse stdout and stderr(BatchLoggingTest.groovy:55)

```

note that you can run the tests locally using this command 


```
 ./gradlew :plugins:nf-google:test
```

**Comment by aaronegolden** [comment]
Update, failing tests should be fixed now. I modified the "should parse stdout and stderr" test case to exercise the new severity based stdout vs. stderr logic. Also removed the Task ID prefixes from the test strings since Batch no longer includes those in the Cloud Logging entries it generates.

**Comment by pditommaso** [comment]
This looks awesome. Thanks, please sign your commit to make the DCO bot pass the test. See [here](https://github.com/nextflow-io/nextflow/blob/master/CONTRIBUTING.md#contributing-code-changes).

**Comment by aaronegolden** [comment]
> This looks awesome. Thanks, please sign your commit to make the DCO bot pass the test. See [here](https://github.com/nextflow-io/nextflow/blob/master/CONTRIBUTING.md#contributing-code-changes).

Done, thanks! I was confused and thought maybe a project owner was supposed to sign off and not me.

**Comment by pditommaso** [comment]
Great! all green. Thanks a lot of looking into this 👍

**Comment by pditommaso** [comment]
Made a minor change to report a failure fetching the logs as a warning. 👉 bdbcdde9

**Pull request merged**
