### PR TITLE
Add tip for error strategy directive

### PR DESCRIPTION
**Pull request by apeltzer**
As it was previously mentioned on Gitter and answered there...

### CODE REVIEW

**Comment by pditommaso** [comment]
1579 files changed? 😰

**Comment by apeltzer** [comment]
I think I updated my fork first and then added the docs here on top... that shouldn't be that much :-(

**Comment by apeltzer** [comment]
I fear the changes are coming in since the branch `cli-docs` wasn't updated for a long time with the changes from `master` ?

**Comment by pditommaso** [comment]
You should have created a new branch. Just copy the snippet below, I will merge it manually.

**Comment by apeltzer** [comment]
Which one? :-)

**Comment by pditommaso** [comment]
I mean the change you wanted to send via the PR

**Pull request closed without merging**
