### PR TITLE
Docu warning about files copied from scratch 

### PR DESCRIPTION
**Pull request by rsuchecki**
Lines 1968-1972, the rest is VS Code's doing

### CODE REVIEW

**Comment by pditommaso** [comment]
What about adding the following [here](file:///Users/pditommaso/Projects/nextflow/docs/_build/html/process.html#multiple-output-files): 

```
.. warning:: Although the input files matching a glob output declaration are not included in the
   resulting output channel, these files still may be transferred from the task scratch directory
   to the target task work directory. Therefore to avoid unnecessary file copies it's recommended
   to avoid the usage of loose wildcards when defining output files e.g. ``file '*'`` .
   Use instead a prefix or a postfix naming notation to restrict the set of matching files to
   only the expected ones e.g. ``file 'prefix_*.sorted.bam'``.
```

**Comment by rsuchecki** [comment]
I think you are right, it is better to focus on glob usage, here is your text with only cosmetic changes

```
.. warning:: Although the input files matching a glob output declaration are not included in the
   resulting output channel, these files may still be transferred from the task scratch directory
   to the target task work directory. Therefore, to avoid unnecessary file copies it is recommended
   to avoid the usage of loose wildcards when defining output files e.g. ``file '*'`` .
   Instead, use a prefix or a postfix naming notation to restrict the set of matching files to
   only the expected ones e.g. ``file 'prefix_*.sorted.bam'``.
```

This is better as a general advice, but there is still the special case where the user might want to pass one or more of the inputs into an output channel (glob or not), then such file will end-up as a copy  instead of a symlink in `task.workDir` when using scratch. Modified from our earlier examples:

```
Channel.from('Bonjour')
  .collectFile()
  .set { greetings }

process echo {
  input:
    file ('greeting.in')  from greetings

  output:
    set file('greeting.in'), file('greeting.out') into result
    //or file('greeting.*') into result

  script:
  """
  cat greeting.in > greeting.out
  """
}
```

Not sure if this warrants a separate warning or should something like this be added:

> In case an input file needs to be declared as one of the outputs of a process when using `scratch`, the unnecessary copying of the input files can be prevented by using `stageOutMode 'move'` with the default `stageInMode 'symlink'`.

**Comment by pditommaso** [comment]
Ok, thanks! Regarding the latter case it's really a corner case, I would consider more an advanced optimisation (also working only in some scenarios e.g. it won't work with Batch execution).

**Comment by rsuchecki** [comment]
Fair enough! Just out of curiosity, why would `mv` not work with Batch execution (by Batch do you mean e.g. SLURM?)

**Comment by pditommaso** [comment]
Both `stageInMode` and `stageOutMode` are ignored with AWS Batch and Google pipelines executors because they need to use aws cli / gsutil to move data from/to S3/GS object storage.

**Comment by pditommaso** [comment]
Merged manually. Thanks!

**Pull request closed without merging**
