### PR TITLE
[Plugin] nf-sraql for Google bigquery

### PR DESCRIPTION
**Pull request by abhi18av**
The PR addresses https://github.com/nextflow-io/nextflow/issues/1842 

The initial goal is to integrate Google BigQuery completely within the plugin and then later on expand to AWS Athena.

The design is heavily based on the design of `nf-sql`, though the mistakes are original 😉 

I'm managing the developement on my end via a project board on my fork https://github.com/abhi18av/nextflow/projects/2

### CODE REVIEW

**Comment by pditommaso** [comment]
This looks very promising. One thing, I know I've asked to create a PR for this, but thinking more about this it makes more sense to create an independent project. 

I'll setup a new project on nextflow-io org so you will be able to move it there, make sense to you?

**Comment by abhi18av** [comment]
Yup, this sounds good to me 👍 

Thinking a bit further along in future, we'll likely have many plugins (official + community) - do we want to host all of them on `nextflow-io` organization?

**Comment by abhi18av** [comment]
I'm not sure why the tests are failing on the CI, when I've tested each of the classes locally via IntelliJ native invocation, then all tests pass for `nf-sraql`.


Worth noting that I'm not able to test locally using `make smoke` as the process seems to get stuck at the k8s test

image

**Comment by abhi18av** [comment]
User experience test as of https://github.com/nextflow-io/nextflow/pull/2438/commits/68c7e70e59d1ccf281a247c86217fa8d3f60c7c8

```nextflow
nextflow.enable.dsl=2

def sraqlQuery = "SELECT *  FROM `nih-sra-datastore.sra.metadata` WHERE  bioproject='PRJNA494931';"
sraql_ch = channel.sraql.fromQuery(sraqlQuery)

process TEST {
    input:
        val(sraqlMap)

    script:
        """
        echo ${sraqlMap.acc}
        """
}

workflow {
    TEST(sraql_ch)
}


```

With `sraql.source='google-bigquery'` in the `nextflow.config` file, gives the following result

```
(base) bash-5.0$ ./launch.sh _scratch/sraqldb.nf -plugins nf-sraql -process.echo true
N E X T F L O W  ~  version 21.10.1
Launching `_scratch/sraqldb.nf` [clever_tesla] - revision: 086cce980a
executor >  local (3)
[59/85fc8a] process > TEST (1) [100%] 3 of 3 ✔
SRR7974375

SRR7974376

SRR7974377



```

**Comment by pditommaso** [comment]
Closing this was promoted to an independent project https://github.com/nextflow-io/nf-sraql

**Pull request closed without merging**
