### PR TITLE
add Apptainer support derived from Singularity implementation.

### PR DESCRIPTION
**Pull request by tbugfinder**
Closes: #2970 

Signed-off-by: tbugfinder <tbugfinder@online.ms>

### CODE REVIEW

**Comment by pditommaso** [comment]
Thanks a lot for this valuable PR. I wonder if the Apptainer image format is different from the Singularity one. If they use the same images I guess the `SingularityCache` is not really needed.

**Comment by tbugfinder** [comment]
Apptainer supports and uses the SIF format. It doesn't add its dedicated container format.

**Comment by pditommaso** [comment]
Thanks for clarifying this. Also, I was wondering if specific support in nextflow is really needed. Stating the [Apptainer faq](https://apptainer.org/news/community-announcement-20211130/) the backward should be available, at least at this stage 

>  Apptainer will provide singularity as a command line link and will maintain as much of the CLI and environment functionality as possible. From the user's perspective, very little, if anything, will change.

**Comment by tbugfinder** [comment]
Correct 👍 
Apptainer installation includes singularity alias.
Nevertheless apptainer has deprecated singularity environment variables and might add specific APPTAINER_* vars in upcoming releases. Therefore Apptainer specific support makes sense.

https://apptainer.org/docs/user/main/singularity_compatibility.html#singularity-environment-variable-compatibility

**Comment by pditommaso** [comment]
OK, agree on that. However, I've realised that the current implementation it's just identical to singularility and likely they will not diverge dramatically, at least in the short term. 

I think it would make sense to refactor the current implementation using common base class `BaseSingularityBuilder` with the current logic and parametrising the `singularity|apptainer` naming into an abstract method that can be defined by `SingularityBuilder` and `ApptainerBuilder` sub-classes.

**Comment by pditommaso** [comment]
Closing in favour of #3345

**Pull request closed without merging**
