### PR TITLE
Fix upload of nested directory outputs on azure

### PR DESCRIPTION
**Pull request by fbdtemme**
This PR fixes the issue described in #2577

### CODE REVIEW

**Review by pditommaso — CHANGES_REQUESTED** [review]
Thanks a lot for this PR. This is is very welcome. It would be important to capture the issue in the integration tests run this by script 

https://github.com/nextflow-io/nextflow/blob/master/validation/azure.sh#L1-L1

Any change to a small test to replicate the problem?

**Comment by fbdtemme** [comment]
The ./test-subdirs.nf test case now reproduces this error.

**Comment by pditommaso** [comment]
Thanks a lot

**Comment by fbdtemme** [comment]
Had to update some assertion statements, should be fixed now.

**Review by pditommaso — APPROVED** [review]

**Comment by pditommaso** [comment]
Awesome, thanks.

**Pull request merged**
