### PR TITLE
Add -entry parameter to pass in k8s executor

### PR DESCRIPTION
**Pull request by xhejtman**
Some pipelines need to pass -entry parameter. Make it work with kuberun executor.

### CODE REVIEW

**Review by pditommaso — CHANGES_REQUESTED** [review]
Thanks for submitting this PR. Please a corresponding test in this class https://github.com/nextflow-io/nextflow/blob/9c140cee318c29d23aad4ae3f2a3a6e23049287f/modules/nextflow/src/test/groovy/nextflow/k8s/K8sDriverLauncherTest.groovy#L101-L119

Moreover, the commit(s) should be signed as explained [here](https://github.com/nextflow-io/nextflow/blob/master/CONTRIBUTING.md#contributing-code-changes) to be eligible for merge. 

Thanks a lot

**Review by pditommaso — CHANGES_REQUESTED** [review]
Please keep this into a separate PR. Also, this change can introduce unexpected side effects on current users, therefore I think it'd better to make it an opt-in option

**Comment by xhejtman** [comment]
sorry the merge of two PRs was not intended. I am not much familiar with PRs.

**Comment by xhejtman** [comment]
test should be fixed

**Comment by pditommaso** [comment]
Nice, thanks a lot for contributing to the project.

**Pull request merged**
