### PR TITLE
Run tasks under user accounts in Azure Batch

### PR DESCRIPTION
**Pull request by manuelesimi**
This PR attaches the user identity to the pool. There are two options:

1) If the configuration specifies `runAs`, the task is run under that user. The assumption here is that the user already exists on the execution node in the pool.

2) `runAs` is omitted. In this case, the usual auto-user identity is explicitly attached to the task. For this identity, it is also possible to set `privileged` to `true` to run the task under elevated access (see https://docs.microsoft.com/en-us/azure/batch/batch-user-accounts#elevated-access-for-tasks).

Technically, Azure Batch also offers the possibility to create a user on the fly in the pool, but I don't feel it is needed in this context. Either the auto-user or the pre-existing user should cover all the use cases I can think of.

### CODE REVIEW

**Review by pditommaso — CHANGES_REQUESTED** [review]
Nice! thanks a lot for this PR! there's a failing test to address. Everything else looks awesome 👍

**Comment by manuelesimi** [comment]
Whoops, I didn't notice the side effect on the hash. I fixed the expected poolId.

**Comment by pditommaso** [comment]
Included in release `21.06.0-edge`.

**Comment by vinishgeorge** [comment]
I have test this and can confirm its working for me . Thank you @pditommaso  @manuelesimi for the quick response !!.

**Pull request merged**
