### PR TITLE
Fix chmod command to accommodate hidden files in bindir (or empty bindir)

### PR DESCRIPTION
**Pull request by abhi18av**
This PR addresses the suggestion in https://github.com/nextflow-io/nextflow/issues/3227#issuecomment-1254946739

### CODE REVIEW

**Comment by bentsherman** [comment]
From our discussion today, the command should be:
```bash
chmod +x $PWD/nextflow-bin/{.*,*}
```

**Comment by pditommaso** [comment]
yeah the `-R` recurse the subdir which may not be desirable. I think it could be even better using 

```
chmod +x $PWD/nextflow-bin/* || true
```

**Comment by bentsherman** [comment]
Yes, I like the `|| true` better.

**Comment by abhi18av** [comment]
Thanks @bentsherman @pditommaso for the review, I have now accommodated the feedback.

**Review by bentsherman — APPROVED** [review]

**Pull request merged**
