### PR TITLE
Add the fcp tool option to file copy strategy

### PR DESCRIPTION
**Pull request by abhi18av**
This PR builds upon the discussion in https://github.com/nextflow-io/nextflow/issues/3549#issuecomment-1385020467 

( And the automated tests have betrayed the build again 😅 )

All tests passing locally 

image

### CODE REVIEW

**Review by bentsherman — APPROVED** [review]

**Comment by pditommaso** [comment]
Has this been tested? you can try it in your computer specifying `fcp` in the stage out directive and using `process.scratch = true`

**Comment by abhi18av** [comment]
Yes, I've tested this locally (with `rnaseq-nf` pipeline) and it is working as expected 

- Changes to `nextflow.config` 

```nextflow

  mamba_rclone {
    conda.enabled = true
    conda.useMamba = true
    process {
        conda = "$baseDir/conda.yml"
        stageOutMode = "rclone"
        scratch = "scratch-dir"
    }
  }



```


- Execution of the pipeline with the local `mamba_fcp` profile

```console
~/p/n/_/rnaseq-nf (master|✚1) $ time ../../launch.sh run main.nf -profile mamba_fcp                                               (base) 
N E X T F L O W  ~  version 23.01.0-edge
Launching `main.nf` [shrivelled_koch] DSL2 - revision: 4ab4121ede
 R N A S E Q - N F   P I P E L I N E
 ===================================
 transcriptome: /Users/eklavya/projects/nextflow/_resources/rnaseq-nf/data/ggal/ggal_1_48850000_49020000.Ggal71.500bpflank.fa
 reads        : /Users/eklavya/projects/nextflow/_resources/rnaseq-nf/data/ggal/*_{1,2}.fq
 outdir       : results
 
executor >  local (6)
[d4/6c9aa8] process > RNASEQ:INDEX (ggal_1_48850000_49020000) [100%] 1 of 1 ✔
[00/a7bbab] process > RNASEQ:FASTQC (FASTQC on ggal_gut)      [100%] 2 of 2 ✔
[35/82595f] process > RNASEQ:QUANT (ggal_liver)               [100%] 2 of 2 ✔
[7d/675a97] process > MULTIQC                                 [100%] 1 of 1 ✔

Done! Open the following report in your browser --> results/multiqc_report.html
```

- The use of `nxf_fs_fcp` function in `.command.run` files 


image

**Comment by pditommaso** [comment]
Why GH tests do not run with your PRs!!? 😄

**Comment by abhi18av** [comment]
I have the same thousand $$$ question 😅 

I have checked the `build.yml` Github actions file but that doesn't give me a clue https://github.com/nextflow-io/nextflow/blob/41510e874644af8fe8986f04fa5bad20bb9a430f/.github/workflows/build.yml#L13 

Technically, it should even trigger as soon as resync this branch using "Update branch" option on the Github UI - testing it now.

But unless I am mistaken, I recall even @bentsherman mentioned that he has seen similar behavior on some of PRs.

**Comment by pditommaso** [comment]
I think because there's a `/` in the branch name. Try changing the name of the branch

**Comment by abhi18av** [comment]
Just tried it https://github.com/nextflow-io/nextflow/pull/3563 but unfortunately no dice 

image
 

I've also tried to address that suspicion in the past  https://github.com/nextflow-io/nextflow/pull/3445 with a different branch name `abhinav-enhanced-azcopy-options`.

**Comment by pditommaso** [comment]
then run `make smoke` in your computer and swear that all tests are green 😄

**Comment by abhi18av** [comment]
Paolo, you can trust me 😉 

But anyways, I've tested this locally via `make clean` and  `make smoke` and all tests are passing against the latest commit in this branch https://github.com/nextflow-io/nextflow/pull/3556/commits/0d3f59092f61901c605b8e4a7e709d014f7bf41f 

image

**Comment by pditommaso** [comment]
Included in version 23.02.0-edge

**Pull request merged**
