### PR TITLE
Add/process.dockerfile

### PR DESCRIPTION
**Pull request by marcodelapierre**
@pditommaso  have fun!

this is a small one.

it comes out of some of our discussions within https://github.com/nextflow-io/nf-wave/issues/4

have the loooong flight in a few hours .. touching base in Milan tomorrow!

### CODE REVIEW

**Comment by pditommaso** [comment]
Not super sure about this, need to think a bit

**Comment by marcodelapierre** [comment]
I knew it, sure, also happy to discuss here or email or slack

**Comment by marcodelapierre** [comment]
No rush at all

**Comment by marcodelapierre** [comment]
I have just got the github app on the phone, I can be more responsive now 😉

**Comment by pditommaso** [comment]
I've commented about this [here](https://github.com/nextflow-io/nf-wave/issues/4#issuecomment-1566183849)

**Comment by pditommaso** [comment]
I'm bit concerned about overloading Wave with too many feature, and I haven't seen any real user demand for this specific capability. I suggest closing this and reconsidering in the future if needed.

**Comment by marcodelapierre** [comment]
I agree - the community has spoken, so let's go with the K.I.S.S. approach :-)

**Pull request closed without merging**
