### PR TITLE
wr executor module

### PR DESCRIPTION
**Pull request by sb10**
Work in progress for an executor that uses wr as a scheduler. See #1088

### CODE REVIEW

**Comment by pditommaso** [comment]
Don't forget to sign the DCO. See for details https://github.com/nextflow-io/nextflow/blob/master/CONTRIBUTING.md#contributing-code-changes

**Comment by sb10** [comment]
> Don't forget to sign the DCO. See for details https://github.com/nextflow-io/nextflow/blob/master/CONTRIBUTING.md#contributing-code-changes

I'll do that. By the way, that document mentions and explicitly links to the docs for `git commit -S`, when what you actually want is `git commit -s`. The 2 are completely different.

**Comment by pditommaso** [comment]
Oops, thanks for mentioning highlighting that.

**Comment by pditommaso** [comment]
Sorry for not having replied before. As I was mentioning the idea is to externalise modules as external components. Therefore  I'm merged manually the core changes to enable the wr executor as a separate plugin. 

Have a look at 21088ad3e5890d4ecdb0f8e17b75f6d5b9e99ba6. 

I can help you to set up the remaining part of the code as a separate project.

**Comment by sb10** [comment]
> I can help you to set up the remaining part of the code as a separate project.

Yes please, is there an example of this already?

**Comment by pditommaso** [comment]
I've just created a project skeleton.

**Pull request closed without merging**
