### PR TITLE
Fix minor typos in changelogs/source code

### PR DESCRIPTION
**Pull request by mribeirodantas**

### CODE REVIEW

**Review by pditommaso — APPROVED** [review]
Cool, thanks

**Comment by pditommaso** [comment]
Oops tests failed

**Comment by mribeirodantas** [comment]
Yeah, but it can't be the PR, right? 😅

**Comment by bentsherman** [comment]
I think all the PRs started failing with this error:

```
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested
```

Seems related to #4314

**Comment by mribeirodantas** [comment]
LGTM?

**Pull request merged**
