### PR TITLE
List requirements on pre-existing named pools in Azure.

### PR DESCRIPTION
**Pull request by manuelesimi**
After running some tests on pre-existing named pools in Azure, I found out some requirements not listed in the current documentation but needed by Nextflow to use these pools as queues where to submit tasks.

### CODE REVIEW

**Review by pditommaso — COMMENTED** [review]
Hi Manuele, thanks for the detailed contribution. Regarding the need to adding the `azcopy` tool, NF should be able to download it automatically when the task start (when the pool was not created by NF itself) 

https://github.com/nextflow-io/nextflow/blob/711362ca895cafb3f7f01651050c4dfc0cba9557/plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy#L359-L364

**Comment by manuelesimi** [comment]
Hi @pditommaso, thanks for clarifying.

After I posted my comment I realized that I had the _copyToolInstallMode_ option set to `node` instead of `task`. That indeed does the job. I'd still list `azcopy` among the requirements for pre-created pools and explain to set  _copyToolInstallMode_ to `task` to match the requirement.

**Comment by pditommaso** [comment]
> That indeed does the job. I'd still list azcopy among the requirements for pre-created pools and explain to set copyToolInstallMode to task to match the requirement 

This makes sense tho something still weird. The setting is set automatically so that  when the pool is not created by NF the azcopy is copied for each task 

https://github.com/nextflow-io/nextflow/blob/9e9337d3e847a7a657ac25ca39fcab8bac487938/plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzBatchOpts.groovy#L126-L138

**Comment by manuelesimi** [comment]
Hi @pditommaso, you're right. Another error (with the docker container) led me to manually install the azcopy tool on the nodes (or set copyToolInstallMode to task). Now that I solved it, I see that NF does the installation automatically. 

Bottom line, the code you pasted indeed works :) 
Thanks!

**Comment by pditommaso** [comment]
Good! 😎 then what about point 3 in your PR?

**Comment by manuelesimi** [comment]
> Good! 😎 then what about point 3 in your PR?

Just removed ;)

**Review by pditommaso — APPROVED** [review]
Thanks Manuele.

**Pull request merged**
