### PR TITLE
Add debug messages for wave null container engine error

### PR DESCRIPTION
**Pull request by bentsherman**
Related to #3965

### CODE REVIEW

**Comment by pditommaso** [comment]
This looks suspicious 

https://github.com/nextflow-io/nextflow/blob/e4a878b6ce6d62bfd809fbbb88a6d4f2639e214f/modules/nextflow/src/main/groovy/nextflow/script/WorkflowMetadata.groovy#L242-L242

I fear the `.with` has some side effects on the ContainerConfig object. WDYT?

**Comment by pditommaso** [comment]
I've followed a different approach, following back to `docker` when the engine is null and logging the wrong config object

**Comment by bentsherman** [comment]
Okay, your changes seem more likely to help.

I don't understand though how the `.with()` would affect anything, since the workflow metadata container engine isn't referenced anywhere else in the code

**Comment by pditommaso** [comment]
> I don't understand though how the .with() would affect anything

yeah, I don't believe is related. Just removed it because it's an unusual pattern

**Pull request closed without merging**
