### PR TITLE
Remove redundant DSL version checks

### PR DESCRIPTION
**Pull request by bentsherman**
First batch of changes from #3344 . Includes the most straightforward changes that don't break a bunch of tests or require much refactoring.

* DSL1 deprecation errors that are now unreachable since DSL1 will fail at the beginning anyway
* ~~Classes and methods marked as `@Deprecated` that aren't used anywhere else in the code~~

### CODE REVIEW

**Comment by bentsherman** [comment]
@pditommaso The tests ran and everything looks good. I will update parts 2 and 3.

**Comment by bentsherman** [comment]
@pditommaso I reduced this PR to focus only on DSL1-related code, since targeting all deprecated code was probably too broad and harder to review.

**Comment by bentsherman** [comment]
More importantly, the unit tests no longer use `Channel.close()` which was deprecated by DSL2.

**Comment by pditommaso** [comment]
Merged manually via 2b433a52

**Pull request closed without merging**
