### PR TITLE
GCE Integration

### PR DESCRIPTION
**Pull request by olifly**
* New CloudDriver that allows the creation of an ignite cluster in GCE (https://cloud.google.com/compute/)
* New Executor that runs nextflow scripts as Google Pipelines (https://cloud.google.com/genomics/)

### CODE REVIEW

**Comment by pditommaso** [comment]
Hi Ólafur, amazing contribution. Let's start with basic stuff. Please fix the failing test and please check the [DCO](https://github.com/apps/dco) requirement. Thanks a lot!

**Comment by olifly** [comment]
I'm creating a new pull request where our contribution is squahed into a single commit and dco signed.  Closing this one.

**Comment by pditommaso** [comment]
ok, great. For future reference it was also possible just to force the push with `git push -f` to update this one 👍

**Comment by olifly** [comment]
Yeah, but after couple of hours of  a "fun" git rebase session to see if I could retroactively add sign off to our previous commits I decided it would just be simpler to create a new branch with everything squashed and signed and go from there :)

**Comment by pditommaso** [comment]
ah-ah, yes, git can be really fun 😉

**Pull request closed without merging**
