### PR TITLE
Force kuberun to wait for pods before shutdown

### PR DESCRIPTION
**Pull request by kfrancisdev**
- wait for pod to stop running before shutdown.
- Patch for Issue #2654

### CODE REVIEW

**Comment by bentsherman** [comment]
Have you tested this fix with your nextflow run? Did the workflow wait until the pods were deleted?

**Comment by kfrancisdev** [comment]
> Have you tested this fix with your nextflow run? Did the workflow wait until the pods were deleted?

I tested this fix manually. It waited until the pod was not running. Specifically, it waited until the pod succeeded. The pod still is present after the status is succeeded. So that behavior does not change. I think the pod should be explicitly deleted in shutdown if it's not running

**Comment by pditommaso** [comment]
That sounds reasonable. Please add sign off the commit to make the DCO bot pass https://github.com/nextflow-io/nextflow/pull/2667/checks?check_run_id=5296377084

**Comment by kfrancisdev** [comment]
Sign-off added.

**Comment by pditommaso** [comment]
Thanks a lot!

**Pull request merged**
