### PR TITLE
Use peak_rss as memory metrics for the workflow report and timeline

### PR DESCRIPTION
**Pull request by phupe**
Modification to use the peak_rss as memory metrics for the workflow report and timeline instead of vmem as suggested in Issue #980.

### CODE REVIEW

**Comment by phupe** [comment]
As RSS memory corresponds to the memory held in the RAM, reporting this metrics really helps to calibrate the amount of memory resources to ask to the job scheduler when submitting the job on a cluster.

Sounds good to me to add a third tab in the memory chart to report the peak rss.

**Comment by phupe** [comment]
As suggested a new chart to display the peak rss in addition to vmem has been added. Same for the timeline.

**Comment by phupe** [comment]
I didn't change `return bytes.toFixed(1)+' '+units[u];` to `return bytes.toFixed(3)+' '+units[u];` in file 
modules/nextflow/src/main/resources/nextflow/trace/assets/ReportTemplate.js in this pull request as suggested in #986 .

Do you want me to integrate this modification in this pull request?

**Comment by pditommaso** [comment]
Yes please.

**Comment by pditommaso** [comment]
OK, I've found the critical line. I can do that patch on `ReportTemplate.js` file. Thanks!

**Comment by pditommaso** [comment]
Included in version `19.01.0-edge`.

**Pull request merged**
