### PR TITLE
Remove CDN from timeline reports and make them offline readable

### PR DESCRIPTION
**Pull request by tamasgal**
This PR removes the CDN-included JavaScript files and also the font from Google to be able to view the timeline repots offline and also to remove unwanted traces for people who would not like to tell Google when they are looking at their reports `;)`

I also cleaned up the the code around the template generation a little bit but now it would also be a good opportunity to extract the template generation out of `TimelineObserver` and `ReportObserver`, since those are currently doing more or less the same.

I modified the `d3-timeline.js` a bit and removed the cosmetics-logic from `TimesliceObserver` into `d3-timeline.js`, before it was entangled and also a bit hard to understand.

There are of course still quite a few things which could be improved.

Let me know what you think.

### CODE REVIEW

**Comment by tamasgal** [comment]
Sorry, I am not familiar with the testing procedure of Groovy/Spock. I managed to run the test environment locally to reproduce the errors and attempted to fix the tests, however I need to figure out how to turn on some logging to see what's expected and what's delivered... also the development cycle seems to be extremely slow compared to other languages I work with, but I guess that's the lack of my knowledge how to set it up and use it correctly `;)`

**Comment by abhi18av** [comment]
Hi @tamasgal , thanks for this effort!

Would it be possible for you to share a sample generated report using the changes in this PR?

**Comment by tamasgal** [comment]
Yes of course, I completely forgot!

With this `nextflow.config` (I needed a container on my Mac with `ps` installed and `python:3.6` was already there `;)`):

```
process.container = 'python:3.6'
docker.enabled = true
```

and the following workflow `test.nf`:

```nextflow
process foo {
  script:
  """
  sleep 3
  """
}

process bar {
  script:
  '''
  sleep 2
  '''
}

process narf {
  script:
  '''
  sleep 4
  '''
}

process fjoord {
  echo true
  script:
  '''
  sleep 5
  '''
}
```

I get the attached HTML template when running:

```
░ tamasgal@greybox.local:nextflow  remove-cdn-from-timeline ●
░ 13:04:10 > ./launch.sh test.nf -with-timeline timeline-offline.html -with-docker
N E X T F L O W  ~  version 21.02.0-edge
Launching `test.nf` [mad_cray] - revision: 3d415a4248
executor >  local (4)
[4e/a3b9d3] process > foo    [100%] 1 of 1 ✔
[c1/22fdf7] process > bar    [100%] 1 of 1 ✔
[3e/aad9a6] process > narf   [100%] 1 of 1 ✔
[5e/dd2c71] process > fjoord [100%] 1 of 1 ✔
```

[timeline-offline.html.zip](https://github.com/nextflow-io/nextflow/files/6035783/timeline-offline.html.zip)

**Review by pditommaso — CHANGES_REQUESTED** [review]
Hi, thanks a lot for this PR. Yes, this can be useful, the only side-effect is that the report file is larger because it contains all the JS assets, but 200k should be fair. 

I would prefer to continue to use the current google font, which I find more readable. When offline it should fallback the browser default one. Don't think it constitutes a privacy issue.  

Please signoff the contribution DCO to the PR merged. Mor details hre 

https://github.com/nextflow-io/nextflow/blob/master/CONTRIBUTING.md#contributing-code-changes

Thanks a lot

**Comment by tamasgal** [comment]
Alright, thanks for the feedback Paolo! I will put back the Google font and will also fix the remaining two unit tests; it just takes a bit longer as I am new to Groovy (I had some fun Groovy fun with Jenkins a few years ago though `;)`).

I can also add an additional minified version of the `d3-timeline.js` and check how much we could squeeze out.

**Comment by pditommaso** [comment]
Thanks! I much appreciated the good quality of the code. Your groovy skills don't look so bad!  

The failing tests may be due to a build problem with pull requests. I'm trying to solve it.

**Comment by tamasgal** [comment]
Ha, thanks, it's still a long way to go, but I am willing to improve since `nextflow` seems to be the hottest candidate for our workflow management system in KM3NeT, the next generation neutrino telescope experiment `:)`.

The two failing tests are the one which compares the HTML output to a reference HTML file. I replaced it locally but there is still a difference and I have a hard time figuring it out from the unit test suite HTML report, but it's just a matter of time.

The second failing test is related to the HTML template reading, where I also changed the function's signature. I just need to write a suitable test for it.

I think I will have time today or tomorrow to fix those...

**Comment by pditommaso** [comment]
> the next generation neutrino telescope experiment

Oh, this looks really sexy 🤩

> The two failing tests are the one which compares the HTML output to a reference HTML file

You. can check test locally using `make smoke` (faster) or `make test` (all tests, slower), then look at the generated report. Using IntelliJ it's even easier

**Comment by tamasgal** [comment]
Ah, `make smoke` is a good advice. I am still struggling with the IntelliJ, I use it for writing the code (it's utterly helpful when you are new to a language, even if I am a hardcore Vim/DoomEmacs user) but setting up the configurations for testing is a bit mysterious. I should probably study that first `;)`.

**Comment by pditommaso** [comment]
> setting up the configurations for testing is a bit mysterious

It should not try following these steps: https://github.com/nextflow-io/nextflow#intellij-idea

**Comment by tamasgal** [comment]
Yes I did that already but could not figure out how to run the test suite from there. But I don't want to waste your time, I will surely figure it out later `;D`

**Comment by abhi18av** [comment]
@tamasgal , for this you could look into the `Gradle` window. Try using the following keystrokes `Ctrl + Tab` and then press `G` while keeping the `Ctrl` pressed. Or simply, use `View -> Tool windows -> Gradle` and then select the appropriate task.


image



Hope this helps :)

**Comment by tamasgal** [comment]
Perfect, thanks! I was able to run the whole test suite from `Tasks/verification/test` and from there I can rerun just also a single test, that shortens my development cycle by a factor of 100 or so 😆

**Comment by tamasgal** [comment]
Uh, sorry, something went crazy on merging from master, let me fix that...

**Comment by tamasgal** [comment]
Alright, tests are fixed. I eventually removed the one which tests the `readTemplate` function as it is already tested inside `renderHTML` and is just a simple file reader anyways, but if you want, I can add a small one.

**Review by pditommaso — APPROVED** [review]

**Comment by pditommaso** [comment]
All fine. thanks for this contribution

**Pull request merged**
