### PR TITLE
Allow launcher to be set up outside NXF_HOME

### PR DESCRIPTION
**Pull request by douglasgscofield**
We have Nextflow installed in our compute cluster's module system with NXF_HOME set to an installation subdirectory. Users were getting errors running nextflow because for each novel NXF_HOST the launcher could not be installed under NXF_HOME because it is not user-writable.  This pull request is one possible way to address this, by using NXF_LAUNCHBASE as the base of the launcher directory.  If NXF_LAUNCHBASE is set by the user, it is used; if not, then if NXF_HOME is writable, NXF_LAUNCHBASE is set to that; if not, then if NXF_TEMP is set then NXF_LAUNCHBASE is set to that; else fail.

### CODE REVIEW

**Comment by pditommaso** [comment]
Hi @douglasgscofield, is it fine the workaround I've proposed ?

**Comment by pditommaso** [comment]
use the `NXF_TEMP` if defined. See https://github.com/nextflow-io/nextflow/commit/d7f8a7e4ff9b0fffebb9283f0d7a0782d73e4d21

Thanks for the contribution.

**Comment by douglasgscofield** [comment]
Thanks, sorry for the no feedback.  Disappeared down the email stack.  I'm happy with the workaround, thanks!

**Comment by pditommaso** [comment]
Good! :)

**Pull request closed without merging**
