### PR TITLE
Fix #3217 fixOwnership not working

### LINKED ISSUE #3217: fixOwnership does not work in all cases
## Bug report 

The option docker.fixOwnership does not fix the ownership in all cases.

### Expected behavior and actual behavior

**Expected**
The owner of all files produced by nextflow should be the user executing Docker even if Docker is not rootless. So that the `rm -rf <taskdir>` should not require root permission.

**Actual**
Only files owned by root within the container will be `chown`ed to the users uid. Files that got created by a user within the container by an Id other than 0 or host's UID can only be removed by root.

### Steps to reproduce the problem
1. Make sure you are not `root`
2. Create the following `nextflow.config`
  ```
  docker.enabled=true
  docker.fixOwnership=true
  ```
3. Execute following .nf
  ```nextflow
  process p{
  debug true
  container "ubuntu"
  """
    echo asdf > asdf.txt
    mkdir folder
    echo asdf > folder/asdf.txt
    useradd test
    useradd nextflow
    mkdir nextflow
    chown -R nextflow:nextflow nextflow
    su nextflow << EOF
      pwd
      echo asdf>nextflow/asdf.txt
    EOF
  """
  }
  
  workflow{
  p()
  }
```
4. Try to delete the `work` folder. Or task folder if you have other task folders
5. Should show a permissions error
### Program output 

```shell
# nextflow run main.nf
N E X T F L O W  ~  version 22.04.5
Launching `main.nf` [soggy_banach] DSL2 - revision: dda238d01f
executor >  local (1)
[df/d116c5] process > p [100%] 1 of 1 ✔
/tmp/nt-tmp/work/df/d116c5026044cbaed505a6b318fcae

# rm -rf work\
rm: cannot remove 'work/df/d116c5026044cbaed505a6b318fcae/nextflow/asdf.txt': Permission denied
```

**.nexflow.log**
```
Sep-19 13:44:46.259 [main] DEBUG nextflow.cli.Launcher - $> nextflow run main.nf
Sep-19 13:44:46.294 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.04.5
Sep-19 13:44:46.311 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /tmp/nt-tmp/nextflow.config
Sep-19 13:44:46.312 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /tmp/nt-tmp/nextflow.config
Sep-19 13:44:46.328 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Sep-19 13:44:46.664 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 by global default
Sep-19 13:44:46.678 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [soggy_banach] DSL2 - revision: dda238d01f
Sep-19 13:44:46.691 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/home/kibu/.nextflow/plugins; core-plugins: nf-amazon@1.7.2,nf-azure@0.13.2,nf-console@1.0.3,nf-ga4gh@1.0.3,nf-google@1.1.4,nf-sqldb@0.4.0,nf-tower@1.4.0
Sep-19 13:44:46.693 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Sep-19 13:44:46.702 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Sep-19 13:44:46.703 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Sep-19 13:44:46.706 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Sep-19 13:44:46.714 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Sep-19 13:44:46.754 [main] DEBUG nextflow.Session - Session uuid: f6fc71d2-9e97-4d28-9fd7-e504e135fb16
Sep-19 13:44:46.755 [main] DEBUG nextflow.Session - Run name: soggy_banach
Sep-19 13:44:46.755 [main] DEBUG nextflow.Session - Executor pool size: 8
Sep-19 13:44:46.776 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 22.04.5 build 5708
  Created: 15-07-2022 16:09 UTC (18:09 CEST)
  System: Linux 5.19.7-1-MANJARO
  Runtime: Groovy 3.0.10 on OpenJDK 64-Bit Server VM 18.0.2+0
  Encoding: UTF-8 (UTF-8)
  Process: 1323994@earth [127.0.1.1]
  CPUs: 8 - Mem: 31.1 GB (4.6 GB) - Swap: 34.2 GB (33 GB)
Sep-19 13:44:46.793 [main] DEBUG nextflow.Session - Work-dir: /tmp/nt-tmp/work [tmpfs]
Sep-19 13:44:46.793 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /tmp/nt-tmp/bin
Sep-19 13:44:46.798 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Sep-19 13:44:46.805 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Sep-19 13:44:46.816 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Sep-19 13:44:46.823 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 9; maxThreads: 1000
Sep-19 13:44:46.864 [main] DEBUG nextflow.Session - Session start invoked
Sep-19 13:44:47.006 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Sep-19 13:44:47.047 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Sep-19 13:44:47.048 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Sep-19 13:44:47.051 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Sep-19 13:44:47.058 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=8; memory=31.1 GB; capacity=8; pollInterval=100ms; dumpInterval=5m
Sep-19 13:44:47.155 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: p
Sep-19 13:44:47.155 [main] DEBUG nextflow.Session - Ignite dataflow network (1)
Sep-19 13:44:47.155 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > p
Sep-19 13:44:47.156 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Sep-19 13:44:47.156 [main] DEBUG nextflow.Session - Session await
Sep-19 13:44:47.284 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Sep-19 13:44:47.288 [Task submitter] INFO  nextflow.Session - [df/d116c5] Submitted process > p
Sep-19 13:44:48.213 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: p; status: COMPLETED; exit: 0; error: -; workDir: /tmp/nt-tmp/work/df/d116c5026044cbaed505a6b318fcae]
Sep-19 13:44:48.220 [main] DEBUG nextflow.Session - Session await > all process finished
Sep-19 13:44:48.221 [main] DEBUG nextflow.Session - Session await > all barriers passed
Sep-19 13:44:48.224 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=1; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=179ms; failedDuration=0ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ]
Sep-19 13:44:48.314 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Sep-19 13:44:48.322 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

### Environment 

* Nextflow versions:
  N E X T F L O W
  version 22.04.5 build 5708
  created 15-07-2022 16:09 UTC (18:09 CEST)
  cite doi:10.1038/nbt.3820
  http://nextflow.io
  
  and

  N E X T F L O W
  version 22.09.3-edge build 5767
  created 10-09-2022 14:55 UTC (16:55 CEST)
  cite doi:10.1038/nbt.3820
  http://nextflow.io
* Java version:
  openjdk version "18.0.2" 2022-07-19
  OpenJDK Runtime Environment (build 18.0.2+0)
  OpenJDK 64-Bit Server VM (build 18.0.2+0, mixed mode)
* Operating system:
  LSB Version:	n/a
  Distributor ID:	ManjaroLinux
  Description:	Manjaro Linux
  Release:	22.0.0
  Codename:	Sikaris
* Bash version:
  GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
  Copyright (C) 2020 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

### PR DESCRIPTION
**Pull request by Kibubu**
Fixes the issue #3217

Not sure if `--from root` is there to preserve multiple UIDs from different process.

Signed-off-by: Kibubu <85624897+Kibubu@users.noreply.github.com>

### CODE REVIEW

**Comment by pditommaso** [comment]
Indeed, the flag `--from root` is used to only apply ownership change to root owner files.

**Comment by Kibubu** [comment]
So, should there be another solution that changes only those file created by the task an not those copied in for example?

**Comment by Kibubu** [comment]
You are correct, this example is rather fabricated, but since I guess [he](https://nextflow.slack.com/archives/C02T98A23U7/p1663085963643459?thread_ts=1662741368.042059&cid=C02T98A23U7) and myself stumbled upon it there might be more people involved. Most will probably just `sudo rm` those files.

My example could also be buried in script within the container and totally hidden from the user.

But as always if the consequences of removing the `--from root` clause are greater the benefits this PR and issue can be closed.

**Comment by pditommaso** [comment]
Ultimately this is an old trick, that would be better to not use and we may even deprecate. 

To prevent this problem the user of `runOptions` can provide a better solution 

https://github.com/CRG-CNAG/CalliNGS-NF/blob/master/nextflow.config#L14

**Comment by Kibubu** [comment]
Well I guess I'll close the PR but would leave the Issue open for further discussions.

Providing runOptions won't solve the demonstrated problem. The script should show the same behavior regardless of being executed inside a container or not. That also means modifying the script to suit the container could be considered an anti-pattern.

One option would be to add a note to the docs that only containers should not change UIDs during their execution. Or it is the responsibility of the container to chown all created files to the initial UID.

**Pull request closed without merging**
