### PR TITLE
more famous scientist

### PR DESCRIPTION
**Pull request by JoseEspinosa**
My two cents

### CODE REVIEW

**Comment by pditommaso** [comment]
Now you are contributor 😄 😄 👏 👏

**Comment by JoseEspinosa** [comment]
Finally 😂
It could be an opportunity to start playing

2017-06-30 14:08 GMT+02:00 Paolo Di Tommaso <notifications@github.com>:

**Comment by pditommaso** [comment]
Fuck Jose! you made the build [crash](https://travis-ci.org/nextflow-io/nextflow/builds/248755993)! 

The comma after `pauling` !! 😂

**Comment by JoseEspinosa** [comment]
noooo, fuck!!!


2017-06-30 14:13 GMT+02:00 Paolo Di Tommaso <notifications@github.com>:

**Comment by pditommaso** [comment]
no worry, I will fix :)

**Pull request merged**
