### PR TITLE
fixes bug 389

### PR DESCRIPTION
**Pull request by msmootsgi**
So, the approach I've arrived at is to NOT run `git pull` if the repo in question is checked out to a tag or commit hash.  My original idea of running the equivalent of `git pull origin tagname` does not appear to work with JGit.  Creating a pull command with `git.pull().setRemoteBranchName(tagname)` doesn't help.  Adding a `.setRemote('origin')` doesn't help either (and is the default in the JGit code anyway).

Instead I simply check the repo to see if it's checked out to a tag and if so, don't run `git pull`.  This won't cause any problems for a commit hash and could only cause a problem with a tag if you happen to re-write the tag with a new hash.  In that case, however, I feel like you get what you deserve for violating the integrity of the tags!  :)

Anyway, let me know what you think.  I've added several tests and run this locally a bunch, but please give this a close look.

### CODE REVIEW

**Comment by pditommaso** [comment]
Thanks a lot. Basically it's not possible to pull a tagged repo. I'm wondering if a more recent version of JGit could solve the problem. Also have you found any reference in the forum and/or stackoverflow ?

**Comment by msmootsgi** [comment]
I couldn't find anything on the web about JGit's inability to pull a tagged repo.  However, given how JGit [handles branches](http://download.eclipse.org/jgit/site/4.8.0.201706111038-r/apidocs/org/eclipse/jgit/lib/Repository.html#getFullBranch--), and what [detached HEAD state](https://stackoverflow.com/questions/5582208/checking-out-git-tag-leads-to-detached-head-state) is, it makes sense.  If you're ever in detached HEAD state then you've checked out to a commit hash, which is an immovable location in the git DAG, so there's no sense trying to move (i.e. pull).  Pulling won't ever change a commit hash, so why do it?   I don't love that JGit throws an exception when pulling in detached HEAD (it would be better to return already up-to-date, like native git), but since we know that it does, then I think checking to avoid the exception is a reasonable approach.

Thinking about my patch a little, I think the `taggedRepo` method would be more appropriately named `inDetachedHeadState` to better capture what it checks.

**Comment by pditommaso** [comment]
In principle this should be fine because tag are supposed to be immutable. However it is possible to force a tag to a new commit and it this case that would result in an inconsistent behaviour, do you agree? 

What about deleting the tag and continue with a fresh pull as before. Would that make sense?

**Comment by msmootsgi** [comment]
Correct, if you force a tag to change, then you'll get inconsistent behavior.  However, I think that inconsistency is better than the current behavior.  I already log a message, but perhaps a warning to STDOUT would help?

Is your suggestion that if the repo is in detached head mode, then delete the repo and re-clone it? That seems excessive, but I think it would solve the problem.  Let me see how easy or ugly that would be.

**Comment by pditommaso** [comment]
My understanding is that this error only happens when the `-latest` option is specified. So I guess it should be possible to do when the user specifies `-latest` and a *tag* is detected to: 

1) delete the tag in the local repo
2) fetch from origin (not really sure it's needed) 
3) continue as before. 

Makes sense ?

**Comment by msmootsgi** [comment]
Well, I'm glad you kept pushing!  As I was pondering how to accomplish what you wanted I decided to check if a new version of JGit now allowed pulling tags and it 4.8 does!  So I've reworked the code.  Now if the the repo is a tag then I set the remote branch name and pull, if the repo is on a commit hash I return Already Set, and if the repo is on a branch I pull like normal.  Let me know what you think!

**Comment by pditommaso** [comment]
Great! Now the only problem is that since [version 4.6](https://wiki.eclipse.org/JGit/New_and_Noteworthy/4.6) JGit requires Java 8. I'm planning to move NF to Java 8 soon, but not in the upcoming release but in the following one (0.27.x). 

Is it urgent this patch? alternatively could you check if the feature you are using for this patch was introduced in a version prior 4.6?

**Comment by msmootsgi** [comment]
Doh!  I tried version 4.5.3 of JGit, which came out fairly recently, but I get the DetachedHeadException again, so it appears as though the fix for pulling tags was added sometime 4.6 or later.  

While this issue is a concern for us, I think we can let this patch wait for 0.27.  In the meantime we can just use branches instead of tags.

**Comment by pditommaso** [comment]
OK, makes sense. Thanks a lot for taking care of this!

**Comment by pditommaso** [comment]
This is fine right? I can merge it?

**Comment by msmootsgi** [comment]
Yes, that would be great!

--
Mike Smoot, Ph.D.
Principal Software Engineer
Synthetic Genomics

**Comment by pditommaso** [comment]
Fantastic

**Comment by pditommaso** [comment]
I had to merge manually because there was a conflict. Thanks for the contribution!

**Pull request closed without merging**
