### PR TITLE
Kuberun: add plugins to config

### PR DESCRIPTION
**Pull request by Lehmann-Fabian**
Using `kuberun` with `-plugins xy` does not yet hand this over to the head-pod. This is implemented in this PR. It would be nice to have this, especially for CWS.

### CODE REVIEW

**Comment by pditommaso** [comment]
I feel a test is missing 😄

**Comment by pditommaso** [comment]
You are right.

**Comment by Lehmann-Fabian** [comment]
Thank you, seems to fix it :)

**Review by pditommaso — APPROVED** [review]

**Pull request merged**
