### PR TITLE
Add YAML/JSON parameter input documentation

### PR DESCRIPTION
**Pull request by apeltzer**
x-ref 

https://github.com/nextflow-io/nf-hack18/issues/4
https://github.com/nextflow-io/nextflow/issues/939

Please let me know if you need more adaptions here!

### CODE REVIEW

**Comment by pditommaso** [comment]
The proper location for this would in the documentation for the command line .. which does not exist. Therefore it's time to create it. I will this PR open and move there asap I've created a new page in the doc for that.

**Comment by apeltzer** [comment]
Ok, I wondered where to put this. Can also do that if you notify me once you created the page ?

**Comment by pditommaso** [comment]
Yes, I'll notify you 👍

**Comment by pditommaso** [comment]
See #950 .

**Comment by apeltzer** [comment]
Closed in favor of https://github.com/nextflow-io/nextflow/pull/964

**Pull request closed without merging**
