### PR TITLE
Refactor to add syslog appender #330

### PR DESCRIPTION
**Pull request by crashGoBoom**
Hi! Here are the changes to add syslogappender for issue #330. Fairly basic right now but let me know if any changes should be made.
Thanks!

### CODE REVIEW

**Comment by pditommaso** [comment]
Thanks a lot for your contribution. I've suggested a couple of changes. In particular I think it should be possible to provide the syslog host parameters to override the defaults. 

My suggestion is to provide the ability to specify an optional argument for the `-syslog` option in the for `host:port:facility`. What do you think?

**Comment by pditommaso** [comment]
Nearly. I would avoid to add an extra parameter  just for the configuration. I was thinking to provide that values as the optional value of the `-syslog` option. Therefore: 

```
nextflow -syslog run .. etc 
```

Enables the syslog appender, while: 

```
 nextflow -syslog HOST:PORT:FACILITY  run .. etc 
```

Enables the syslog appender for that settings. Also it should be able to accept just the `HOST` or `HOST:PORT` or the full syntax `HOST:PORT:FACILITY`. 

To implement this behaviour you will need to declare the parameter as a `String` instead of a `boolean`, then it needed to provide a default value when the user specify the parameter with no argument (eg. `-` or `true`), as it is done for many other options [here](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/cli/Launcher.groovy#L235-L237). 

That method is invoked just before `LoggerHelper.configureLogger`.

**Comment by crashGoBoom** [comment]
@pditommaso Sorry I totally misunderstood! So with my latest commit its just one option that can accept just `HOST` or `HOST:PORT` or the full syntax. Note [here](https://github.com/nextflow-io/nextflow/pull/552/files#diff-e43ae2ad23fc638d1ff470d60c1ebd3cR239) Its a little different than the other option you referenced since those options seem to come after a command and this is a CLI Option that comes before the command. Let me know if there is anything else! Thanks!

**Comment by pditommaso** [comment]
OK, almost there. Please remove the `-s` option (since it's a very specific component it's better to have just the long option name) and do not commit the changes in the `Const` class. Thanks for your patience.

**Comment by crashGoBoom** [comment]
@pditommaso No worries! Made the change to no longer include the `Const` class as well as removing the -s option.  Let me know how it looks. Thanks again!

**Comment by pditommaso** [comment]
Very nice. It looks much better with a single commit. Thanks a lot for your contribution!

**Comment by crashGoBoom** [comment]
Thank you so much @pditommaso ! Please feel free to keep in touch if you have any changes / improvement suggestions. 👍

**Pull request merged**
