### PR TITLE
Google Life Sciences update credential handling.

### PR DESCRIPTION
**Pull request by mbookman**
This is a suggested implementation for updating credentials handling for the Google Life Sciences executor as discussed in #1709.

Automatically pick up Application Default Credentials removing explicit requirements for the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to be set.

I assume there are some tests to update. Feel free to take over this PR or point me to where to updates tests.

### CODE REVIEW

**Review by pditommaso — CHANGES_REQUESTED** [review]
Thanks a lot for submitting this PR. I'm fine with it, however, it would be important to keep backward compatibility with current behavior. 

Therefore my suggestion is that if NF detects the `GOOGLE_APPLICATION_CREDENTIALS` it continues with the current behavior, otherwise it applies the logic you are suggesting.

**Comment by mbookman** [comment]
Thanks Paolo. I have restored the previous behavior when `GOOGLE_APPLICATION_CREDENTIALS` is set.

There is a small drawback to preserving the current behavior if a user wants to use a service account credential file to run workflows in different projects.  In that case, they need to edit the JSON and change the project ID. If it is something that they do frequently, they can have two copies of their credential file, for example:

```
$ ls my_nextflow_creds/

my-creds-file.project_A.json
my-creds-file.project_B.json
```

(where the only difference between the above two files is the `project_id` field) and then set `GOOGLE_APPLICATION_CREDENTIALS` to point to the respective JSON for different runs.

In practice, when people use service accounts, they tend to restrict usage to the associated Cloud project. Further, I think going forward, most use cases won't set `GOOGLE_APPLICATION_CREDENTIALS` anyway and the appropriate Application Default Credentials will get picked up (and the project ID will come from the nextflow config).

**Comment by pditommaso** [comment]
Hi, Sorry for the late reply. 

> There is a small drawback to preserving the current behavior if a user wants to use a service account credential file to run workflows in different projects

In this case, the projectId could be set in the nextflow config. Do you agree? 

Also please, sign-off your commit to make the DCO bot to pass the check https://github.com/nextflow-io/nextflow/pull/1776/checks?check_run_id=1323499154

**Comment by pditommaso** [comment]
One more thing, still the google region or zone to be used should be provided in the nextflow config. Does make sense to you ?

**Comment by mbookman** [comment]
Re: _In this case, the projectId could be set in the nextflow config. Do you agree?_

I think it would be the preferred behavior for the nextflow config to override the service account config, but in the current implementation, that would raise an error:

```
        def credsFile = env.get('GOOGLE_APPLICATION_CREDENTIALS')
        final projectId = GoogleLifeSciencesConfig.getProjectIdFromCreds(credsFile)

        config = GoogleLifeSciencesConfig.fromSession(session)
        if( !config.project )
            config.project = projectId
        else if( config.project != projectId )
            throw new AbortOperationException("Project Id `$config.project` declared in the nextflow config file does not match the one expected by credentials file: $credsFile")
```

**Comment by pditommaso** [comment]
You are right, now I'm also remembering that this was how it was working in the past (the project id in the config had precedence) but users tended to forget to change/update it resulting in the execution hanging. 

I think it would be better to keep it and modify it as following: 

```
        def projectId
        def credsFile = env.get('GOOGLE_APPLICATION_CREDENTIALS')
        if( credsFile && (projectId = GoogleLifeSciencesConfig.getProjectIdFromCreds(credsFile)) ) {
            if( !config.project )
                config.project = projectId
            else if( config.project != projectId )
                throw new AbortOperationException("Project Id `$config.project` declared in the nextflow config file does not match the one expected by credentials file: $credsFile")
        } 
        
        if( !config.project ) {
            throw new AbortOperationException("Missing Google project Id -- Specify it adding the setting `google.project='your-project-id'` in the nextflow.config file")
        }
```

To summarise: 
1. try to fetch the projectId from the creds file 
2. if exists make sure matches the one in the nextflow config
3. use the creds projectId when in the nexflow config is missing 
4. stop if no projectId is given either from creds file or nextflow config 

Happy to merge once the commit is signed-off.

**Comment by mbookman** [comment]
commit is signed off

**Comment by pditommaso** [comment]
Nice. Thanks for contributing to the project. I've merged this PR manually.

**Pull request closed without merging**
