### PR TITLE
Add warning about using clusterOptions with process directives

### PR DESCRIPTION
**Pull request by bentsherman**
Close https://github.com/seqeralabs/nf-tower-docs/issues/432

### CODE REVIEW

**Review by pditommaso — APPROVED** [review]

**Comment by pditommaso** [comment]
@ewels Haven't this docs change triggered the [code CI build & test](https://github.com/nextflow-io/nextflow/actions/runs/6039441915)? Am I wrong?

**Comment by ewels** [comment]
I think it's (mostly) working as expected.

## Build

The build steps are required, so they _have_ to run, otherwise you can't merge the PR:

CleanShot 2023-08-31 at 21 16 54@2x

Once triggered, the actions workflow looks for any changes outside of the `docs` folder:

https://github.com/nextflow-io/nextflow/blob/a1e1d3ca322afd64eb6d67bc7bb8e9d2a8ff4c00/.github/workflows/build.yml#L39-L43

A bunch of the steps in the workflow are then skipped if that evaluates to `false`:

https://github.com/nextflow-io/nextflow/blob/a1e1d3ca322afd64eb6d67bc7bb8e9d2a8ff4c00/.github/workflows/build.yml#L45-L46

You can see those steps being skipped in the run that you linked to, in the `Build` jobs:

CleanShot 2023-08-31 at 21 18 52@2x

This means that the required `Build` job does run, fulfilling the branch protection requirement so that the PR can be merged. However, because the main steps are skipped, it only took 17 seconds to run:



## Test

The `test` jobs come from a second, different job definition in the workflow file:

https://github.com/nextflow-io/nextflow/blob/a1e1d3ca322afd64eb6d67bc7bb8e9d2a8ff4c00/.github/workflows/build.yml#L94-L95

These have no docs logic attached to them. So they just always run.

I did originally add logic to skip these steps in https://github.com/nextflow-io/nextflow/commit/9f09e7b0f0e9c0f22d440dbd8d166bea66d936aa (the new `&& needs.build.outputs.any_changed == 'true'` bit):

```yaml
  test:
    if: ${{ !contains(github.event.head_commit.message, '[ci fast]') && needs.build.outputs.any_changed == 'true' }}
```

But it looks like you removed it again in https://github.com/nextflow-io/nextflow/commit/5c429046f2691cdca11ad3734f592c1d0e166967 👀  🚮 💥 

Maybe this was a mistake? I'll open a PR to add that back again, so that the tests are skipped for docs-only PRs..

**Comment by ewels** [comment]
Opened https://github.com/nextflow-io/nextflow/pull/4250 to skip tests again on docs-only PRs.

**Review by pditommaso — APPROVED** [review]

**Comment by pditommaso** [comment]
> But it looks like you removed it again in https://github.com/nextflow-io/nextflow/commit/5c429046f2691cdca11ad3734f592c1d0e166967

Oops, didn't realise that. sorry!

**Comment by ewels** [comment]
No worries, easy to do!

**Pull request merged**
