### PR TITLE
Add boot disk, cpu platform to google batch

### LINKED ISSUE #3049: Add support for Google Batch boot disk size
The Google Batch API allows the control of the boot disk size via the [following setting](https://github.com/googleapis/googleapis/blob/master/google/cloud/batch/v1/task.proto#L42). 

The Goal of this issue is to add support for it in Nextflow via the configuration setting 

```
google.lifeSciences.bootDiskSize = <size using MemUnit type>
```

### PR DESCRIPTION
**Pull request by bentsherman**
Closes #3049

### CODE REVIEW

**Review by pditommaso — APPROVED** [review]
Looks nice

**Comment by pditommaso** [comment]
damn, new conflicts

**Comment by bentsherman** [comment]
that is why I initially did it all in one PR 😅

**Comment by pditommaso** [comment]
Ok, thanks

**Pull request merged**
