### PR TITLE
Improve handling unstage  outputs and controls

### PR DESCRIPTION
**Pull request by pditommaso**
This is PR is an improvement of PR #5345 trying to keep the changes at level of of launcher script. 

In particular uses re-organise the `nxf_unstage` function splitting into `nxf_unstage_outputs` and `nxf_unstage_std_files` helper functions. 

@jorgee please check if it makes sense to you

### CODE REVIEW

**Comment by pditommaso** [comment]
It looks like I've broken Google LS, nothing useful in the logs 

```
Dec-02 08:37:48.504 [main] DEBUG nextflow.cli.Launcher - $> /Users/pditommaso/Projects/nextflow/launch.sh -C ./gls.config run ./test-subdirs.nf
Dec-02 08:37:48.557 [main] DEBUG nextflow.cli.CmdRun - N E X T F L O W  ~  version 24.10.0
Dec-02 08:37:48.566 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=dev; embedded=false; plugins-dir=/Users/pditommaso/Projects/nextflow/plugins; core-plugins: nf-amazon@2.9.0,nf-azure@1.10.1,nf-cloudcache@0.4.2,nf-codecommit@0.2.2,nf-console@1.1.4,nf-google@1.15.2,nf-tower@1.9.3,nf-wave@1.7.2
Dec-02 08:37:48.568 [main] DEBUG nextflow.plugin.DevPluginManager - Add plugin root repository: /Users/pditommaso/Projects/nextflow/plugins
Dec-02 08:37:48.569 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Dec-02 08:37:48.570 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Dec-02 08:37:48.572 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.12.0 in 'development' mode
Dec-02 08:37:48.579 [main] DEBUG nextflow.plugin.DevPluginClasspath - Groovy DEV plugin classpath: classes-dirs=[build/classes/groovy/main, build/classes/main, build/resources/main]; jars-dirs=[build/target/libs]
Dec-02 08:37:48.620 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-wave@1.7.2' resolved
Dec-02 08:37:48.620 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-amazon@2.9.0' resolved
Dec-02 08:37:48.620 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-google@1.15.2' resolved
Dec-02 08:37:48.620 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-tower@1.9.3' resolved
Dec-02 08:37:48.620 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-cloudcache@0.4.2' resolved
Dec-02 08:37:48.620 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-codecommit@0.2.2' resolved
Dec-02 08:37:48.620 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-console@1.1.4' resolved
Dec-02 08:37:48.620 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-azure@1.10.1' resolved
Dec-02 08:37:48.631 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /Users/pditommaso/Projects/nextflow/validation/gls.config
Dec-02 08:37:48.646 [main] DEBUG n.secret.LocalSecretsProvider - Secrets store: /Users/pditommaso/.nextflow/secrets/store.json
Dec-02 08:37:48.648 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@47c64cfe] - activable => nextflow.secret.LocalSecretsProvider@47c64cfe
Dec-02 08:37:48.650 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Dec-02 08:37:48.806 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 by global default
Dec-02 08:37:48.814 [main] DEBUG nextflow.cli.CmdRun - Launching `./test-subdirs.nf` [soggy_lovelace] DSL2 - revision: 7787a51584
Dec-02 08:37:48.815 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[nf-amazon@2.9.0, nf-google@1.15.2]
Dec-02 08:37:48.815 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[nf-amazon@2.9.0, nf-google@1.15.2, nf-tower@1.9.3]
Dec-02 08:37:48.815 [main] DEBUG nextflow.plugin.PluginUpdater - Update not supported during development mode
Dec-02 08:37:48.815 [main] DEBUG nextflow.plugin.PluginUpdater - Starting plugin nf-amazon version: 2.9.0
Dec-02 08:37:48.815 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-amazon@2.9.0'
Dec-02 08:37:48.836 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-amazon@2.9.0
Dec-02 08:37:48.844 [main] DEBUG nextflow.file.FileHelper - > Added 'S3FileSystemProvider' to list of installed providers [s3]
Dec-02 08:37:48.844 [main] DEBUG nextflow.plugin.PluginUpdater - Update not supported during development mode
Dec-02 08:37:48.844 [main] DEBUG nextflow.plugin.PluginUpdater - Starting plugin nf-google version: 1.15.2
Dec-02 08:37:48.844 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-google@1.15.2'
Dec-02 08:37:48.860 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-google@1.15.2
Dec-02 08:37:48.860 [main] DEBUG nextflow.plugin.PluginUpdater - Update not supported during development mode
Dec-02 08:37:48.860 [main] DEBUG nextflow.plugin.PluginUpdater - Starting plugin nf-tower version: 1.9.3
Dec-02 08:37:48.860 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-tower@1.9.3'
Dec-02 08:37:48.864 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-tower@1.9.3
Dec-02 08:37:48.888 [main] DEBUG nextflow.Session - Session UUID: 6d6e0bc7-a86e-44ed-989e-25a19dd3b37b
Dec-02 08:37:48.888 [main] DEBUG nextflow.Session - Run name: soggy_lovelace
Dec-02 08:37:48.888 [main] DEBUG nextflow.Session - Executor pool size: 11
Dec-02 08:37:48.981 [main] DEBUG nextflow.file.FilePorter - File porter settings maxRetries=3; maxTransfers=50; pollTimeout=null
Dec-02 08:37:48.992 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 24.10.0 build 5928
  Created: 27-10-2024 18:36 UTC (18:36 BST)
  System: Mac OS X 15.1.1
  Runtime: Groovy 4.0.24 on OpenJDK 64-Bit Server VM 21+35
  Encoding: UTF-8 (UTF-8)
  Process: 85074@Paolos-MacBook-Pro.local [127.0.0.1]
  CPUs: 11 - Mem: 36 GB (92.9 MB) - Swap: 0 (0) - Virtual threads ON
Dec-02 08:37:48.998 [main] DEBUG nextflow.Session - Work-dir: gs://rnaseq-nf/scratch [Mac OS X]
Dec-02 08:37:48.998 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /Users/pditommaso/Projects/nextflow/validation/bin
Dec-02 08:37:49.014 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[AwsBatchExecutor, GoogleLifeSciencesExecutor, GoogleBatchExecutor]
Dec-02 08:37:49.021 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Dec-02 08:37:49.023 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
Dec-02 08:37:49.030 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Dec-02 08:37:49.034 [main] DEBUG nextflow.util.CustomPoolFactory - Creating virtual thread pool
Dec-02 08:37:49.059 [main] DEBUG nextflow.Session - Session start
Dec-02 08:37:49.140 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Dec-02 08:37:49.178 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: google-lifesciences
Dec-02 08:37:49.179 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'google-lifesciences'
Dec-02 08:37:49.179 [main] DEBUG nextflow.executor.Executor - [warm up] executor > google-lifesciences
Dec-02 08:37:49.185 [main] DEBUG n.processor.TaskPollingMonitor - Creating task monitor for executor 'google-lifesciences' > capacity: 1000; pollInterval: 10s; dumpInterval: 5m 
Dec-02 08:37:49.187 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: google-lifesciences)
Dec-02 08:37:49.188 [main] WARN  n.c.g.l.GoogleLifeSciencesExecutor - Google Cloud Life Sciences API Cloud Life Sciences is deprecated and will no longer be available on Google Cloud after July 8, 2025. Consider migrating to Google Cloud Batch instead. Read more at this link: https://cloud.google.com/life-sciences/docs/deprecations
Dec-02 08:37:49.193 [main] DEBUG n.c.g.l.GoogleLifeSciencesExecutor - Google Life Science config=GoogleLifeSciencesConfig(project:my-nf-project-261815, zones:[], regions:[europe-west2], preemptible:false, remoteBinDir:null, location:europe-west2, disableBinDir:false, bootDiskSize:null, cpuPlatform:null, sshDaemon:false, sshImage:gcr.io/cloud-genomics-pipelines/tools, debugMode:null, copyImage:google/cloud-sdk:slim, usePrivateAddress:false, enableRequesterPaysBuckets:false, network:null, subnetwork:null, serviceAccountEmail:null, parallelThreadCount:1, downloadMaxComponents:8, keepAliveOnFailure:false, maxParallelTransfers:4, maxTransferAttempts:1, delayBetweenAttempts:10s)
Dec-02 08:37:49.317 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: google-lifesciences
Dec-02 08:37:49.317 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'google-lifesciences'
Dec-02 08:37:49.326 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: bar, foo
Dec-02 08:37:49.326 [main] DEBUG nextflow.Session - Igniting dataflow network (2)
Dec-02 08:37:49.326 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > foo
Dec-02 08:37:49.326 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > bar
Dec-02 08:37:49.327 [main] DEBUG nextflow.script.ScriptRunner - Parsed script files:
  Script_41838a4c32a240e9: /Users/pditommaso/Projects/nextflow/validation/test-subdirs.nf
Dec-02 08:37:49.327 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination 
Dec-02 08:37:49.327 [main] DEBUG nextflow.Session - Session await
Dec-02 08:37:51.841 [Task submitter] DEBUG n.c.g.l.GoogleLifeSciencesTaskHandler - [GLS] Task submitted > foo - Pipeline Id: 12653942769597774811
Dec-02 08:37:51.842 [Task submitter] INFO  nextflow.Session - [9a/c98bd4] Submitted process > foo
Dec-02 08:41:40.137 [Task monitor] DEBUG n.c.g.l.GoogleLifeSciencesTaskHandler - [GLS] Task complete > foo - Start Time: 2024-12-02T08:38:09.314060439Z - End Time: 2024-12-02T08:41:35.352941256Z
Dec-02 08:41:40.612 [Task monitor] DEBUG n.c.g.l.GoogleLifeSciencesTaskHandler - [GLS] Cannot read exitstatus for task: `foo` | gs://rnaseq-nf/scratch/9a/c98bd48c95301b90bf77e13464afbf/.exitcode
Dec-02 08:41:40.614 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: foo; status: COMPLETED; exit: null; error: -; workDir: gs://rnaseq-nf/scratch/9a/c98bd48c95301b90bf77e13464afbf]
Dec-02 08:41:40.799 [TaskFinalizer-1] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=foo; work-dir=gs://rnaseq-nf/scratch/9a/c98bd48c95301b90bf77e13464afbf
  error [nextflow.exception.ProcessFailedException]: Process `foo` terminated with an error exit status (null)
Dec-02 08:41:40.986 [TaskFinalizer-1] ERROR nextflow.processor.TaskProcessor - Error executing process > 'foo'

Caused by:
  Process `foo` terminated with an error exit status (null)


Command executed:

  mkdir -p gsfolder/sub
  touch gsfolder/test1.txt
  touch gsfolder/sub/test1.txt
  
  mkdir gsfolder2
  touch gsfolder2/test2.txt
  
  mkdir gsfolder3
  touch gsfolder3/test3.txt
  
  mkdir gsfolder4
  touch gsfolder4/test4.txt
  
  echo 'Hello 5'>>test5.txt
  echo 'Hello 6'>>test6.txt
  echo 'Hello 7'>>test7.txt
  
  mkdir -p gsfolder5/sub
  touch gsfolder5/sub/test8.txt

Command exit status:
  null

Command output:
  (empty)

Work dir:
  gs://rnaseq-nf/scratch/9a/c98bd48c95301b90bf77e13464afbf

Container:
  quay.io/nextflow/rnaseq-nf:latest
```

**Comment by pditommaso** [comment]
```
» gs cat gs://rnaseq-nf/scratch/9a/c98bd48c95301b90bf77e13464afbf/.command.log
+ cd /scratch/9a/c98bd48c95301b90bf77e13464afbf
+ gsutil -m -q cp gs://rnaseq-nf/scratch/9a/c98bd48c95301b90bf77e13464afbf/.command.run .
+ bash .command.run nxf_stage
+ [[ '' -gt 0 ]]
+ true
.command.run: line 183: nxf_unstage_ret: unbound variable
+ cd /scratch/9a/c98bd48c95301b90bf77e13464afbf
+ bash .command.run nxf_unstage
CommandException: No URLs matched: .exitcode
CommandException: 1 file/object could not be transferred.
+ bash .command.run nxf_unstage_std_files
CommandException: No URLs matched: .exitcode
CommandException: 1 file/object could not be transferred.
validation (test_3711_v2)» gs cat gs://rnaseq-nf/scratch/9a/c98bd48c95301b90bf77e13464afbf/.command.run
#!/bin/bash
### ---
### name: 'foo'
### container: 'quay.io/nextflow/rnaseq-nf:latest'
### outputs:
### - 'gsfolder/'
### - 'gsfolder2'
### - 'gsfolder3'
### - 'gsfolder4'
### - 'test5.txt'
### - 'test6.txt'
### - 'test7.txt'
### - 'gsfolder5/sub'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

# bash helper functions
nxf_cp_retry() {
    local max_attempts=1
    local timeout=10
    local attempt=0
    local exitCode=0
    while (( $attempt < $max_attempts ))
    do
      if "$@"
        then
          return 0
      else
        exitCode=$?
      fi
      if [[ $exitCode == 0 ]]
      then
        break
      fi
      nxf_sleep $timeout
      attempt=$(( attempt + 1 ))
      timeout=$(( timeout * 2 ))
    done
}

nxf_parallel() {
    IFS=$'\n'
    local cmd=("$@")
    local cpus=$(nproc 2>/dev/null || < /proc/cpuinfo grep '^process' -c)
    local max=$(if (( cpus>4 )); then echo 4; else echo $cpus; fi)
    local i=0
    local pid=()
    (
    set +u
    while ((i<${#cmd[@]})); do
        local copy=()
        for x in "${pid[@]}"; do
          # if the process exist, keep in the 'copy' array, otherwise wait on it to capture the exit code
          # see https://github.com/nextflow-io/nextflow/pull/4050
          [[ -e /proc/$x ]] && copy+=($x) || wait $x
        done
        pid=("${copy[@]}")

        if ((${#pid[@]}>=$max)); then
          nxf_sleep 0.2
        else
          eval "${cmd[$i]}" &
          pid+=($!)
          ((i+=1))
        fi
    done
    for p in "${pid[@]}"; do
        wait $p
    done
    )
    unset IFS
}

# google storage helper
gs_opts=('-q' '-m' '-o' 'GSUtil:parallel_thread_count=1' '-o' 'GSUtil:sliced_object_download_max_components=8')

nxf_gs_download() {
    local source=$1
    local target=$2
    local project=$3
    local basedir=$(dirname $2)
    local ret
    local opts=("${gs_opts[@]}")
    if [[ $project ]]; then
      opts+=('-u' "$project")
    fi

    ## download assuming it's a file download
    mkdir -p $basedir
    ret=$(gsutil ${opts[@]} cp "$source" "$target" 2>&1) || {
        ## if fails check if it was trying to download a directory
        mkdir $target
        gsutil ${opts[@]} cp -R "$source/*" "$target" || {
          rm -rf $target
          >&2 echo "Unable to download path: $source"
          exit 1
        }
    }
}

nxf_gs_upload() {
    local name=$1
    local target=$2
    gsutil ${gs_opts[@]} cp -R "$name" "$target/$name"
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:0} -ne 0 ]] && exit_status=${nxf_unstage_ret}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /scratch/9a/c98bd48c95301b90bf77e13464afbf/.exitcode
    set +u
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /scratch/9a/c98bd48c95301b90bf77e13464afbf/.command.sh
}

nxf_stage() {
    true
    # stage input files
    echo start | gsutil -q cp  -c - gs://rnaseq-nf/scratch/9a/c98bd48c95301b90bf77e13464afbf/.command.begin
    downloads=(true)
    downloads+=("nxf_gs_download gs://rnaseq-nf/scratch/9a/c98bd48c95301b90bf77e13464afbf/.command.sh .command.sh ")
    nxf_parallel "${downloads[@]}"
}

nxf_unstage_outputs() {
    true
    uploads=()
    IFS=$'\n'
    for name in $(eval "ls -1d gsfolder gsfolder2 gsfolder3 gsfolder4 test5.txt test6.txt test7.txt gsfolder5/sub" | sort | uniq); do
        uploads+=("nxf_gs_upload '$name' gs://rnaseq-nf/scratch/9a/c98bd48c95301b90bf77e13464afbf")
    done
    unset IFS
    nxf_parallel "${uploads[@]}"
}

nxf_unstage_std_files() {
    true
    gsutil -m -q cp -R .command.out gs://rnaseq-nf/scratch/9a/c98bd48c95301b90bf77e13464afbf/.command.out || true
    gsutil -m -q cp -R .command.err gs://rnaseq-nf/scratch/9a/c98bd48c95301b90bf77e13464afbf/.command.err || true
    gsutil -m -q cp -R .exitcode gs://rnaseq-nf/scratch/9a/c98bd48c95301b90bf77e13464afbf/.exitcode || true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_std_files
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=/scratch/9a/c98bd48c95301b90bf77e13464afbf
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
}

$NXF_ENTRY
```

and 

```
» gs cat gs://rnaseq-nf/scratch/9a/c98bd48c95301b90bf77e13464afbf/.command.log
+ cd /scratch/9a/c98bd48c95301b90bf77e13464afbf
+ gsutil -m -q cp gs://rnaseq-nf/scratch/9a/c98bd48c95301b90bf77e13464afbf/.command.run .
+ bash .command.run nxf_stage
+ [[ '' -gt 0 ]]
+ true
.command.run: line 183: nxf_unstage_ret: unbound variable
+ cd /scratch/9a/c98bd48c95301b90bf77e13464afbf
+ bash .command.run nxf_unstage
CommandException: No URLs matched: .exitcode
CommandException: 1 file/object could not be transferred.
+ bash .command.run nxf_unstage_std_files
CommandException: No URLs matched: .exitcode
CommandException: 1 file/object could not be transferred.
```

**Comment by jorgee** [comment]
I like the improvement reduces the changes from the original code. I am checking the error I think I also had one when doing the original implementation

**Comment by pditommaso** [comment]
Missing google tests 🥁

**Review by jorgee — APPROVED** [review]

**Pull request merged**
