### PR TITLE
Remove outdated FAQ page from docs

### PR DESCRIPTION
**Pull request by mribeirodantas**

### CODE REVIEW

**Comment by bentsherman** [comment]
The FAQ page is really old, and it isn't linked in the nav bar for some reason.

@pditommaso What do you want to do with the FAQ page? Do you think it's worth keeping?

**Comment by pditommaso** [comment]
Yeah, it really outdated. I'd say to remove and rewrite from scratch on https://github.com/nextflow-io/nextflow/discussions

**Comment by bentsherman** [comment]
@mribeirodantas Are you up to the task? The goal would be to scan the Q&A discussions and pick out the questions that come up repeatedly or seem important, and collect them into an FAQ page for the Nextflow docs. It could probably be done over the course of a few doc sessions.

**Comment by mribeirodantas** [comment]
> The FAQ page is really old, and it isn't linked in the nav bar for some reason.
Yeah, it disappeared from the nav bar, but you can still find it through the search box. I (and I believe other people) always landed there when I searched for the `bin` folder, for example.

I think it's good to have a FAQ section in the official docs, and also to mention the Nextflow Patterns website there. So we're gonna keep the FAQ in the docs?

**Comment by bentsherman** [comment]
@mribeirodantas Check this thread again, I think you missed a few of our comments.

We're saying, scrap the current FAQ page and re-create it from scratch. Many of those FAQs aren't as relevant any more. Instead you can go through the Q&A Discussions page to find good FAQs, i.e. questions that are asked there repeatedly or just seem worth documenting.

**Comment by mribeirodantas** [comment]
I had read all comments, but I thought Paolo meant something different. So we're really gonna keep the FAQ [section] in the docs, but with new questions and answers. Great for me! 🥳 I will work on it.

**Comment by pditommaso** [comment]
Hi @mribeirodantas, thanks for improving this, but I agree with Ben the FAQ content and structure are quite outdated. 

Also, it would be better not to keep it in the docs but in the GitHub discussion to allow a quicker iteration/editing and promote a better interaction with the community

**Comment by mribeirodantas** [comment]
Ok, as I had understood your message initially then. I will delete the FAQ pages then.

**Comment by mribeirodantas** [comment]
LGTM?

**Comment by pditommaso** [comment]
Vamos!

**Comment by mribeirodantas** [comment]
🇧🇷 🥳

**Pull request merged**
