### PR TITLE
Fix failing CI tests

### PR DESCRIPTION
**Pull request by bentsherman**
see discussion in #4712

### CODE REVIEW

**Comment by bentsherman** [comment]
@pditommaso don't know if you did something with the github secrets but unit tests are passing here 👍

**Comment by bentsherman** [comment]
LGTM👍

**Comment by bentsherman** [comment]
@pditommaso why was this PR reverted? even if it wasn't related to the google batch CI tests, they are still good changes. the docs test actually will fail sometimes without this change

**Comment by pditommaso** [comment]
Becasue `GOOGLE_APPLICATION_CREDENTIALS` is required for that test

**Comment by bentsherman** [comment]
Then keep the docs snippet?

**Pull request merged**
