### PR TITLE
html-trace improvements

### PR DESCRIPTION
**Pull request by ewels**
* New plots for % allocated cpus and memory
* New plot for disk io
* More table formatting and unit tidying
* Updated bootstrap framework
* New moment.js framework to handle nasty date formatting stuff

Still a couple of minor TODOs:

* The dynamically generated plots don't pick up on the screen width so end up all narrow and weird
* The table columns are still super wide in places
* Other general tidying perhaps?

### CODE REVIEW

**Comment by ewels** [comment]
Example output: [test_report.html.zip](https://github.com/nextflow-io/nextflow/files/1399935/test_report.html.zip)

If anyone has any ideas about my new Docker error in the example, also welcome! ;)

**Comment by pditommaso** [comment]
Beautiful. I'm going to merge on the master! About Docker a friend is telling me that it could be a missing dependency in the container .. :)

**Comment by ewels** [comment]
Great! Give me a couple of hours before going to master please though - I have a couple of tweaks nearly done this morning (currently in a meeting though so can't quite push yet).

**Comment by pditommaso** [comment]
OK, sounds good.

**Pull request merged**
