### PR TITLE
Nullable input/output paths

### LINKED ISSUE #2678: DSL2 - emit tuples with optional values
## Usage scenario 

I'd like to be able to return a tuple with optional elements. For example, by defining the output as `tuple val(id), path("output.txt"), path("output2.txt" optional: true)`, I'd like a process to be able to emit an event `["foo", path("output.txt"), null]`.

The process and downstream processes can take a while to run, so using a multi-channel output in combination with a groupTuple() (See Attempt 3) is very undesirable.

## Suggested implementation 

Probably this would require:

* altering [TupleOutParam.groovy#L103-L105](https://github.com/nextflow-io/nextflow/blob/856aacf0ef9a6de65214edc41af7b4e0d894b136/modules/nextflow/src/main/groovy/nextflow/script/params/TupleOutParam.groovy#L103-L105) so that FileOutParams can be optional even if the TupleOutParam is not optional. 
* Change something to [TaskProcessor.groovy#L1519-L1524](https://github.com/nextflow-io/nextflow/blob/856aacf0ef9a6de65214edc41af7b4e0d894b136/modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy#L1519-L1524) so that non-optional TupleOutParams with optional FileOutParams are emitted instead of throwing a MissingFileException.

## Reproducible examples

I made several attempts at getting this to run with the current implementation of Nextflow. To summarise:

* Attempt 1: optional path in non-optional tuple → errors
* Attempt 2: optional tuple → tuple with missing file is not emitted
* Attempt 3: multi-channel output followed by a groupTuple → introduces a bottleneck in workflows with long execution times
* Attempt 4: a messy workaround solution to this problem

### Attempt 1: optional path in tuple
Because of [TupleOutParam.groovy#L103-L105](https://github.com/nextflow-io/nextflow/blob/856aacf0ef9a6de65214edc41af7b4e0d894b136/modules/nextflow/src/main/groovy/nextflow/script/params/TupleOutParam.groovy#L103-L105), this optional value is overridden by the tuple's value for 'optional', namely false.

If I try to run the code following code, Nextflow will produce an error when output2.txt is missing.

<details>
  <summary>Attempt 1 reprex</summary>

```groovy
nextflow.enable.dsl=2

process test_process1 {
  input:
    tuple val(id)
  output:
    tuple val(id), path("output.txt"), path("output2.txt", optional: true)
  script:
    """
    echo $id > output.txt
    if [[ "$id" == "foo" ]]; then
      echo $id > output2.txt
    fi
    """
}

workflow {
  Channel.fromList( ["foo", "bar"] )
    | view { "input: ${it}" }
    | test_process1
    | view { "output: ${it}" }
}
```
↓
```
$ NXF_VER=21.10.6 nextflow run test_outputs_opt1.nf
input: foo
input: bar
output: [foo, work/81/e866d5e329c9ac9980a0c9313d347b/output.txt, work/81/e866d5e329c9ac9980a0c9313d347b/output2.txt]
[8c/e39e04] NOTE: Missing output file(s) `output2.txt` expected by process `test_process1 (2)` -- Error is ignored
```
</details>

### Attempt 2: make the whole tuple optional

By making the whole tuple optional, Nextflow doesn't produce an error anymore, but my whole tuple is removed, which is undesirable.

<details>
  <summary>Attempt 2 reprex</summary>

```groovy
nextflow.enable.dsl=2

process test_process1 {
  input:
    tuple val(id)
  output:
    tuple val(id), path("output.txt"), path("output2.txt") optional true
  script:
    """
    echo $id > output.txt
    if [[ "$id" == "foo" ]]; then
      echo $id > output2.txt
    fi
    """
}

workflow {
  Channel.fromList( ["foo", "bar"] )
    | view { "input: ${it}" }
    | test_process1
    | view { "output: ${it}" }
}
```
↓
```
$ NXF_VER=21.10.6 nextflow run test_outputs_opt2.nf
input: foo
input: bar
output: [foo, work/95/0e07ee0b94834d4587509b152aa354/output.txt, /home/rcannoodwork/95/0e07ee0b94834d4587509b152aa354/output2.txt]
```
</details>

### Attempt 3: multichannel output

This approach is what is proposed in #1980. However, having to use 'groupTuple()' to merge the multichannel output back into a single event is also undesirable, as now the whole Channel needs to be executed before any events can be emitted downstream. Note that setting `size: 2` doesn't work in this case, since some tuples should have one element, others two.

<details>
  <summary>Attempt 3 reprex</summary>

```groovy
nextflow.enable.dsl=2

process test_process2 {
  input:
    tuple val(id)
  output:
    tuple val(id), val("output1"), path("output.txt")
    tuple val(id), val("output2"), path("output2.txt") optional true
  script:
    """
    echo $id > output.txt
    if [[ "$id" == "foo" ]]; then
      echo $id > output2.txt
    fi
    """
}

workflow {
  Channel.fromList( ["foo", "bar"] )
    | view { "input: ${it}" }
    | test_process2
    | mix
    | groupTuple(by: 0)
    | map{ [ it[0], [it[1], it[2]].transpose().collectEntries() ]}
    | view { "output: ${it}" }
}
```
↓
```
$ NXF_VER=21.10.6 nextflow run test_outputs_opt3.nf
input: foo
input: bar
output: [bar, [output1:work/9c/97b3a2884f97594532a19923e6c748/output.txt]]
output: [foo, [output1:work/60/984231826c9a9cc2a1e1cf29e16fdb/output.txt, output2:work/60/984231826c9a9cc2a1e1cf29e16fdb/output2.txt]]
```
</details>

### Attempt 4: add junk to output

By adding a file known to exist (e.g. ".command.sh") to the output, I can force the Channel to always return a tuple. This _works_, but the code looks quite messy and I need to do postprocessing to remove the additional file.

<details>
  <summary>Attempt 4 reprex</summary>

```groovy
nextflow.enable.dsl=2

process test_process3 {
  input:
    tuple val(id)
  output:
    tuple val(id), path{[".command.sh", "output.txt"]}, path{[".command.sh", "output2.txt"]}
  script:
    """
    echo $id > output.txt
    if [[ "$id" == "foo" ]]; then
      echo $id > output2.txt
    fi
    """
}

workflow {
  Channel.fromList( ["foo", "bar"] )
    | view { "input: ${it}" }
    | test_process3
    | map { output ->
      map = [["output1", "output2"], output.drop(1)].transpose()
      map_without_dummy = map.collectEntries{ key, out ->
        if (out instanceof List && out.size() > 2) {
          [ key, out.drop(1) ]
        } else if (out instanceof List && out.size == 2) {
          [ key, out[1] ]
        } else {
          [ key, null ]
        }
      }
      [ output[0], map_without_dummy ]
    }
    | view { "output: ${it}" }
}
```
↓
```
$ NXF_VER=21.10.6 nextflow run test_outputs_opt4.nf
input: foo
input: bar
output: [foo, [output1:work/96/a51f95280ee3332f50b6b05a12596b/output.txt, output2:work/96/a51f95280ee3332f50b6b05a12596b/output2.txt]]
output: [bar, [output1:work/ec/87149bfea74975d37307d6a115c812/output.txt, output2:null]]
```
</details>

### PR DESCRIPTION
**Pull request by bentsherman**
Close #2678

This PR contains the support for nullable paths via `arity: '0..1'`, which was implemented in PR #3706 but ultimately excluded because it is tricky to implement.

With the new arity feature, you can set `arity: '0..*'` to specify that a path input/output should be a list and can be empty.

With this PR, you can also set `arity: '0..1'` to specify that a path input/output should be a single file but could also be null. Whereas `optional: true` emits nothing if no file is produced, this "nullable" path emits a null value which can be accepted by similarly nullable inputs.

The problem with the current implementation is that the null path is being passed through some code that it shouldn't, and produces this warning:
```
WARN: File system is unable to get file attributes file: nextflow.util.NullPath@7f -- Cause: java.nio.file.ProviderMismatchException
```

While it still works, ideally the null path should bypass any code that would try to use it like a real file.

Additionally, it should be considered whether nullable paths should be implemented with a separate option like `nullable: true` instead of adding it on to the arity feature, which might simplify the logic a bit.

### CODE REVIEW

**Comment by mjhipp** [comment]
@bentsherman this is an interesting change. 
Am I understanding correctly that with the newest edge release, you can use `arity: '0..1'` to get a list of `path` with max length 1? Essentially like an `Option[Path]` in languages like scala? 

And with this PR, instead of a list of max length 1, it would be just a `path` object that may or may not be `null`?

**Comment by bentsherman** [comment]
Yes. With `arity: '0..1'` it will emit nothing if there is no file, like `optional: true`. Whereas nullable would emit emit a "null" path that could trigger downstream tasks.

**Comment by mjhipp** [comment]
When I use the new edge (not this PR), it says `'0..1'` is not allowed

```
N E X T F L O W  ~  version 23.09.0-edge
Launching `foo.nf` [sick_keller] DSL2 - revision: bbf58d593f
Path arity 0..1 is not allowed

 -- Check script 'foo.nf' at line: 3 or see '.nextflow.log' file for more details
```

When using `'0..2'`, I am able to emit a channel (this works whether or not its wrapped in a tuple), that I can pass along to a downstream process.

```
process FOO {
  input:
    tuple path(bam), path(bai, arity: '0..2')
    val output // file name

  output:
    tuple path(output), path("${output - ~/.bam$/}.bai", arity: '0..2'), emit: bam_ch

  script:
    """
    touch $output
    ${bai ? "touch ${output - ~/.bam$/}.bai" : ''} 
    """
}

params.bai = [] // default to no index

workflow {
  FOO(
    tuple(params.bam, params.bai),
    'output.bam'
  )
  FOO.out.bam_ch.view { "bam/bai tuple: $it" }
}
```

When I run with an index, I get an index back (wrapped in a list)

```
❯ NXF_VER=23.09.0-edge ./nextflow run foo.nf --bam foo.bam --bai foo.bai
N E X T F L O W  ~  version 23.09.0-edge
Launching `foo.nf` [peaceful_hamilton] DSL2 - revision: a562747916
executor >  local (1)
executor >  local (1)
[8c/fb43ce] process > FOO [100%] 1 of 1 ✔
bam/bai tuple: [/Users/mikehipp/work/8c/fb43ce5ad904a1669594504f1c9d56/output.bam, [/Users/mikehipp/work/8c/fb43ce5ad904a1669594504f1c9d56/output.bai]]
```

When I run with no index, I get an empty list in place of the index, which can be used as an input downstream.

```
❯ NXF_VER=23.09.0-edge ./nextflow run foo.nf --bam foo.bam
N E X T F L O W  ~  version 23.09.0-edge
Launching `foo.nf` [loving_kalman] DSL2 - revision: 6b8955ef01
executor >  local (1)
[b5/cdcdcf] process > FOO [100%] 1 of 1 ✔
bam/bai tuple: [/Users/mikehipp/work/b5/cdcdcff85fcd0d5e0fe5cbf801ff89/output.bam, []]
```

Ideally and in my opinion, logically, I would think `'0..1'` should behave identically to `'0..2'` and `'0..*'` except it is limited to one file maximum. It can still output a channel that can be passed, except the channel is an empty list. Using an empty list for an optional file is how I have always handled this up to now. 

It just seems that using an empty list, like with `'0..*'`, would be a more consistent with the other behavior of the `arity` feature, rather than a null value.

**Comment by bentsherman** [comment]
Sorry, I got some things mixed up.

Arity `0..1` is not allowed right now, as a temporary stopgap until we figure out how to handle nullability the right way. I don't think emitting an empty array arity is `0..1` is the "correct way", because the intent is that it's a single file that could be null, and you want to emit the "null" file.

On the other hand, an empty array would make things simple. The problem with the null file approach (implemented in this PR) is that Nextflow is trying to use it like a real file throughout the code, so we either have to re-route null files or add more no-op behavior to the `NullPath` class.

You might be able to do `arity: '1', optional: true`, but I think the current implementation will still throw an error if no file is produced.

**Comment by mjhipp** [comment]
Thanks for the insight. 

You mention that the intent is to have a path that may or may not be `null`. I would like to ask if the real intent is to have a nullable path, or if the intent is to have some way to allow an optional output to trigger downstream processes, whether or it is present? If so, an empty list or a nullable path would accomplish that same intent?

**Comment by bentsherman** [comment]
It would. I just wonder if it could cause confusion with any dataflow logic between the two processes, where `null` and `[]` would have different behavior.

For example, `if ( file )` would be `false` for both `null` and `[]`, but `if ( file != null )` would be different. So if a user wants to use the nullable file in some way, which almost always involves a null check, they will get the right or wrong behavior depending on how they do it...

**Comment by bentsherman** [comment]
This is unlikely to be resolved before static types are implemented. I will try to fold nullable paths into #4553 , should be easier there anyway

**Comment by bentsherman** [comment]
Note to self on mapping static types to arity:

- `Path`: arity = `1`
- `Collection<Path>`: arity = `0..*`
- `Optional<Path>`: arity = `0..1`

Therefore the `arity` option will only remain relevant for inputs/outputs of type `Collection<Path>`, as a way to enforce a certain collection size/range.

**Pull request closed without merging**
